import Link from "next/link";
import { ArrowLeft, ArrowRight, CircleAlert, Code2, FlaskConical, GitBranch, MousePointer2, TimerReset } from "lucide-react";
import type { DocsArticle, DocsLanguage } from "../docs-data";
import type { CreativeGuide } from "../docs-creative-content";
import DocsSourceFooter from "./docs-source-footer";

function CodePanel({ code, t }: { code: NonNullable<CreativeGuide["stations"][number]["code"]>; t: DocsLanguage }) {
  return <div className="creative-code"><div><Code2 size={15} /><span>{code.language}</span><small>{t === "vi" ? "Mẫu thử" : "Specimen"}</small></div><pre><code>{code.value}</code></pre></div>;
}

function StationBody({ station, t }: { station: CreativeGuide["stations"][number]; t: DocsLanguage }) {
  return <><span className="creative-station-marker">{station.marker[t]}</span><h2>{station.title[t]}</h2><p>{station.narrative[t]}</p><ul>{station.beats.map((beat) => <li key={beat.en}>{beat[t]}</li>)}</ul>{station.code && <CodePanel code={station.code} t={t} />}{station.warning && <aside><CircleAlert size={17} /><span>{station.warning[t]}</span></aside>}</>;
}

function FrameLab({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-render-lab"><section className="creative-simulation frame-record"><header><TimerReset size={18} /><div><small>FRAME 0248</small><strong>{guide.simulation.label[t]}</strong></div><b>16.7ms</b></header><div className="frame-budget">{guide.simulation.tracks.map((track) => <article className={`tone-${track.tone}`} key={track.name.en}><span>{track.name[t]}</span><small>{track.detail[t]}</small></article>)}</div><footer><span>{t === "vi" ? "0ms · bắt đầu" : "0ms · start"}</span><span>{t === "vi" ? "16,7ms · deadline" : "16.7ms · deadline"}</span></footer></section><div className="frame-lab-notes">{guide.stations.map((station, index) => <section key={station.title.en} data-step={index + 1}><StationBody station={station} t={t} /></section>)}</div></div>;
}

function EventScene({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-event-scene"><section className="creative-simulation event-path"><header><MousePointer2 size={18} /><strong>{guide.simulation.label[t]}</strong><span>CLICK #A17</span></header><div className="event-dom-tree"><span>window</span><ArrowRight size={14} /><span>document</span><ArrowRight size={14} /><span>ul.docs</span><ArrowRight size={14} /><b>button.remove</b></div><div className="event-phases">{guide.simulation.tracks.map((track) => <article className={`tone-${track.tone}`} key={track.name.en}><small>{track.name[t]}</small><strong>{track.detail[t]}</strong></article>)}</div></section><div className="event-case-files">{guide.stations.map((station) => <section key={station.title.en}><div className="case-pin" /><StationBody station={station} t={t} /></section>)}</div></div>;
}

function AsyncControlRoom({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-async-control-room"><section className="creative-simulation async-graph"><header><GitBranch size={18} /><strong>{guide.simulation.label[t]}</strong><span>RUNNING</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><i>{String(index + 1).padStart(2, "0")}</i><div><strong>{track.name[t]}</strong><small>{track.detail[t]}</small></div>{index < guide.simulation.tracks.length - 1 && <ArrowRight size={16} />}</article>)}</div></section><div className="async-console-stack">{guide.stations.map((station, index) => <section key={station.title.en}><span className="console-index">{String(index + 1).padStart(2, "0")}</span><div><StationBody station={station} t={t} /></div></section>)}</div></div>;
}

function IncidentDesk({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-incident-desk"><section className="creative-simulation incident-trace"><header><CircleAlert size={18} /><strong>{guide.simulation.label[t]}</strong><span>OPEN</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><b>{String(index + 1).padStart(2, "0")}</b><div><strong>{track.name[t]}</strong><small>{track.detail[t]}</small></div>{index < guide.simulation.tracks.length - 1 && <ArrowRight size={16} />}</article>)}</div></section><div className="incident-files">{guide.stations.map((station, index) => <section key={station.title.en} data-case={String(index + 1).padStart(2, "0")}><StationBody station={station} t={t} /></section>)}</div></div>;
}

function ModuleGraph({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-module-graph"><section className="creative-simulation module-map"><header><GitBranch size={18} /><strong>{guide.simulation.label[t]}</strong><span>ES MODULE</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><Code2 size={16} /><strong>{track.name[t]}</strong><small>{track.detail[t]}</small>{index < guide.simulation.tracks.length - 1 && <ArrowRight size={17} />}</article>)}</div></section><div className="module-chapters">{guide.stations.map((station, index) => <section key={station.title.en}><span className="module-coordinate">M{index + 1}</span><StationBody station={station} t={t} /></section>)}</div></div>;
}

function PackageConsole({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-package-console"><section className="creative-simulation package-manifest"><header><Code2 size={18} /><strong>{guide.simulation.label[t]}</strong><span>LOCKED</span></header><div>{guide.simulation.tracks.map((track) => <article className={`tone-${track.tone}`} key={track.name.en}><span>{track.name[t]}</span><code>{track.detail[t]}</code></article>)}</div></section><div className="package-panels">{guide.stations.map((station, index) => <section key={station.title.en}><b>{String(index + 1).padStart(2, "0")}</b><div><StationBody station={station} t={t} /></div></section>)}</div></div>;
}
function ConfigVault({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-config-vault"><section className="creative-simulation config-route"><header><Code2 size={18} /><strong>{guide.simulation.label[t]}</strong><span>SERVER ONLY</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><b>{index + 1}</b><strong>{track.name[t]}</strong><small>{track.detail[t]}</small></article>)}</div></section><div className="config-chambers">{guide.stations.map((station, index) => <section key={station.title.en}><span>VAULT/{String(index + 1).padStart(2, "0")}</span><StationBody station={station} t={t} /></section>)}</div></div>;
}

function GitWorkbench({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-git-workbench"><section className="creative-simulation git-areas"><header><GitBranch size={18} /><strong>{guide.simulation.label[t]}</strong><span>HEAD → MAIN</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><small>0{index + 1}</small><strong>{track.name[t]}</strong><code>{track.detail[t]}</code>{index < guide.simulation.tracks.length - 1 && <ArrowRight size={16} />}</article>)}</div></section><div className="git-bench-notes">{guide.stations.map((station, index) => <section key={station.title.en} data-command={`git:${index + 1}`}><StationBody station={station} t={t} /></section>)}</div></div>;
}

function HistoryLedger({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-history-ledger"><section className="creative-simulation commit-anatomy"><header><GitBranch size={18} /><strong>{guide.simulation.label[t]}</strong><span>a14f3c2</span></header><div>{guide.simulation.tracks.map((track) => <article className={`tone-${track.tone}`} key={track.name.en}><b>{track.name[t]}</b><span>{track.detail[t]}</span></article>)}</div></section><div className="ledger-entries">{guide.stations.map((station, index) => <section key={station.title.en}><span className="ledger-hash">{`0${index + 1}`} · {index === 0 ? "HEAD" : "HEAD~" + index}</span><StationBody station={station} t={t} /></section>)}</div></div>;
}
function ReviewRoom({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-review-room"><section className="creative-simulation review-queue"><header><GitBranch size={18} /><strong>{guide.simulation.label[t]}</strong><span>REVIEW REQUIRED</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><i>{String(index + 1).padStart(2, "0")}</i><strong>{track.name[t]}</strong><small>{track.detail[t]}</small></article>)}</div></section><div className="review-packets">{guide.stations.map((station, index) => <section key={station.title.en}><span className="review-status">{index < 2 ? "IN REVIEW" : index === 2 ? "DISCUSS" : "MERGE GATE"}</span><StationBody station={station} t={t} /></section>)}</div></div>;
}

function ChangeBudget({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-change-budget"><section className="creative-simulation change-meter"><header><Code2 size={18} /><strong>{guide.simulation.label[t]}</strong><span>COST PROFILE</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><div><strong>{track.name[t]}</strong><small>{track.detail[t]}</small></div><span><i style={{ width: `${46 + index * 21}%` }} /></span></article>)}</div></section><div className="change-notes">{guide.stations.map((station, index) => <section key={station.title.en} data-cost={`0${index + 1}`}><StationBody station={station} t={t} /></section>)}</div></div>;
}

function DebugLab({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-debug-lab"><section className="creative-simulation debug-loop"><header><CircleAlert size={18} /><strong>{guide.simulation.label[t]}</strong><span>HYPOTHESIS #1</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><b>{index + 1}</b><div><strong>{track.name[t]}</strong><small>{track.detail[t]}</small></div>{index < guide.simulation.tracks.length - 1 && <ArrowRight size={16} />}</article>)}</div></section><div className="lab-notebook">{guide.stations.map((station, index) => <section key={station.title.en}><span>EXPERIMENT {String(index + 1).padStart(2, "0")}</span><StationBody station={station} t={t} /></section>)}</div></div>;
}
function TestPyramidLab({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-test-pyramid-lab"><section className="creative-simulation test-signal-tower"><header><FlaskConical size={18} /><strong>{guide.simulation.label[t]}</strong><span>SIGNAL / COST</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en} style={{ width: `${94 - index * 20}%` }}><b>{track.name[t]}</b><small>{track.detail[t]}</small></article>)}</div></section><div className="test-level-cards">{guide.stations.map((station, index) => <section key={station.title.en} data-layer={`L${index + 1}`}><StationBody station={station} t={t} /></section>)}</div></div>;
}

function ApiContractWorkshop({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-api-contract-workshop"><section className="creative-simulation request-workbench"><header><Code2 size={18} /><strong>{guide.simulation.label[t]}</strong><span>HTTP/1.1</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><code>{index === 0 ? "→" : index === 1 ? "≡" : "←"}</code><div><strong>{track.name[t]}</strong><small>{track.detail[t]}</small></div></article>)}</div></section><div className="contract-blueprints">{guide.stations.map((station, index) => <section key={station.title.en}><span className="blueprint-coordinate">API/{String(index + 1).padStart(2, "0")}</span><StationBody station={station} t={t} /></section>)}</div></div>;
}

function AccessControlMatrix({ guide, t }: { guide: CreativeGuide; t: DocsLanguage }) {
  return <div className="creative-access-control-matrix"><section className="creative-simulation access-matrix"><header><CircleAlert size={18} /><strong>{guide.simulation.label[t]}</strong><span>DEFAULT: DENY</span></header><div>{guide.simulation.tracks.map((track, index) => <article className={`tone-${track.tone}`} key={track.name.en}><b>{String.fromCharCode(65 + index)}</b><strong>{track.name[t]}</strong><small>{track.detail[t]}</small></article>)}</div></section><div className="policy-cells">{guide.stations.map((station, index) => <section key={station.title.en} data-decision={index === 2 ? "ALLOW?" : index === 3 ? "AUDIT" : "VERIFY"}><StationBody station={station} t={t} /></section>)}</div></div>;
}
export default function CreativeFoundationGuide({ guide, article, t }: { guide: CreativeGuide; article: DocsArticle; t: DocsLanguage }) {
  return <main className={`creative-guide creative-${guide.mode}`}><nav><Link href="/blog/foundations"><ArrowLeft size={16} />{t === "vi" ? "Phòng tài liệu Nền tảng" : "Foundation library"}</Link><span><FlaskConical size={15} />{guide.eyebrow[t]}</span></nav><header className="creative-guide-hero"><div><div className="docs-article-tags">{article.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><h1>{article.title[t]}</h1><p>{guide.thesis[t]}</p></div><aside><small>{t === "vi" ? "NHIỆM VỤ" : "MISSION"}</small><strong>{guide.mission[t]}</strong></aside></header>{guide.mode === "frame-lab" && <FrameLab guide={guide} t={t} />}{guide.mode === "event-scene" && <EventScene guide={guide} t={t} />}{guide.mode === "async-control-room" && <AsyncControlRoom guide={guide} t={t} />}{guide.mode === "incident-desk" && <IncidentDesk guide={guide} t={t} />}{guide.mode === "module-graph" && <ModuleGraph guide={guide} t={t} />}{guide.mode === "package-console" && <PackageConsole guide={guide} t={t} />}{guide.mode === "config-vault" && <ConfigVault guide={guide} t={t} />}{guide.mode === "git-workbench" && <GitWorkbench guide={guide} t={t} />}{guide.mode === "history-ledger" && <HistoryLedger guide={guide} t={t} />}{guide.mode === "review-room" && <ReviewRoom guide={guide} t={t} />}{guide.mode === "change-budget" && <ChangeBudget guide={guide} t={t} />}{guide.mode === "debug-lab" && <DebugLab guide={guide} t={t} />}{guide.mode === "test-pyramid-lab" && <TestPyramidLab guide={guide} t={t} />}{guide.mode === "api-contract-workshop" && <ApiContractWorkshop guide={guide} t={t} />}{guide.mode === "access-control-matrix" && <AccessControlMatrix guide={guide} t={t} />}<DocsSourceFooter sources={guide.sources} t={t} /></main>;
}
