import type { DetailedDoc } from "./docs-data";

const S = {
  eventLoop: "https://html.spec.whatwg.org/multipage/webappapis.html#event-loops",
  jsModel: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Execution_model",
  microtasks: "https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide/In_depth",
  webWorks: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_the_web_works",
  browserLoad: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_browsers_load_websites",
  renderPath: "https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/Critical_rendering_path",
  gitChanges: "https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository",
  gitBranch: "https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows",
  gitRebase: "https://git-scm.com/book/en/v2/Git-Branching-Rebasing",
  http: "https://www.rfc-editor.org/rfc/rfc9110.html",
  httpCache: "https://www.rfc-editor.org/rfc/rfc9111.html",
  httpOverview: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview",
  html: "https://html.spec.whatwg.org/multipage/sections.html",
  waiStructure: "https://www.w3.org/WAI/tutorials/page-structure/",
  waiElements: "https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/",
  cascade: "https://www.w3.org/TR/css-cascade-5/",
  specificity: "https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascade/Specificity",
  values: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascade/Value_processing",
  responsive: "https://web.dev/learn/design/",
  containers: "https://web.dev/learn/css/container-queries/",
  responsiveMdn: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design",
  wcag: "https://www.w3.org/TR/WCAG22/",
  wcagUnderstand: "https://www.w3.org/WAI/WCAG22/Understanding/",
  aria: "https://www.w3.org/WAI/ARIA/apg/",
  forms: "https://www.w3.org/WAI/tutorials/forms/",
  formValidation: "https://www.w3.org/WAI/tutorials/forms/validation/",
  formNotice: "https://www.w3.org/WAI/tutorials/forms/notifications/",
};

export const detailedDocs: Record<string, DetailedDoc> = {
  "event-loop": {
    format: "trace-lab",
    promise: { vi: "Sau bài này, bạn có thể nhìn một đoạn async và tự dự đoán thứ tự chạy thay vì học thuộc mẹo.", en: "After this guide, you can predict an async trace instead of memorising timing tricks." },
    flow: ["script task", "call stack", "microtask checkpoint", "render opportunity", "next task"],
    sections: [
      { kicker: { vi: "BÀI TOÁN", en: "THE PUZZLE" }, heading: { vi: "Đoán output trước khi chạy", en: "Predict the output before running it" }, body: { vi: "Theo dõi từng callback: code đồng bộ chạy hết trên stack; Promise reaction vào microtask queue; timer tạo task mới. Khi task hiện tại kết thúc, trình duyệt vét microtask rồi mới có cơ hội render và lấy task tiếp theo.", en: "Track each callback: synchronous code finishes on the stack; Promise reactions enter the microtask queue; timers create later tasks. After the current task, the browser drains microtasks, may render, then selects another task." }, code: { language: "js", value: "console.log('A');\nsetTimeout(() => console.log('D'), 0);\nPromise.resolve().then(() => console.log('C'));\nconsole.log('B');\n// A → B → C → D" }, items: [{ vi: "Stack: đang chạy gì?", en: "Stack: what is running now?" }, { vi: "Queue: việc gì đã sẵn sàng?", en: "Queue: what work is ready?" }, { vi: "Checkpoint: khi nào microtask được vét hết?", en: "Checkpoint: when are microtasks drained?" }] },
      { kicker: { vi: "MENTAL MODEL", en: "MENTAL MODEL" }, heading: { vi: "Event loop là bộ điều phối, không phải worker", en: "The event loop is a coordinator, not a worker" }, body: { vi: "Timer không chạy code ở nền; nó chỉ làm callback đủ điều kiện xếp hàng. Fetch làm I/O ngoài stack, nhưng phần xử lý response vẫn quay lại JavaScript. Một task đồng bộ 200ms vẫn khóa input, animation và paint.", en: "A timer does not run code in the background; it only makes a callback eligible. Fetch performs I/O away from the stack, but response handling returns to JavaScript. A 200ms synchronous task still blocks input, animation, and paint." }, compare: { left: { vi: "Sai lầm", en: "Wrong model" }, right: { vi: "Mô hình đúng", en: "Useful model" }, leftItems: [{ vi: "setTimeout(0) chạy ngay", en: "setTimeout(0) runs immediately" }, { vi: "async làm CPU work nhanh hơn", en: "async makes CPU work faster" }], rightItems: [{ vi: "0ms là delay tối thiểu", en: "0ms is a minimum delay" }, { vi: "async giải phóng thời gian chờ I/O", en: "async frees the stack during I/O waits" }] } },
      { kicker: { vi: "DEBUG", en: "DEBUG" }, heading: { vi: "Ba lỗi async đáng săn", en: "Three async failures worth hunting" }, body: { vi: "Race condition để kết quả cũ ghi đè state mới; starvation đến từ chuỗi microtask không nhường lượt; long task đến từ CPU work quá lớn. Đo Performance trace, hủy request cũ và chia nhỏ công việc hoặc chuyển sang Worker.", en: "Race conditions let stale results overwrite fresh state; starvation comes from microtasks that never yield; long tasks come from oversized CPU work. Measure a Performance trace, cancel stale requests, and chunk work or move it to a Worker." }, items: [{ vi: "Gắn tên cho từng async operation trong log.", en: "Name each async operation in logs." }, { vi: "Kiểm tra state còn hợp lệ trước khi commit kết quả.", en: "Check state validity before committing a result." }, { vi: "Nếu input lag, đo long task trước khi tối ưu.", en: "If input lags, measure long tasks before optimising." }], note: { vi: "Callback này vào queue nào, và queue nào phải được vét trước khi nó chạy?", en: "Which queue owns this callback, and which queue must drain before it runs?" } },
    ],
    sources: [{ label: "WHATWG HTML — Event loops", href: S.eventLoop }, { label: "MDN — JavaScript execution model", href: S.jsModel }, { label: "MDN — In-depth microtasks", href: S.microtasks }],
  },
  "web-foundations": {
    format: "request-map",
    promise: { vi: "Bạn sẽ đọc một lần tải trang như bản đồ nhiều hệ thống, biết lỗi nằm ở mạng, server hay renderer.", en: "You will read a page load as a multi-system map and locate failures in network, server, or renderer." },
    sections: [
      { kicker: { vi: "BẢN ĐỒ", en: "SYSTEM MAP" }, heading: { vi: "Một URL khởi động cả chuỗi", en: "One URL starts a chain" }, body: { vi: "Browser tách URL, tìm IP qua DNS, thiết lập kết nối, thương lượng TLS rồi gửi HTTP request. HTML đầu tiên lại phát hiện CSS, JavaScript, font và media. Vì vậy 'trang chậm' có thể là DNS, TTFB, tài nguyên chặn render hoặc JavaScript dài.", en: "The browser parses the URL, resolves DNS, establishes a connection, negotiates TLS, then sends HTTP. The first HTML discovers CSS, JavaScript, fonts, and media. A slow page may therefore mean DNS, TTFB, render-blocking resources, or long JavaScript." }, diagram: ["URL + DNS", "connection + TLS", "HTTP response", "resource discovery", "DOM + CSSOM", "layout + paint"] },
      { kicker: { vi: "RENDER", en: "RENDER" }, heading: { vi: "Từ byte đến pixel", en: "From bytes to pixels" }, body: { vi: "HTML được parse thành DOM; CSS thành CSSOM; hai cấu trúc tạo render tree. Browser tính style, layout rồi paint và composite. Thay width có thể kéo theo layout; transform thường chỉ cần composite. Vì vậy Network và Performance phải được đọc cùng nhau.", en: "HTML becomes the DOM; CSS becomes the CSSOM; together they produce a render tree. The browser calculates styles, layout, paint, and compositing. Width may trigger layout; transform often needs only compositing. Network and Performance therefore belong together." }, items: [{ vi: "Network: tài nguyên đến khi nào?", en: "Network: when did resources arrive?" }, { vi: "Main: JavaScript chiếm bao lâu?", en: "Main: how long did JavaScript run?" }, { vi: "Rendering: layout/paint có lặp lại?", en: "Rendering: do layout/paint repeat?" }] },
      { kicker: { vi: "CASE STUDY", en: "CASE STUDY" }, heading: { vi: "200 OK nhưng người dùng vẫn thấy lỗi", en: "200 OK while the user still sees failure" }, body: { vi: "200 chỉ nói request thành công theo HTTP. Body có thể sai schema, JavaScript có thể throw, CSS có thể chưa tải hoặc cache đang cũ. Lần từ waterfall sang response, console rồi DOM thay vì dừng ở status.", en: "A 200 only says the request succeeded under HTTP semantics. The body may violate its schema, JavaScript may throw, CSS may be missing, or cache may be stale. Trace from waterfall to response, console, and DOM." }, compare: { left: { vi: "Triệu chứng", en: "Symptom" }, right: { vi: "Bằng chứng đầu tiên", en: "First evidence" }, leftItems: [{ vi: "Trắng trang", en: "Blank screen" }, { vi: "Nội dung cũ", en: "Stale content" }, { vi: "Layout nhảy", en: "Layout shift" }], rightItems: [{ vi: "Console + bundle", en: "Console + bundle" }, { vi: "Cache-Control + service worker", en: "Cache-Control + service worker" }, { vi: "CSS/font timing", en: "CSS/font timing" }] } },
    ],
    sources: [{ label: "MDN — How the web works", href: S.webWorks }, { label: "MDN — How browsers load websites", href: S.browserLoad }, { label: "MDN — Critical rendering path", href: S.renderPath }],
  },
  "git-workflow": {
    format: "decision-playbook",
    promise: { vi: "Bạn sẽ chọn commit, branch, merge, rebase hay revert theo tình huống thay vì nhớ lệnh rời rạc.", en: "You will choose commit, branch, merge, rebase, or revert by situation rather than memorising commands." },
    sections: [
      { kicker: { vi: "BẢN CHẤT", en: "CORE MODEL" }, heading: { vi: "Git quản lý snapshot và con trỏ", en: "Git manages snapshots and pointers" }, body: { vi: "Working tree là việc đang làm; index là bản nháp commit kế tiếp; commit là snapshot bất biến có parent; branch là con trỏ di chuyển. Hiểu bốn vật này làm restore, merge và rebase bớt ma thuật.", en: "The working tree is current work; the index drafts the next commit; a commit is an immutable snapshot with a parent; a branch is a moving pointer. These objects make restore, merge, and rebase less magical." }, diagram: ["working tree", "index", "commit graph", "local branch", "remote-tracking branch"] },
      { kicker: { vi: "PLAYBOOK", en: "PLAYBOOK" }, heading: { vi: "Chọn thao tác theo mục tiêu", en: "Choose an operation by intent" }, body: { vi: "Xác định bạn muốn bảo toàn lịch sử, viết lại lịch sử cá nhân hay đảo thay đổi đã chia sẻ. Rebase làm sạch branch riêng; merge giữ hình dạng hội tụ; revert tạo commit đảo ngược an toàn trên branch chung.", en: "Decide whether to preserve history, rewrite private history, or undo a shared change. Rebase cleans a private branch; merge preserves convergence; revert safely reverses shared change." }, compare: { left: { vi: "Tình huống", en: "Situation" }, right: { vi: "Lựa chọn", en: "Choice" }, leftItems: [{ vi: "Branch riêng cần cập nhật", en: "Private branch needs updates" }, { vi: "Feature đã review", en: "Reviewed feature" }, { vi: "Commit xấu đã push", en: "Bad commit was pushed" }], rightItems: [{ vi: "rebase nếu team cho phép", en: "rebase if team permits" }, { vi: "merge/squash theo quy ước", en: "merge/squash by convention" }, { vi: "revert, không rewrite", en: "revert, do not rewrite" }] } },
      { kicker: { vi: "THỰC CHIẾN", en: "WORKING LOOP" }, heading: { vi: "Một vòng làm việc có thể review", en: "A reviewable working loop" }, body: { vi: "Stage theo ý định, xem chính xác snapshot sắp commit, chạy test và viết message nói lý do. PR tốt đủ nhỏ để review một lượt và không trộn refactor ngoài scope.", en: "Stage by intent, inspect the exact snapshot, run tests, and state why in the message. A good PR fits one review pass and avoids unrelated refactoring." }, code: { language: "bash", value: "git status --short\ngit diff\ngit add -p\ngit diff --cached\nnpm test\ngit commit -m \"fix(auth): reject expired sessions\"" }, items: [{ vi: "Bỏ sửa chưa stage: git restore <file>", en: "Discard unstaged work: git restore <file>" }, { vi: "Bỏ stage, giữ file: git restore --staged <file>", en: "Unstage, keep work: git restore --staged <file>" }, { vi: "Đảo commit chung: git revert <sha>", en: "Undo shared commit: git revert <sha>" }] },
    ],
    sources: [{ label: "Pro Git — Recording changes", href: S.gitChanges }, { label: "Pro Git — Branching workflows", href: S.gitBranch }, { label: "Pro Git — Rebasing", href: S.gitRebase }],
  },  "http-basics": {
    format: "protocol-workbench",
    promise: { vi: "Bạn sẽ đọc và thiết kế HTTP như một hợp đồng có semantics, cache và lỗi rõ ràng.", en: "You will read and design HTTP as a contract with clear semantics, caching, and failure signals." },
    sections: [
      { kicker: { vi: "GIẢI PHẪU", en: "ANATOMY" }, heading: { vi: "Thông điệp tự mô tả", en: "A self-describing message" }, body: { vi: "Method nói ý định, target nói resource, fields mang metadata và content mang representation. Cùng status 200 nhưng body của GET là trạng thái resource, còn body của POST có thể là kết quả xử lý. API contract phải mô tả method, status, headers và schema.", en: "The method states intent, the target identifies a resource, fields carry metadata, and content carries a representation. A 200 body for GET represents resource state, while POST may represent processing results. An API contract covers method, status, headers, and schema." }, code: { language: "http", value: "PATCH /articles/42 HTTP/1.1\nIf-Match: \"v7\"\nContent-Type: application/json\n\n{\"title\":\"HTTP semantics\"}\n\nHTTP/1.1 200 OK\nETag: \"v8\"" } },
      { kicker: { vi: "SEMANTICS", en: "SEMANTICS" }, heading: { vi: "Safe, idempotent và cacheable là ba câu hỏi khác nhau", en: "Safe, idempotent, and cacheable are different questions" }, body: { vi: "Safe nghĩa là client không yêu cầu đổi state; idempotent nghĩa là gửi lặp có hiệu ứng dự kiến như một lần; cacheable nói response có thể tái sử dụng. GET safe và idempotent; PUT/DELETE idempotent nhưng không safe; POST thường không idempotent.", en: "Safe means no requested state change; idempotent means repeats have the intended effect of one request; cacheable means a response may be reused. GET is safe and idempotent; PUT/DELETE are idempotent but unsafe; POST is usually not idempotent." }, compare: { left: { vi: "Thiết kế yếu", en: "Weak contract" }, right: { vi: "Thiết kế rõ", en: "Clear contract" }, leftItems: [{ vi: "GET /delete?id=42", en: "GET /delete?id=42" }, { vi: "200 cho mọi lỗi", en: "200 for every failure" }, { vi: "retry POST mù quáng", en: "blindly retry POST" }], rightItems: [{ vi: "DELETE /articles/42", en: "DELETE /articles/42" }, { vi: "4xx/5xx đúng ngữ nghĩa", en: "semantic 4xx/5xx" }, { vi: "idempotency key khi cần", en: "idempotency key when needed" }] } },
      { kicker: { vi: "SẢN XUẤT", en: "PRODUCTION" }, heading: { vi: "Cache, concurrency và retry", en: "Caching, concurrency, and retry" }, body: { vi: "Cache-Control quyết định freshness; ETag/If-None-Match cho revalidation; If-Match tránh lost update. Chỉ retry lỗi tạm thời và phải cân nhắc method. 429/503 có thể kèm Retry-After; lỗi 5xx nên có request id để tra log.", en: "Cache-Control defines freshness; ETag/If-None-Match enables revalidation; If-Match prevents lost updates. Retry only transient failures while respecting methods. 429/503 may include Retry-After; 5xx should expose a request ID." }, items: [{ vi: "400: request không hợp lệ", en: "400: invalid request" }, { vi: "401: thiếu xác thực hợp lệ", en: "401: valid authentication missing" }, { vi: "403: đã nhận diện nhưng không được phép", en: "403: identified but forbidden" }, { vi: "409: xung đột trạng thái", en: "409: state conflict" }] },
    ],
    sources: [{ label: "RFC 9110 — HTTP Semantics", href: S.http }, { label: "RFC 9111 — HTTP Caching", href: S.httpCache }, { label: "MDN — HTTP overview", href: S.httpOverview }],
  },
  "html-semantic": {
    format: "markup-audit",
    promise: { vi: "Bạn sẽ chọn element theo ý nghĩa và kiểm tra trang như một cây thông tin, không như tập hợp div.", en: "You will choose elements by meaning and audit a page as an information tree, not a pile of divs." },
    sections: [
      { kicker: { vi: "QUYẾT ĐỊNH", en: "DECISION" }, heading: { vi: "Hỏi nội dung là gì trước khi hỏi nó trông ra sao", en: "Ask what content is before how it looks" }, body: { vi: "Nếu kích hoạt hành động, dùng button; nếu đi đến URL, dùng link. main chứa nội dung chính; nav nhóm liên kết điều hướng; article có thể đứng độc lập; section là nhóm có chủ đề và thường cần heading. CSS chịu trách nhiệm ngoại hình.", en: "Use a button for an action and a link for navigation. Main holds primary content; nav groups navigation links; an article can stand alone; a section groups a theme and usually needs a heading. CSS owns appearance." }, compare: { left: { vi: "Dấu hiệu xấu", en: "Code smell" }, right: { vi: "Primitive phù hợp", en: "Better primitive" }, leftItems: [{ vi: "div onClick", en: "div onClick" }, { vi: "span giả heading", en: "span acting as heading" }, { vi: "section không tên", en: "unnamed section" }], rightItems: [{ vi: "button hoặc a", en: "button or a" }, { vi: "h2/h3 đúng cấp", en: "proper h2/h3" }, { vi: "div hoặc section có heading", en: "div or labelled section" }] } },
      { kicker: { vi: "CÂY THÔNG TIN", en: "INFORMATION TREE" }, heading: { vi: "Landmark và heading tạo mục lục vô hình", en: "Landmarks and headings create an invisible table of contents" }, body: { vi: "Người dùng screen reader có thể nhảy qua heading và landmark. Thứ tự DOM phải kể câu chuyện đúng dù CSS đổi cột. Nhiều nav cần accessible name khác nhau; heading không được chọn chỉ vì cỡ chữ.", en: "Screen-reader users navigate by headings and landmarks. DOM order must tell the right story even when CSS rearranges columns. Multiple nav landmarks need distinct accessible names; heading level must not be chosen for font size." }, code: { language: "html", value: "<header>...</header>\n<nav aria-label=\"Chính\">...</nav>\n<main>\n  <article>\n    <h1>HTML ngữ nghĩa</h1>\n    <section aria-labelledby=\"why\">\n      <h2 id=\"why\">Vì sao quan trọng?</h2>\n    </section>\n  </article>\n</main>" } },
      { kicker: { vi: "AUDIT 5 PHÚT", en: "FIVE-MINUTE AUDIT" }, heading: { vi: "Tắt CSS rồi đọc lại trang", en: "Turn off CSS and read the page" }, body: { vi: "Nếu nội dung vẫn có thứ tự hợp lý, heading đúng và control hoạt động bằng keyboard, nền semantic đang tốt. Sau đó xem Accessibility Tree để thấy name, role, state mà công nghệ hỗ trợ nhận được.", en: "If content remains ordered, headings remain meaningful, and controls work by keyboard, the semantic foundation is strong. Then inspect the Accessibility Tree for exposed name, role, and state." }, items: [{ vi: "Mỗi input có label thật.", en: "Every input has a real label." }, { vi: "Ảnh thông tin có alt; ảnh trang trí alt rỗng.", en: "Informative images have alt; decorative images use empty alt." }, { vi: "Table dữ liệu có caption và header cell.", en: "Data tables have a caption and header cells." }, { vi: "Không thêm ARIA nếu HTML native đã đủ.", en: "Do not add ARIA when native HTML is sufficient." }] },
    ],
    sources: [{ label: "WHATWG HTML — Sections", href: S.html }, { label: "W3C WAI — Page structure", href: S.waiStructure }, { label: "WAI APG — Read me first", href: S.waiElements }],
  },
  "css-cascade": {
    format: "conflict-resolver",
    promise: { vi: "Bạn sẽ giải xung đột CSS theo thuật toán, không tăng selector hay thêm !important theo cảm tính.", en: "You will solve CSS conflicts algorithmically instead of escalating selectors or adding !important by instinct." },
    sections: [
      { kicker: { vi: "THUẬT TOÁN", en: "ALGORITHM" }, heading: { vi: "Specificity không phải vòng đầu tiên", en: "Specificity is not the first round" }, body: { vi: "Browser lọc rule liên quan, so origin và importance, layer, specificity, scoping proximity rồi source order. Selector rất mạnh ở layer thấp vẫn thua selector nhẹ ở layer cao. Sau cascade, inheritance/defaulting mới lấp giá trị thiếu.", en: "The browser filters relevant rules, then compares origin and importance, layer, specificity, scoping proximity, and source order. A strong selector in a lower layer can lose to a light selector above it. Inheritance/defaulting then fill missing values." }, diagram: ["relevance", "origin + importance", "layer order", "specificity", "scope proximity", "source order"] },
      { kicker: { vi: "GIẢI XUNG ĐỘT", en: "RESOLVE" }, heading: { vi: "Rule bị gạch ngang là bằng chứng", en: "A crossed-out rule is evidence" }, body: { vi: "Trong DevTools, chọn property ở Computed rồi mở ngược về declaration thắng. Xác định nó thắng ở vòng nào trước khi sửa. Override cuối file chỉ che nguyên nhân và tăng chi phí lần sửa sau.", en: "In DevTools, select the property in Computed and trace back to the winner. Identify which cascade stage decided it before changing code. A late override hides the cause and raises future cost." }, compare: { left: { vi: "Phản xạ", en: "Reflex" }, right: { vi: "Chẩn đoán", en: "Diagnosis" }, leftItems: [{ vi: "Thêm !important", en: "Add !important" }, { vi: "Lặp class/ID", en: "Repeat classes/IDs" }], rightItems: [{ vi: "Kiểm tra origin/layer", en: "Inspect origin/layer" }, { vi: "Hạ specificity ở nơi sở hữu", en: "Lower specificity at the owner" }] } },
      { kicker: { vi: "KIẾN TRÚC", en: "ARCHITECTURE" }, heading: { vi: "Dùng layer để biến thứ tự thành chủ đích", en: "Use layers to make precedence intentional" }, body: { vi: "Đặt reset, base, components và utilities theo thứ tự công khai. Dùng :where() cho selector nền specificity 0; giữ component class nông; dùng custom property cho token. Override trở thành quyết định hệ thống, không phải cuộc chiến selector.", en: "Order reset, base, components, and utilities explicitly. Use :where() for zero-specificity defaults, keep classes shallow, and use custom properties for tokens. Overrides become system decisions, not selector warfare." }, code: { language: "css", value: "@layer reset, base, components, utilities;\n@layer base { :where(a) { color: var(--link); } }\n@layer components { .button { background: var(--accent); } }\n@layer utilities { .text-muted { color: var(--muted); } }" }, items: [{ vi: "color/font thường kế thừa; margin/border thường không.", en: "color/font often inherit; margin/border usually do not." }, { vi: "Computed value chưa chắc là used value sau layout.", en: "A computed value may differ from the used value after layout." }] },
    ],
    sources: [{ label: "W3C — CSS Cascade Level 5", href: S.cascade }, { label: "MDN — Specificity", href: S.specificity }, { label: "MDN — CSS value processing", href: S.values }],
  },  "responsive-design": {
    format: "constraint-workshop",
    promise: { vi: "Bạn sẽ thiết kế theo áp lực nội dung và container, không theo danh sách thiết bị mau lỗi thời.", en: "You will design around content pressure and containers, not an expiring list of devices." },
    sections: [
      { kicker: { vi: "THÍ NGHIỆM", en: "EXPERIMENT" }, heading: { vi: "Kéo hẹp đến khi nội dung bắt đầu nói dối", en: "Responsive design is constraint design" }, body: { vi: "Breakpoint tốt xuất hiện nơi quan hệ nội dung bị phá: tiêu đề đẩy action khỏi tầm nhìn, dòng quá ngắn hoặc control chạm nhau. Nó không tồn tại chỉ vì một điện thoại rộng 390px. Test tiếng Việt dài, zoom 200%, empty state và dữ liệu cực đoan.", en: "A useful breakpoint appears where content relationships fail: a title pushes actions away, lines become unreadable, or controls collide. It does not exist merely because one phone is 390px wide. Test long copy, 200% zoom, empty states, and extreme data." }, items: [{ vi: "Macro layout: cấu trúc toàn trang.", en: "Macro layout: whole-page structure." }, { vi: "Micro layout: component trong nhiều container.", en: "Micro layout: a component across containers." }, { vi: "Media: kích thước và art direction.", en: "Media: sizing and art direction." }] },
      { kicker: { vi: "CÔNG CỤ", en: "TOOLKIT" }, heading: { vi: "Để CSS tự phân phối trước khi thêm media query", en: "Let CSS distribute before adding media queries" }, body: { vi: "Grid auto-fit/minmax xử lý số cột; clamp tạo thang co giãn có biên; logical properties hỗ trợ writing mode; container query giúp component phản ứng theo nơi nó sống. Media query vẫn cần cho bố cục toàn trang và preference như reduced motion.", en: "Grid auto-fit/minmax handles columns; clamp creates bounded fluid scales; logical properties support writing modes; container queries respond to where a component lives. Media queries remain useful for page layout and preferences such as reduced motion." }, code: { language: "css", value: ".grid { grid-template-columns: repeat(auto-fit, minmax(min(100%, 18rem), 1fr)); }\n.card-shell { container-type: inline-size; }\n@container (width > 34rem) { .card { grid-template-columns: 9rem 1fr; } }\nh1 { font-size: clamp(2rem, 5vw, 4rem); }" } },
      { kicker: { vi: "SHIP CHECK", en: "SHIP CHECK" }, heading: { vi: "Responsive còn là dữ liệu, input và hiệu năng", en: "Responsive also means data, input, and performance" }, body: { vi: "Ảnh cần width/height để giữ chỗ, srcset/sizes để tránh tải thừa và picture khi cần art direction. Touch target phải đủ dùng; hover không thể là đường duy nhất. Kiểm tra overflow ngang ở toàn bộ dải chiều rộng, không chỉ ba preset DevTools.", en: "Images need width/height to reserve space, srcset/sizes to avoid over-downloading, and picture for art direction. Touch targets must remain usable; hover cannot be the only path. Check horizontal overflow across the full width range, not only three presets." }, compare: { left: { vi: "Đẹp trong mockup", en: "Mockup-perfect" }, right: { vi: "Bền trong sản phẩm", en: "Production-resilient" }, leftItems: [{ vi: "Lorem ipsum", en: "Lorem ipsum" }, { vi: "Breakpoint theo device", en: "Device breakpoints" }, { vi: "Ảnh desktop thu nhỏ", en: "Shrunk desktop image" }], rightItems: [{ vi: "Copy thật đa ngôn ngữ", en: "Real multilingual copy" }, { vi: "Breakpoint theo nội dung", en: "Content breakpoints" }, { vi: "Responsive source + crop", en: "Responsive source + crop" }] } },
    ],
    sources: [{ label: "web.dev — Learn Responsive Design", href: S.responsive }, { label: "web.dev — Container queries", href: S.containers }, { label: "MDN — Responsive design", href: S.responsiveMdn }],
  },
  "web-accessibility": {
    format: "inclusive-journey",
    promise: { vi: "Bạn sẽ kiểm tra accessibility qua hành trình hoàn thành tác vụ, không chỉ qua điểm số tự động.", en: "You will evaluate accessibility through task completion, not only an automated score." },
    sections: [
      { kicker: { vi: "GÓC NHÌN", en: "LENS" }, heading: { vi: "POUR là bốn câu hỏi về một tác vụ", en: "POUR is four questions about one task" }, body: { vi: "Người dùng có nhận biết thông tin, thao tác control, hiểu trạng thái và dùng được với công nghệ hỗ trợ không? Áp bốn câu hỏi này vào luồng thật như tìm tài liệu hoặc gửi form. Nút contrast tốt nhưng không có accessible name vẫn làm tác vụ thất bại.", en: "Can a person perceive information, operate controls, understand state, and use assistive technology? Apply these questions to a real flow such as finding a guide or submitting a form. A high-contrast button with no accessible name still fails the task." }, diagram: ["Perceivable", "Operable", "Understandable", "Robust", "task completed"] },
      { kicker: { vi: "HÀNH TRÌNH", en: "JOURNEY" }, heading: { vi: "Keyboard → focus → name, role, state", en: "Keyboard first: focus, name, role, state" }, body: { vi: "Đi luồng chính bằng Tab, Shift+Tab, Enter, Space và Escape. Focus phải nhìn thấy, theo DOM có nghĩa và không bị sticky header che. Sau đó xem Accessibility Tree: control có đúng name, role, state và thay đổi động có được thông báo không.", en: "Walk the primary flow with Tab, Shift+Tab, Enter, Space, and Escape. Focus must be visible, follow meaningful DOM order, and remain unobscured. Then inspect the Accessibility Tree for name, role, state, and dynamic announcements." }, code: { language: "tsx", value: "<button type=\"button\" aria-expanded={open} aria-controls=\"filters\">\n  Bộ lọc\n</button>\n<section id=\"filters\" hidden={!open}>...</section>" }, items: [{ vi: "Không dùng positive tabindex để vá thứ tự.", en: "Do not patch order with positive tabindex." }, { vi: "Không xóa outline nếu chưa có focus style thay thế.", en: "Do not remove outline without a replacement." }, { vi: "Không truyền trạng thái chỉ bằng màu.", en: "Do not communicate state by color alone." }] },
      { kicker: { vi: "CHIẾN LƯỢC TEST", en: "TEST STRATEGY" }, heading: { vi: "Automation tìm luật; con người tìm trải nghiệm", en: "Automation finds rules; people find experience" }, body: { vi: "Lint và axe bắt label thiếu, role sai và một số contrast; keyboard test phát hiện thứ tự/focus; screen reader test phát hiện tên và thông báo khó hiểu; zoom/reflow phát hiện nội dung mất. Không công cụ đơn lẻ nào chứng minh trang accessible.", en: "Linters and axe catch missing labels, invalid roles, and some contrast issues; keyboard tests expose order and focus; screen readers expose confusing names and announcements; zoom/reflow reveals lost content. No single tool proves accessibility." }, compare: { left: { vi: "Kiểm tra máy", en: "Machine checks" }, right: { vi: "Kiểm tra người", en: "Human checks" }, leftItems: [{ vi: "rule, role, contrast", en: "rules, roles, contrast" }, { vi: "chạy lặp trong CI", en: "repeatable in CI" }], rightItems: [{ vi: "luồng có hiểu được không", en: "is the flow understandable" }, { vi: "tác vụ có hoàn thành được không", en: "can the task be completed" }] } },
    ],
    sources: [{ label: "W3C — WCAG 2.2", href: S.wcag }, { label: "WAI — Understanding WCAG 2.2", href: S.wcagUnderstand }, { label: "WAI — ARIA Authoring Practices", href: S.aria }],
  },
  "forms-validation": {
    format: "state-machine",
    promise: { vi: "Bạn sẽ thiết kế form như state machine có phản hồi rõ, validation hai lớp và đường phục hồi lỗi.", en: "You will design forms as state machines with clear feedback, two-layer validation, and recovery paths." },
    sections: [
      { kicker: { vi: "STATE MACHINE", en: "STATE MACHINE" }, heading: { vi: "Form không chỉ có hợp lệ và không hợp lệ", en: "A form is more than valid or invalid" }, body: { vi: "Field đi qua pristine, focused, dirty, locally invalid, validating, server-rejected và accepted. Lỗi quá sớm tạo nhiễu; quá muộn làm mất dữ liệu. Hướng dẫn trước input, validate format sau blur/submit, giữ dữ liệu khi server từ chối và focus error summary hoặc field lỗi đầu tiên.", en: "A field moves through pristine, focused, dirty, locally invalid, validating, server-rejected, and accepted states. Early errors create noise; late errors lose work. Instruct before input, validate after blur/submit, preserve values, and focus the summary or first invalid field." }, diagram: ["pristine", "editing", "touched", "submitting", "server result", "recover or success"] },
      { kicker: { vi: "RANH GIỚI TIN CẬY", en: "TRUST BOUNDARY" }, heading: { vi: "Client hỗ trợ; server quyết định", en: "Validate twice, explain once" }, body: { vi: "required, type và pattern phản hồi nhanh nhưng có thể bị bỏ qua. Server phải parse, normalize và validate lại business rule trước khi ghi. Validation không thay authorization; parameterized query và output encoding vẫn là lớp bảo vệ riêng.", en: "required, type, and pattern give fast feedback but can be bypassed. The server must parse, normalise, and validate business rules before persistence. Validation does not replace authorisation; parameterised queries and output encoding remain separate protections." }, compare: { left: { vi: "Client", en: "Client" }, right: { vi: "Server", en: "Server" }, leftItems: [{ vi: "phản hồi tức thì", en: "instant feedback" }, { vi: "giảm request sai", en: "fewer invalid requests" }, { vi: "không đáng tin cậy", en: "not trusted" }], rightItems: [{ vi: "nguồn quyết định", en: "source of truth" }, { vi: "business rule + auth", en: "business rules + auth" }, { vi: "error schema ổn định", en: "stable error schema" }] } },
      { kicker: { vi: "ERROR UX", en: "ERROR UX" }, heading: { vi: "Lỗi phải chỉ đường sửa", en: "An error must point to recovery" }, body: { vi: "Thông báo cần gọi tên field, lý do và ví dụ đúng; link summary tới control; nối hint/error bằng aria-describedby. role=alert phù hợp cho summary động quan trọng nhưng không nên spam mỗi ký tự. Success cũng phải được xác nhận rõ.", en: "An error should name the field, explain why, and show a valid example; link summaries to controls; connect hints/errors with aria-describedby. role=alert can announce an important dynamic summary but should not fire on every keystroke. Success also needs confirmation." }, code: { language: "html", value: "<div role=\"alert\"><a href=\"#email\">Email chưa đúng định dạng.</a></div>\n<label for=\"email\">Email</label>\n<input id=\"email\" type=\"email\" aria-describedby=\"email-error\">\n<p id=\"email-error\">Ví dụ: ban@domain.vn</p>" }, items: [{ vi: "Chặn double submit và báo đang xử lý.", en: "Prevent double submit and expose pending state." }, { vi: "Cho retry mà không nhập lại dữ liệu.", en: "Allow retry without re-entering data." }, { vi: "Chỉ hỏi dữ liệu thật sự cần.", en: "Ask only for required data." }] },
    ],
    sources: [{ label: "WAI — Forms tutorial", href: S.forms }, { label: "WAI — Validating input", href: S.formValidation }, { label: "WAI — User notifications", href: S.formNotice }],
  },
};