export type DocsLanguage = "vi" | "en";
export type DocsTopicId = "foundations" | "languages" | "algorithms" | "tools";
export type Localized = Record<DocsLanguage, string>;

export type DocsTopic = { id: DocsTopicId; accent: "teal" | "coral" | "gold" | "sky"; label: Localized; description: Localized };
export type DocsLesson = { heading: Localized; body: Localized; kicker?: Localized; items?: Localized[]; diagram?: string[]; compare?: { left: Localized; right: Localized; leftItems: Localized[]; rightItems: Localized[] }; code?: { language: string; value: string }; note?: Localized };
export type DocsSource = { label: string; href: string };
export type DetailedDoc = { format: string; promise: Localized; sections: DocsLesson[]; sources: DocsSource[]; flow?: string[] };
export type DocsArticle = { id: string; topic: DocsTopicId; level: "beginner" | "all" | "intermediate"; title: Localized; description: Localized; tags: string[]; sections?: DocsLesson[]; flow?: string[]; status?: "published" | "planned" };
export { detailedDocs } from "./docs-detailed-content.ts";

export const docsTopics: DocsTopic[] = [
  { id: "foundations", accent: "teal", label: { vi: "Nền tảng", en: "Foundations" }, description: { vi: "Khái niệm web, Git và tư duy viết mã bền vững.", en: "Web concepts, Git, and durable coding habits." } },
  { id: "languages", accent: "coral", label: { vi: "Ngôn ngữ & hệ sinh thái", en: "Languages & ecosystem" }, description: { vi: "Ngôn ngữ, framework và nền tảng đã học để tra cứu, ôn lại và phát triển.", en: "Languages, frameworks, and platforms to learn, revisit, and build with." } },
  { id: "algorithms", accent: "gold", label: { vi: "Thuật toán & tư duy", en: "Algorithms & problem solving" }, description: { vi: "Cấu trúc dữ liệu, thuật toán và kỹ thuật giải để học, luyện tập, ôn lại.", en: "Data structures, algorithms, and problem-solving techniques to learn and revisit." } },
  { id: "tools", accent: "sky", label: { vi: "Công cụ & AI", en: "Developer tools & AI" }, description: { vi: "Workflow, công cụ developer và AI để học, ôn lại và làm việc hiệu quả.", en: "Developer workflows, tools, and AI to learn, revisit, and work effectively." } },
];

const plannedFoundationArticles: DocsArticle[] = [
  ["html-semantic", "HTML ngữ nghĩa", "Semantic HTML", "Viết cấu trúc HTML rõ nghĩa cho người dùng, trình duyệt và công cụ hỗ trợ.", "Use meaningful HTML structure for people, browsers, and assistive technology.", ["HTML", "Accessibility"]],
  ["css-cascade", "Hiểu CSS Cascade", "Understanding the CSS cascade", "Nguồn gốc style, specificity và thứ tự ưu tiên trong CSS.", "Origins, specificity, and priority order in CSS.", ["CSS", "Cascade"]],
  ["responsive-design", "Responsive Design từ gốc", "Responsive design from first principles", "Thiết kế giao diện linh hoạt trên mọi kích thước màn hình.", "Build interfaces that adapt across screen sizes.", ["CSS", "Responsive"]],
  ["web-accessibility", "Web Accessibility cơ bản", "Web accessibility basics", "Những nguyên tắc giúp sản phẩm dễ dùng với nhiều người hơn.", "Principles that make products usable by more people.", ["A11y", "HTML"]],
  ["forms-validation", "Form và kiểm tra dữ liệu", "Forms and input validation", "Thiết kế biểu mẫu rõ ràng, có phản hồi và xử lý dữ liệu đúng cách.", "Design clear forms with feedback and sound data handling.", ["Forms", "UX"]],
  ["browser-rendering", "Trình duyệt render trang web", "How browsers render pages", "Từ HTML, CSS đến layout, paint và compositing.", "From HTML and CSS to layout, paint, and compositing.", ["Browser", "Rendering"]],
  ["dom-events", "DOM Events", "DOM events", "Event bubbling, capturing và cách quản lý tương tác người dùng.", "Event bubbling, capturing, and managing user interactions.", ["JavaScript", "DOM"]],
  ["promises-async", "Promise và Async/Await", "Promises and async/await", "Viết luồng bất đồng bộ dễ đọc và dễ xử lý lỗi.", "Write readable async flows with dependable error handling.", ["JavaScript", "Async"]],
  ["javascript-errors", "Xử lý lỗi JavaScript", "Handling JavaScript errors", "Nhận biết, ghi log và xử lý lỗi mà không che giấu nguyên nhân.", "Recognise, log, and handle errors without hiding the cause.", ["JavaScript", "Debugging"]],
  ["javascript-modules", "JavaScript Modules", "JavaScript modules", "Tổ chức mã bằng import, export và ranh giới module rõ ràng.", "Organise code with imports, exports, and clear module boundaries.", ["JavaScript", "Modules"]],
  ["npm-basics", "NPM và package.json", "NPM and package.json", "Quản lý dependency, script và phiên bản gói an toàn.", "Manage dependencies, scripts, and package versions safely.", ["NPM", "Tooling"]],
  ["environment-variables", "Biến môi trường", "Environment variables", "Tách cấu hình khỏi mã và bảo vệ thông tin nhạy cảm.", "Separate configuration from code and protect sensitive values.", ["Config", "Security"]],
  ["git-basics", "Git cho người mới", "Git for beginners", "Repository, staging, commit và remote theo một luồng dễ hiểu.", "Repositories, staging, commits, and remotes in one clear flow.", ["Git", "Workflow"]],
  ["commit-messages", "Viết commit có ý nghĩa", "Writing meaningful commits", "Ghi lại thay đổi để lịch sử dự án thật sự hữu ích.", "Record changes so project history stays useful.", ["Git", "Collaboration"]],
  ["pull-requests", "Pull Request và Code Review", "Pull requests and code review", "Chuẩn bị thay đổi nhỏ, dễ đọc và phản hồi chất lượng.", "Prepare small, reviewable changes and give useful feedback.", ["Git", "Review"]],
  ["clean-code", "Clean Code thực dụng", "Practical clean code", "Tên gọi, hàm nhỏ và cấu trúc giúp mã dễ thay đổi.", "Naming, small functions, and structure that keep code changeable.", ["Code quality", "Design"]],
  ["debugging-basics", "Debugging có phương pháp", "Methodical debugging", "Tái hiện, cô lập và xác nhận lỗi trước khi sửa.", "Reproduce, isolate, and confirm a bug before fixing it.", ["Debugging", "DevTools"]],
  ["testing-basics", "Kiểm thử phần mềm cơ bản", "Software testing basics", "Khi nào dùng unit, integration và end-to-end test.", "When to use unit, integration, and end-to-end tests.", ["Testing", "Quality"]],
  ["rest-api-basics", "REST API căn bản", "REST API fundamentals", "Resource, method, status code và hợp đồng API rõ ràng.", "Resources, methods, status codes, and clear API contracts.", ["API", "HTTP"]],
  ["authentication-basics", "Xác thực và phân quyền", "Authentication and authorization", "Phân biệt danh tính, quyền truy cập và phiên làm việc.", "Separate identity, permissions, and sessions.", ["Security", "Auth"]],
  ["web-security-basics", "Bảo mật web nền tảng", "Web security foundations", "Những rủi ro phổ biến như XSS, CSRF và cách phòng tránh.", "Common risks such as XSS and CSRF, and how to reduce them.", ["Security", "Web"]],
  ["web-performance", "Hiệu năng web căn bản", "Web performance basics", "Đo, tìm và giảm những điểm làm trang web chậm.", "Measure, find, and reduce the work that slows a site down.", ["Performance", "Web"]],
  ["database-basics", "Cơ sở dữ liệu nhập môn", "Database fundamentals", "Bảng, quan hệ, chỉ mục và tư duy dữ liệu bền vững.", "Tables, relationships, indexes, and durable data thinking.", ["Database", "SQL"]],
  ["docker-introduction", "Docker nhập môn", "Introduction to Docker", "Container, image và môi trường phát triển nhất quán.", "Containers, images, and consistent development environments.", ["Docker", "DevOps"]],
  ["deployment-basics", "Đưa ứng dụng lên production", "Deploying an application", "Các bước cơ bản từ build, biến môi trường đến theo dõi sau triển khai.", "Core steps from builds and environment variables to post-deploy monitoring.", ["Deploy", "DevOps"]],
  ["ci-cd-basics", "CI/CD cho dự án nhỏ", "CI/CD for small projects", "Tự động kiểm tra và phát hành thay đổi một cách an toàn.", "Automate checks and release changes with confidence.", ["CI/CD", "Workflow"]],
].map(([id, vi, en, descriptionVi, descriptionEn, tags]) => ({ id, topic: "foundations", level: "beginner", title: { vi, en }, description: { vi: descriptionVi, en: descriptionEn }, tags, status: "planned" })) as DocsArticle[];
const plannedLanguageArticles: DocsArticle[] = [
  ["javascript-core", "JavaScript từ nền tảng", "JavaScript foundations", "Biến, hàm, object, scope và tư duy nền tảng của JavaScript.", "Variables, functions, objects, scope, and core JavaScript thinking.", ["JavaScript", "Core"]],
  ["python", "Python thực dụng", "Python", "Cú pháp, collection và các thói quen viết Python rõ ràng.", "Syntax, collections, and habits for clear Python code.", ["Python", "Backend"]],
  ["java", "Java căn bản", "Java", "OOP, collection và cấu trúc dự án Java hiện đại.", "OOP, collections, and modern Java project structure.", ["Java", "OOP"]],
  ["csharp", "C# và .NET", "C# and .NET", "Ngôn ngữ C# cùng nền tảng xây dựng ứng dụng .NET.", "C# and the foundations of building .NET applications.", ["C#", ".NET"]],
  ["go", "Go cho backend", "Go", "Goroutine, channel và cách tổ chức dịch vụ Go gọn gàng.", "Goroutines, channels, and organised Go services.", ["Go", "Backend"]],
  ["rust", "Rust nhập môn", "Rust", "Ownership, borrowing và xây dựng chương trình an toàn.", "Ownership, borrowing, and building safe programs.", ["Rust", "Systems"]],
  ["c-language", "Lập trình C", "C language", "Con trỏ, bộ nhớ và các khái niệm nền tảng của C.", "Pointers, memory, and the core concepts of C.", ["C", "Systems"]],
  ["cpp", "C++ hiện đại", "C++", "RAII, STL và các tính năng C++ thường dùng.", "RAII, STL, and practical modern C++ features.", ["C++", "Systems"]],
  ["kotlin", "Kotlin cho Android", "Kotlin", "Cú pháp Kotlin và nền tảng phát triển Android.", "Kotlin syntax and foundations for Android development.", ["Kotlin", "Android"]],
  ["swift", "Swift cho iOS", "Swift", "Kiểu dữ liệu, protocol và tư duy phát triển ứng dụng iOS.", "Types, protocols, and iOS application development thinking.", ["Swift", "iOS"]],
  ["php", "PHP hiện đại", "PHP", "Cú pháp PHP và những thực hành backend hiện đại.", "PHP syntax and modern backend practices.", ["PHP", "Backend"]],
  ["ruby", "Ruby căn bản", "Ruby", "Ngôn ngữ Ruby, object và cách viết mã dễ đọc.", "Ruby, objects, and readable code conventions.", ["Ruby", "Backend"]],
  ["dart", "Dart cho ứng dụng đa nền tảng", "Dart", "Ngôn ngữ Dart trước khi bước vào Flutter.", "Dart before stepping into Flutter.", ["Dart", "Mobile"]],
  ["sql", "SQL thực hành", "SQL", "Truy vấn, join, aggregate và cách đọc dữ liệu hiệu quả.", "Queries, joins, aggregates, and reading data efficiently.", ["SQL", "Database"]],
  ["bash", "Bash và dòng lệnh", "Bash and the command line", "Lệnh shell hữu ích để tự động hóa công việc hằng ngày.", "Useful shell commands for everyday automation.", ["Bash", "CLI"]],
  ["react", "React từ nền tảng", "React", "Component, props, state và hooks trong React.", "Components, props, state, and hooks in React.", ["React", "Frontend"]],
  ["nextjs", "Next.js App Router", "Next.js", "Routing, rendering và data flow trong ứng dụng Next.js.", "Routing, rendering, and data flow in Next.js applications.", ["Next.js", "React"]],
  ["vue", "Vue 3 Composition API", "Vue", "Reactivity, component và Composition API của Vue.", "Reactivity, components, and Vue Composition API.", ["Vue", "Frontend"]],
  ["nuxt", "Nuxt cho Vue", "Nuxt", "Routing, server rendering và module trong Nuxt.", "Routing, server rendering, and modules in Nuxt.", ["Nuxt", "Vue"]],
  ["angular", "Angular hiện đại", "Angular", "Component, service, DI và reactive form trong Angular.", "Components, services, DI, and reactive forms in Angular.", ["Angular", "Frontend"]],
  ["svelte", "Svelte và SvelteKit", "Svelte and SvelteKit", "Reactive UI nhẹ nhàng cùng framework SvelteKit.", "Lightweight reactive UI with SvelteKit.", ["Svelte", "Frontend"]],
  ["astro", "Astro cho content website", "Astro", "Islands architecture và xây site tối ưu nội dung.", "Islands architecture and content-focused sites.", ["Astro", "Web"]],
  ["nodejs", "Node.js runtime", "Node.js", "Event-driven runtime, module và xây API bằng Node.js.", "The event-driven runtime, modules, and APIs with Node.js.", ["Node.js", "Backend"]],
  ["express", "Express.js API", "Express.js", "Routing, middleware và cấu trúc API bằng Express.", "Routing, middleware, and API structure with Express.", ["Express", "Node.js"]],
  ["nestjs", "NestJS backend", "NestJS", "Module, controller, provider và DI trong NestJS.", "Modules, controllers, providers, and DI in NestJS.", ["NestJS", "Backend"]],
  ["django", "Django cho web app", "Django", "Model, view, template và admin của Django.", "Django models, views, templates, and admin.", ["Django", "Python"]],
  ["fastapi", "FastAPI cho Python", "FastAPI", "Xây API Python có type hint và tài liệu tự động.", "Typed Python APIs with automatic documentation.", ["FastAPI", "Python"]],
  ["laravel", "Laravel cho PHP", "Laravel", "Routing, Eloquent và cấu trúc ứng dụng Laravel.", "Routing, Eloquent, and Laravel application structure.", ["Laravel", "PHP"]],
  ["spring-boot", "Spring Boot cho Java", "Spring Boot", "Xây dịch vụ Java với Spring Boot và dependency injection.", "Java services with Spring Boot and dependency injection.", ["Spring Boot", "Java"]],
  ["aspnet", "ASP.NET Core", "ASP.NET Core", "Web API, middleware và ứng dụng server bằng .NET.", "Web APIs, middleware, and server apps with .NET.", [".NET", "Backend"]],
  ["flutter", "Flutter cho mobile", "Flutter", "Widget, state và giao diện đa nền tảng với Flutter.", "Widgets, state, and cross-platform UI with Flutter.", ["Flutter", "Mobile"]],
  ["react-native", "React Native", "React Native", "Xây ứng dụng mobile bằng kỹ năng React quen thuộc.", "Build mobile apps with familiar React skills.", ["React Native", "Mobile"]],
  ["unity", "Unity với C#", "Unity", "GameObject, component và luồng làm game trong Unity.", "GameObjects, components, and Unity game workflow.", ["Unity", "Game"]],
  ["godot", "Godot Engine", "Godot", "Node, scene và GDScript trong Godot Engine.", "Nodes, scenes, and GDScript in Godot Engine.", ["Godot", "Game"]],
].map(([id, vi, en, descriptionVi, descriptionEn, tags]) => ({ id, topic: "languages", level: "beginner", title: { vi, en }, description: { vi: descriptionVi, en: descriptionEn }, tags, status: "planned" })) as DocsArticle[];
const plannedAlgorithmArticles: DocsArticle[] = [
  ["arrays", "Mảng và thao tác cơ bản", "Arrays", "Truy cập, duyệt, chèn, xóa và các đánh đổi với mảng.", "Access, traversal, insertion, deletion, and array trade-offs.", ["Array", "Data structure"]],
  ["linked-lists", "Linked List", "Linked lists", "Node, pointer và khi nào linked list phù hợp hơn mảng.", "Nodes, pointers, and when linked lists beat arrays.", ["Linked list", "Pointer"]],
  ["stacks", "Stack", "Stacks", "LIFO, call stack và các bài toán dùng stack.", "LIFO, call stacks, and stack-based problems.", ["Stack", "LIFO"]],
  ["queues", "Queue và Deque", "Queues and deques", "FIFO, queue hai đầu và luồng xử lý tuần tự.", "FIFO, double-ended queues, and sequential processing.", ["Queue", "FIFO"]],
  ["hash-tables", "Hash Table và Map", "Hash tables and maps", "Hashing, collision và tra cứu gần như hằng số.", "Hashing, collisions, and near-constant lookup.", ["Hash table", "Map"]],
  ["trees", "Tree cơ bản", "Trees", "Node, traversal và cách biểu diễn cấu trúc phân cấp.", "Nodes, traversal, and representing hierarchies.", ["Tree", "Traversal"]],
  ["binary-search-tree", "Binary Search Tree", "Binary search trees", "Quy tắc BST, insert, search và delete.", "BST rules, insertion, search, and deletion.", ["Tree", "BST"]],
  ["heap", "Heap và Priority Queue", "Heaps and priority queues", "Min heap, max heap và cách ưu tiên phần tử.", "Min heaps, max heaps, and prioritising elements.", ["Heap", "Priority queue"]],
  ["trie", "Trie và Prefix Tree", "Tries and prefix trees", "Lưu trữ tiền tố cho search, autocomplete và từ điển.", "Prefix storage for search, autocomplete, and dictionaries.", ["Trie", "String"]],
  ["graphs", "Graph nhập môn", "Graphs", "Đỉnh, cạnh, adjacency list và cách mô hình hóa quan hệ.", "Vertices, edges, adjacency lists, and modelling relationships.", ["Graph", "Data structure"]],
  ["union-find", "Union Find", "Union find", "Disjoint set, path compression và union by rank.", "Disjoint sets, path compression, and union by rank.", ["Graph", "DSU"]],
  ["sorting", "Các thuật toán sắp xếp", "Sorting algorithms", "Bubble, selection, merge, quick sort và cách chọn thuật toán.", "Bubble, selection, merge, quick sort, and choosing one.", ["Sorting", "Algorithm"]],
  ["binary-search", "Binary Search", "Binary search", "Tìm kiếm trên không gian có thứ tự và tư duy điều kiện biên.", "Search sorted spaces and reason about boundaries.", ["Search", "Divide and conquer"]],
  ["two-pointers", "Two Pointers", "Two pointers", "Kỹ thuật hai con trỏ cho mảng và string.", "The two-pointer technique for arrays and strings.", ["Array", "Technique"]],
  ["sliding-window", "Sliding Window", "Sliding window", "Cửa sổ trượt cho chuỗi con và dãy con liên tiếp.", "Sliding windows for substrings and contiguous subarrays.", ["Array", "String"]],
  ["prefix-sums", "Prefix Sum", "Prefix sums", "Tính tổng đoạn nhanh và biến đổi bài toán truy vấn.", "Fast range sums and transforming query problems.", ["Array", "Query"]],
  ["difference-arrays", "Difference Array", "Difference arrays", "Cập nhật đoạn hiệu quả trước khi khôi phục kết quả.", "Efficient range updates before recovering results.", ["Array", "Query"]],
  ["recursion", "Recursion", "Recursion", "Base case, recursive case và cách tránh đệ quy mơ hồ.", "Base cases, recursive cases, and avoiding vague recursion.", ["Recursion", "Thinking"]],
  ["backtracking", "Backtracking", "Backtracking", "Sinh tổ hợp, hoán vị và quay lui có kiểm soát.", "Generate combinations, permutations, and controlled backtracking.", ["Recursion", "Search"]],
  ["bfs", "Breadth-First Search", "Breadth-first search", "Duyệt graph theo lớp và tìm đường đi ngắn không trọng số.", "Layered graph traversal and unweighted shortest paths.", ["Graph", "BFS"]],
  ["dfs", "Depth-First Search", "Depth-first search", "Duyệt sâu, phát hiện thành phần và ứng dụng đệ quy.", "Deep traversal, components, and recursive applications.", ["Graph", "DFS"]],
  ["dynamic-programming", "Dynamic Programming", "Dynamic programming", "State, transition, memoization và tabulation.", "State, transitions, memoization, and tabulation.", ["DP", "Optimization"]],
  ["greedy", "Greedy", "Greedy algorithms", "Chọn tối ưu cục bộ và cách chứng minh lựa chọn tham lam.", "Local optimal choices and proving greedy decisions.", ["Greedy", "Optimization"]],
  ["divide-conquer", "Divide and Conquer", "Divide and conquer", "Chia nhỏ bài toán, giải đệ quy và kết hợp kết quả.", "Split problems, solve recursively, and combine results.", ["Recursion", "Algorithm"]],
  ["bit-manipulation", "Bit Manipulation", "Bit manipulation", "Bitwise operator, mask và tối ưu biểu diễn trạng thái.", "Bitwise operators, masks, and compact state representation.", ["Bit", "Optimization"]],
  ["strings", "Thuật toán chuỗi", "String algorithms", "Pattern, palindrome và kỹ thuật xử lý text hiệu quả.", "Patterns, palindromes, and efficient text processing.", ["String", "Algorithm"]],
  ["intervals", "Intervals", "Intervals", "Merge, overlap và sắp xếp khoảng thời gian.", "Merging, overlaps, and sorting intervals.", ["Intervals", "Sorting"]],
  ["monotonic-stack", "Monotonic Stack", "Monotonic stacks", "Next greater element và các bài toán phần tử gần nhất.", "Next-greater elements and nearest-element problems.", ["Stack", "Technique"]],
  ["monotonic-queue", "Monotonic Queue", "Monotonic queues", "Tối ưu min/max trong cửa sổ trượt.", "Optimise min/max values in sliding windows.", ["Queue", "Technique"]],
  ["shortest-paths", "Đường đi ngắn nhất", "Shortest paths", "Dijkstra, Bellman-Ford và lựa chọn theo trọng số.", "Dijkstra, Bellman-Ford, and weighted-path choices.", ["Graph", "Path"]],
  ["topological-sort", "Topological Sort", "Topological sort", "Sắp xếp phụ thuộc trong DAG và luồng công việc.", "Order dependencies in DAGs and workflows.", ["Graph", "DAG"]],
  ["minimum-spanning-tree", "Minimum Spanning Tree", "Minimum spanning trees", "Kruskal, Prim và cách nối graph với chi phí thấp.", "Kruskal, Prim, and connecting graphs at low cost.", ["Graph", "MST"]],
  ["segment-tree", "Segment Tree", "Segment trees", "Truy vấn và cập nhật đoạn hiệu quả trên dữ liệu lớn.", "Efficient range queries and updates on large data.", ["Tree", "Query"]],
  ["fenwick-tree", "Fenwick Tree", "Fenwick trees", "Prefix sum động với Binary Indexed Tree.", "Dynamic prefix sums with Binary Indexed Trees.", ["Tree", "Query"]],
].map(([id, vi, en, descriptionVi, descriptionEn, tags]) => ({ id, topic: "algorithms", level: "beginner", title: { vi, en }, description: { vi: descriptionVi, en: descriptionEn }, tags, status: "planned" })) as DocsArticle[];
const plannedToolArticles: DocsArticle[] = [
  ["git-basics-tool", "Git nền tảng", "Git fundamentals", "Repository, staging, commit và remote cho workflow rõ ràng.", "Repositories, staging, commits, and remotes for a clear workflow.", ["Git", "Workflow"]],
  ["github-workflow", "GitHub workflow", "GitHub workflow", "Issue, branch, pull request và collaboration trên GitHub.", "Issues, branches, pull requests, and collaboration on GitHub.", ["GitHub", "Collaboration"]],
  ["git-branching", "Git branching strategy", "Git branching strategy", "Feature branch, trunk-based và cách chọn chiến lược nhánh.", "Feature branches, trunk-based development, and branching choices.", ["Git", "Branching"]],
  ["vscode", "VS Code cho developer", "VS Code", "Extension, workspace, debug và phím tắt tăng tốc công việc.", "Extensions, workspaces, debugging, and shortcuts for faster work.", ["VS Code", "IDE"]],
  ["terminal", "Terminal và CLI", "Terminal and CLI", "Điều hướng file, pipe, process và script shell hữu ích.", "File navigation, pipes, processes, and useful shell scripts.", ["CLI", "Terminal"]],
  ["chrome-devtools", "Chrome DevTools", "Chrome DevTools", "Inspect, network, performance và debug frontend bằng DevTools.", "Inspect, network, performance, and frontend debugging with DevTools.", ["DevTools", "Debugging"]],
  ["postman", "Postman và API testing", "Postman and API testing", "Collection, environment và kiểm tra API có hệ thống.", "Collections, environments, and systematic API checks.", ["Postman", "API"]],
  ["insomnia", "Insomnia cho API", "Insomnia for APIs", "Một workflow nhẹ để khám phá và test REST/GraphQL API.", "A lightweight workflow for exploring and testing REST/GraphQL APIs.", ["Insomnia", "API"]],
  ["docker-tool", "Docker thực hành", "Docker", "Image, container, volume và môi trường phát triển nhất quán.", "Images, containers, volumes, and consistent development environments.", ["Docker", "DevOps"]],
  ["docker-compose", "Docker Compose", "Docker Compose", "Ghép nhiều service local bằng một file cấu hình.", "Compose multiple local services with one configuration file.", ["Docker", "Compose"]],
  ["kubernetes", "Kubernetes nhập môn", "Kubernetes", "Pod, deployment, service và cách tư duy vận hành container.", "Pods, deployments, services, and container operations thinking.", ["Kubernetes", "DevOps"]],
  ["ci-cd", "CI/CD workflow", "CI/CD workflow", "Tự động test, build và release thay đổi an toàn.", "Automate testing, builds, and safe releases.", ["CI/CD", "DevOps"]],
  ["github-actions", "GitHub Actions", "GitHub Actions", "Workflow YAML, jobs, cache và automation trên GitHub.", "Workflow YAML, jobs, caching, and GitHub automation.", ["GitHub Actions", "CI/CD"]],
  ["jest", "Jest cho unit test", "Jest", "Test case, mock có kiểm soát và coverage thực dụng.", "Test cases, controlled mocks, and practical coverage.", ["Jest", "Testing"]],
  ["playwright", "Playwright E2E", "Playwright", "Kiểm thử hành trình người dùng trên trình duyệt.", "Test user journeys in real browsers.", ["Playwright", "E2E"]],
  ["eslint", "ESLint", "ESLint", "Quy tắc chất lượng mã và workflow sửa lỗi tự động.", "Code-quality rules and automatic fixing workflows.", ["ESLint", "Quality"]],
  ["prettier", "Prettier", "Prettier", "Định dạng mã nhất quán trong team và CI.", "Consistent code formatting in teams and CI.", ["Prettier", "Quality"]],
  ["vite", "Vite", "Vite", "Dev server, build tool và cấu hình frontend hiện đại.", "Dev server, build tooling, and modern frontend configuration.", ["Vite", "Frontend"]],
  ["webpack", "Webpack", "Webpack", "Bundler, loader, plugin và cách đọc cấu hình webpack.", "Bundlers, loaders, plugins, and reading webpack configuration.", ["Webpack", "Build"]],
  ["package-managers", "NPM, pnpm và Bun", "NPM, pnpm, and Bun", "Quản lý package, lockfile và script trong dự án JavaScript.", "Packages, lockfiles, and scripts in JavaScript projects.", ["NPM", "Tooling"]],
  ["openapi", "OpenAPI và API docs", "OpenAPI and API docs", "Đặc tả API, contract và tài liệu có thể kiểm chứng.", "API specifications, contracts, and verifiable documentation.", ["OpenAPI", "API"]],
  ["database-tools", "Database tools", "Database tools", "Dùng GUI và CLI để khám phá, query và quản lý dữ liệu.", "Use GUI and CLI tools to explore, query, and manage data.", ["Database", "Tooling"]],
  ["linux-workflow", "Linux workflow", "Linux workflow", "Permission, process, network và tác vụ server thường gặp.", "Permissions, processes, networking, and common server tasks.", ["Linux", "Server"]],
  ["cloud-deploy", "Cloud deploy", "Cloud deployment", "Deploy web app lên cloud và quản lý biến môi trường.", "Deploy web apps to the cloud and manage environment variables.", ["Cloud", "Deploy"]],
  ["monitoring", "Monitoring và logging", "Monitoring and logging", "Log, metric, alert và cách điều tra sự cố production.", "Logs, metrics, alerts, and production incident investigation.", ["Observability", "DevOps"]],
  ["security-tooling", "Security tooling", "Security tooling", "Dependency audit, secret scanning và kiểm tra bề mặt tấn công.", "Dependency audits, secret scanning, and attack-surface checks.", ["Security", "Tooling"]],
  ["ai-coding-basics", "AI coding có kiểm chứng", "AI coding with verification", "Dùng AI nhanh hơn nhưng vẫn giữ tư duy và kiểm chứng kỹ thuật.", "Use AI faster while retaining technical thinking and verification.", ["AI", "Workflow"]],
  ["prompt-engineering", "Prompt cho developer", "Prompting for developers", "Đặt context, ràng buộc và tiêu chí kiểm tra cho AI.", "Set context, constraints, and checks for AI.", ["AI", "Prompting"]],
  ["chatgpt-workflow", "ChatGPT trong workflow", "ChatGPT workflow", "Dùng ChatGPT để giải thích, phản biện và tăng tốc nghiên cứu.", "Use ChatGPT to explain, challenge, and accelerate research.", ["ChatGPT", "AI"]],
  ["claude-code", "Claude Code workflow", "Claude Code", "Giao việc, review diff và duy trì ngữ cảnh trong codebase.", "Delegate tasks, review diffs, and maintain codebase context.", ["Claude", "AI"]],
  ["github-copilot", "GitHub Copilot", "GitHub Copilot", "Gợi ý code, chat trong IDE và cách kiểm chứng đầu ra.", "Code suggestions, IDE chat, and output verification.", ["Copilot", "AI"]],
  ["cursor", "Cursor workflow", "Cursor", "Tổ chức context, rule và chỉnh sửa nhiều file bằng AI.", "Organise context, rules, and multi-file AI edits.", ["Cursor", "AI"]],
  ["mcp", "Model Context Protocol", "MCP", "Kết nối AI với công cụ, dữ liệu và workflow một cách có kiểm soát.", "Connect AI to tools, data, and workflows with control.", ["MCP", "AI"]],
  ["ai-agents", "AI agents", "AI agents", "Phân rã nhiệm vụ, tool use và giám sát agent trong công việc.", "Task decomposition, tool use, and supervising agents at work.", ["Agent", "AI"]],
].map(([id, vi, en, descriptionVi, descriptionEn, tags]) => ({ id, topic: "tools", level: "beginner", title: { vi, en }, description: { vi: descriptionVi, en: descriptionEn }, tags, status: "planned" })) as DocsArticle[];
export const docsArticles: DocsArticle[] = [
  { id: "event-loop", topic: "foundations", level: "beginner", title: { vi: "JavaScript Event Loop", en: "JavaScript Event Loop" }, description: { vi: "Hiểu call stack, Web APIs, hàng đợi tác vụ và cách JavaScript xử lý bất đồng bộ.", en: "Understand the call stack, Web APIs, task queues, and how JavaScript handles async work." }, tags: ["JavaScript", "Async"], flow: ["Call Stack", "Web APIs", "Task Queue", "Event Loop", "Call Stack"], sections: [{ heading: { vi: "Event Loop là gì?", en: "What is the Event Loop?" }, body: { vi: "JavaScript chạy trên một luồng chính. Event Loop điều phối công việc bất đồng bộ để callback chỉ được đưa về Call Stack khi ngăn xếp đang trống.", en: "JavaScript runs on a main thread. The Event Loop coordinates async work so callbacks return to the Call Stack only when it is empty." } }, { heading: { vi: "Microtask và Macrotask", en: "Microtasks and macrotasks" }, body: { vi: "Promise callbacks được ưu tiên trong microtask queue trước các tác vụ như setTimeout. Hiểu thứ tự này giúp dự đoán kết quả bất đồng bộ chính xác hơn.", en: "Promise callbacks are prioritised in the microtask queue before tasks such as setTimeout. Knowing this order makes async behaviour predictable." } }] },
  { id: "web-foundations", topic: "foundations", level: "beginner", title: { vi: "Web hoạt động như thế nào?", en: "How does the web work?" }, description: { vi: "Từ trình duyệt, HTTP đến cách một trang web hiển thị nội dung.", en: "From browsers and HTTP to how a page renders content." }, tags: ["HTTP", "Browser", "HTML"] },
  { id: "git-workflow", topic: "foundations", level: "all", title: { vi: "Git workflow không gây rối", en: "A Git workflow that stays clear" }, description: { vi: "Commit nhỏ, nhánh tính năng và cách đọc lịch sử dự án.", en: "Small commits, feature branches, and reading project history." }, tags: ["Git", "Workflow"] },
  { id: "http-basics", topic: "foundations", level: "beginner", title: { vi: "HTTP thực hành", en: "Practical HTTP" }, description: { vi: "Methods, status codes, headers và quy ước API dễ dùng.", en: "Methods, status codes, headers, and useful API conventions." }, tags: ["HTTP", "API"] },
  ...plannedFoundationArticles.map((article) => (["browser-rendering", "dom-events", "promises-async", "javascript-errors", "javascript-modules", "npm-basics", "environment-variables", "git-basics", "commit-messages", "pull-requests", "clean-code", "debugging-basics", "testing-basics", "rest-api-basics", "authentication-basics"].includes(article.id) ? { ...article, status: "published" as const } : article)),
  ...plannedLanguageArticles,
  { id: "typescript-mental-model", topic: "languages", level: "intermediate", title: { vi: "Tư duy TypeScript thực dụng", en: "A practical TypeScript mental model" }, description: { vi: "Kiểu dữ liệu giúp làm rõ ý định và giảm lỗi khi thay đổi mã.", en: "Types clarify intent and reduce mistakes as code changes." }, tags: ["TypeScript", "Types"] },
  { id: "react-state", topic: "languages", level: "beginner", title: { vi: "State trong React", en: "State in React" }, description: { vi: "Phân biệt state, props và trường hợp không cần state.", en: "Separate state from props and recognise when state is unnecessary." }, tags: ["React", "State"] },
  { id: "css-layout", topic: "languages", level: "beginner", title: { vi: "CSS Layout hiện đại", en: "Modern CSS layout" }, description: { vi: "Lựa chọn Flexbox và Grid cho bố cục responsive.", en: "Choose Flexbox and Grid for responsive layouts." }, tags: ["CSS", "Layout"] },
  ...plannedAlgorithmArticles,
  { id: "complexity", topic: "algorithms", level: "all", title: { vi: "Độ phức tạp và Big O", en: "Complexity and Big O" }, description: { vi: "Đọc chi phí thời gian và bộ nhớ để chọn giải pháp hợp lý.", en: "Read time and memory cost to choose a sensible solution." }, tags: ["Big O", "Performance"] },
  { id: "data-structures", topic: "algorithms", level: "intermediate", title: { vi: "Chọn cấu trúc dữ liệu", en: "Choosing data structures" }, description: { vi: "Mảng, Map, Set và các đánh đổi trong ứng dụng thực tế.", en: "Arrays, Maps, Sets, and real-world trade-offs." }, tags: ["Map", "Set"] },
  { id: "problem-solving", topic: "algorithms", level: "all", title: { vi: "Phân rã bài toán", en: "Breaking down problems" }, description: { vi: "Một quy trình nhỏ để biến yêu cầu mơ hồ thành bước triển khai rõ ràng.", en: "A small process for turning ambiguous requirements into clear implementation steps." }, tags: ["Thinking", "Design"] },
  ...plannedToolArticles,
  { id: "debugging", topic: "tools", level: "all", title: { vi: "Debug có hệ thống", en: "Debugging systematically" }, description: { vi: "Tái hiện lỗi, cô lập nguyên nhân và xác minh trước khi sửa.", en: "Reproduce, isolate, and verify a problem before changing code." }, tags: ["Debugging", "DevTools"] },
  { id: "ai-pairing", topic: "tools", level: "all", title: { vi: "Dùng AI như lập trình viên đồng hành", en: "Using AI as a programming partner" }, description: { vi: "Đặt câu hỏi tốt, kiểm chứng kết quả và giữ quyền quyết định kỹ thuật.", en: "Ask better questions, verify output, and retain technical judgment." }, tags: ["AI", "Workflow"] },
  { id: "testing", topic: "tools", level: "intermediate", title: { vi: "Chiến lược kiểm thử", en: "Testing strategies" }, description: { vi: "Unit, integration và E2E test nên phối hợp với nhau ra sao.", en: "How unit, integration, and E2E tests work together." }, tags: ["Testing", "Quality"] },
];

export const levelLabel: Record<DocsArticle["level"], Localized> = { beginner: { vi: "Mới bắt đầu", en: "Beginner" }, all: { vi: "Mọi cấp độ", en: "All levels" }, intermediate: { vi: "Đã có nền tảng", en: "Intermediate" } };
export const getTopic = (id: string) => docsTopics.find((topic) => topic.id === id);
export const getArticle = (topic: string, id: string) => docsArticles.find((article) => article.topic === topic && article.id === id);
