import type { CreativeGuide } from "./docs-creative-content";

export const workflowCreativeGuides: Record<string, CreativeGuide> = {
  "environment-variables": {
    mode: "config-vault",
    eyebrow: { vi: "CONFIG VAULT · RUNTIME BOUNDARY", en: "CONFIG VAULT · RUNTIME BOUNDARY" },
    thesis: { vi: "Biến môi trường là đầu vào của tiến trình, không phải két sắt. Chúng giúp tách cấu hình khỏi mã nhưng vẫn cần validation, phân quyền và kiểm soát nơi giá trị bị đóng gói.", en: "Environment variables are process inputs, not a vault. They separate configuration from code, but still require validation, access control, and awareness of where values are bundled." },
    mission: { vi: "Theo một giá trị cấu hình từ nơi cấp phát đến process, phân biệt build-time và runtime, rồi chặn secret trước khi nó đi vào client hoặc log.", en: "Trace configuration from its source into the process, separate build time from runtime, and stop secrets before they reach clients or logs." },
    simulation: { label: { vi: "Hành trình của cấu hình", en: "Configuration journey" }, tracks: [
      { name: { vi: "Nguồn", en: "Source" }, detail: { vi: "shell · .env · secret manager", en: "shell · .env · secret manager" }, tone: "cool" },
      { name: { vi: "Tiến trình", en: "Process" }, detail: { vi: "process.env · chuỗi", en: "process.env · strings" }, tone: "warm" },
      { name: { vi: "Boundary", en: "Boundary" }, detail: { vi: "server-only hoặc public bundle", en: "server-only or public bundle" }, tone: "hot" },
    ] },
    stations: [
      { marker: { vi: "KHOANG 01 · MENTAL MODEL", en: "CHAMBER 01 · MENTAL MODEL" }, title: { vi: "Cấu hình thay đổi theo môi trường; mã không cần đổi", en: "Configuration varies by environment; code does not" }, narrative: { vi: "Cùng một artifact có thể chạy ở local, staging và production nếu URL, cờ tính năng hoặc credential được cấp từ bên ngoài. Trong Node.js, process.env cung cấp giá trị cho tiến trình và phần lớn giá trị là chuỗi; gán 'false' không tự biến thành boolean false.", en: "The same artifact can run locally, in staging, and in production when URLs, feature flags, and credentials arrive externally. In Node.js, process.env exposes process values and most values are strings; assigning 'false' does not produce boolean false." }, beats: [{ vi: "Tên biến mô tả capability, không mô tả máy cụ thể.", en: "Name variables by capability, not by a particular machine." }, { vi: "Thiếu giá trị bắt buộc phải fail sớm khi khởi động.", en: "Missing required values should fail at startup." }, { vi: "Default chỉ dùng khi thật sự an toàn.", en: "Use defaults only when they are genuinely safe." }], code: { language: "ts", value: "const port = Number(process.env.PORT ?? 3000);\nconst production = process.env.NODE_ENV === 'production';\nif (!Number.isInteger(port)) throw new Error('PORT must be an integer');" } },
      { marker: { vi: "KHOANG 02 · BUILD/RUNTIME", en: "CHAMBER 02 · BUILD/RUNTIME" }, title: { vi: "Build-time value có thể bị đóng cứng vào bundle", en: "A build-time value can be frozen into the bundle" }, narrative: { vi: "Framework frontend thường thay biến public bằng literal lúc build. Đổi biến trên server sau khi deploy không thay bundle đã tạo. Runtime config được đọc khi process hoặc request chạy. Vì vậy phải biết giá trị nào thuộc artifact, giá trị nào thuộc deployment và giá trị nào tuyệt đối không được tới browser.", en: "Frontend frameworks often replace public variables with literals during the build. Changing a server variable after deployment does not rewrite an existing bundle. Runtime config is read when a process or request executes. Decide which values belong to the artifact, the deployment, or must never reach the browser." }, beats: [{ vi: "Public prefix là lời đồng ý đưa giá trị vào client.", en: "A public prefix is consent to expose a value to the client." }, { vi: "API base URL có thể public; database password thì không.", en: "An API base URL may be public; a database password may not." }, { vi: "Inspect bundle thay vì tin vào tên biến.", en: "Inspect the bundle instead of trusting a variable name." }], warning: { vi: "Secret từng đi vào bundle vẫn phải rotate dù đã xóa khỏi source.", en: "A secret that reached a bundle must be rotated even after removal from source." } },
      { marker: { vi: "KHOANG 03 · VALIDATION", en: "CHAMBER 03 · VALIDATION" }, title: { vi: "Parse một lần thành object cấu hình có kiểu", en: "Parse once into a typed configuration object" }, narrative: { vi: "Đọc process.env rải rác khiến quy tắc parsing và default không nhất quán. Hãy tập trung validation ở composition root, kiểm tra enum, URL, số và biến bắt buộc, sau đó truyền một object bất biến cho phần còn lại. Lỗi cấu hình nên xuất hiện trước khi nhận traffic.", en: "Reading process.env throughout the codebase scatters parsing and defaults. Validate once at the composition root, checking enums, URLs, numbers, and required values, then pass an immutable configuration object onward. Configuration failures should appear before traffic arrives." }, beats: [{ vi: "Phân biệt undefined, chuỗi rỗng và giá trị sai.", en: "Distinguish undefined, empty, and invalid values." }, { vi: "Thông báo tên biến thiếu nhưng không in giá trị bí mật.", en: "Name the missing variable without printing its secret value." }, { vi: "Test parser bằng ma trận cấu hình nhỏ.", en: "Test the parser with a small configuration matrix." }], code: { language: "ts", value: "export const config = Object.freeze({\n  databaseUrl: required('DATABASE_URL'),\n  logLevel: oneOf('LOG_LEVEL', ['debug', 'info', 'error']),\n  timeoutMs: positiveInt('TIMEOUT_MS', 5000),\n});" } },
      { marker: { vi: "KHOANG 04 · SECRET HYGIENE", en: "CHAMBER 04 · SECRET HYGIENE" }, title: { vi: ".env tiện cho local nhưng không phải hệ thống quản lý secret", en: ".env is convenient locally, not a secret-management system" }, narrative: { vi: "Không commit file chứa secret; dùng .env.example chỉ với tên và giá trị giả. Production nên cấp secret bằng nền tảng triển khai hoặc secret manager, giới hạn quyền đọc, rotate định kỳ và audit truy cập. Secret cũng có thể rò qua crash report, command history, CI output và snapshot process.", en: "Do not commit secret-bearing files; keep only names and fake values in .env.example. Production should inject secrets through the deployment platform or a secret manager, restrict readers, rotate, and audit access. Secrets can also leak through crash reports, shell history, CI output, and process snapshots." }, beats: [{ vi: "Phát hiện secret trong git: revoke trước, xóa lịch sử sau.", en: "Secret found in Git: revoke first, rewrite history second." }, { vi: "Cấp quyền tối thiểu cho từng service.", en: "Grant least privilege to each service." }, { vi: "Không dùng cùng credential cho local và production.", en: "Never share one credential between local and production." }], code: { language: "text", value: "# .env.example (safe to commit)\nDATABASE_URL=postgres://user:password@localhost:5432/app\nPAYMENT_API_KEY=replace-me\n# .env stays ignored and contains real local values." } },
    ],
    sources: [{ label: "Node.js — Environment variables", href: "https://nodejs.org/api/environment_variables.html" }, { label: "Node.js — process.env", href: "https://nodejs.org/api/process.html#processenv" }, { label: "The Twelve-Factor App — Config", href: "https://12factor.net/config" }, { label: "OWASP — Secrets management", href: "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html" }],
  },
  "git-basics": {
    mode: "git-workbench",
    eyebrow: { vi: "GIT WORKBENCH · SNAPSHOT MODEL", en: "GIT WORKBENCH · SNAPSHOT MODEL" },
    thesis: { vi: "Git dễ hiểu hơn khi ngừng nghĩ nó là nút Save: working tree là bàn làm việc, staging area là bản nháp snapshot kế tiếp và commit là một node lịch sử bất biến.", en: "Git becomes simpler when it stops looking like a Save button: the working tree is your desk, the index is the draft of the next snapshot, and a commit is an immutable history node." },
    mission: { vi: "Đi một thay đổi qua working tree → index → commit → remote và biết chính xác mỗi lệnh đang tác động lớp nào.", en: "Move one change through working tree → index → commit → remote while knowing exactly which layer each command affects." },
    simulation: { label: { vi: "Ba vùng và một remote", en: "Three areas and a remote" }, tracks: [
      { name: { vi: "Working tree", en: "Working tree" }, detail: { vi: "file đang sửa", en: "files being edited" }, tone: "warm" },
      { name: { vi: "Index", en: "Index" }, detail: { vi: "snapshot kế tiếp", en: "next snapshot" }, tone: "hot" },
      { name: { vi: "Repository", en: "Repository" }, detail: { vi: "commit graph · refs", en: "commit graph · refs" }, tone: "cool" },
    ] },
    stations: [
      { marker: { vi: "BÀN 01 · REPOSITORY", en: "BENCH 01 · REPOSITORY" }, title: { vi: "Git lưu snapshot và quan hệ cha, không lưu một thư mục ảnh chụp rời rạc", en: "Git stores snapshots and parent relationships, not unrelated folder copies" }, narrative: { vi: "Mỗi commit trỏ tới một snapshot nội dung, commit cha và metadata. Branch chỉ là ref di chuyển tới commit; HEAD cho biết ref/commit đang checkout. Vì dữ liệu local đã có graph, log, diff và branch không cần mạng.", en: "Each commit points to a content snapshot, parent commit, and metadata. A branch is a moving ref to a commit; HEAD identifies the checked-out ref or commit. Because the graph is local, log, diff, and branching do not need the network." }, beats: [{ vi: "git init tạo database .git; không tải remote.", en: "git init creates .git; it does not fetch a remote." }, { vi: "git clone lấy graph và checkout một working tree.", en: "git clone downloads a graph and checks out a working tree." }, { vi: "Commit ID phụ thuộc nội dung và metadata.", en: "A commit ID depends on content and metadata." }], code: { language: "sh", value: "git status --short\ngit log --oneline --decorate --graph -8\ngit show --stat HEAD" } },
      { marker: { vi: "BÀN 02 · STAGING", en: "BENCH 02 · STAGING" }, title: { vi: "git add nghĩa là đưa đúng nội dung hiện tại vào snapshot kế tiếp", en: "git add means put this exact content into the next snapshot" }, narrative: { vi: "Index nằm giữa working tree và commit. Nếu stage file rồi tiếp tục sửa, một file có thể vừa staged vừa unstaged vì index giữ phiên bản tại thời điểm git add. Dùng git diff xem phần chưa stage và git diff --staged xem chính xác thứ sắp commit.", en: "The index sits between the working tree and commits. If you stage and then edit again, one file can be both staged and unstaged because the index retained the earlier content. git diff shows unstaged work; git diff --staged shows exactly what will be committed." }, beats: [{ vi: "Stage theo patch để tách hai ý định trong cùng file.", en: "Stage by patch to separate two intentions in one file." }, { vi: "Review staged diff ngay trước commit.", en: "Review the staged diff immediately before committing." }, { vi: "Untracked không tự đi vào commit.", en: "Untracked files do not enter a commit automatically." }], code: { language: "sh", value: "git add -p\ngit diff\ngit diff --staged\ngit restore --staged path/to/file" } },
      { marker: { vi: "BÀN 03 · BRANCH", en: "BENCH 03 · BRANCH" }, title: { vi: "Branch là con trỏ nhẹ; switch thay working tree theo snapshot", en: "A branch is a lightweight pointer; switch updates the working tree" }, narrative: { vi: "Tạo branch không sao chép toàn bộ dự án. Commit mới làm branch hiện tại tiến lên. Khi hai branch phân kỳ, merge tạo quan hệ hợp nhất hoặc rebase phát lại commit lên base mới. Người mới nên ưu tiên commit nhỏ, pull trước khi push và đọc graph trước khi xử lý conflict.", en: "Creating a branch does not copy the project. A new commit advances the current branch. When branches diverge, merge records integration while rebase replays commits onto a new base. Beginners should keep commits small, integrate before pushing, and inspect the graph before resolving conflicts." }, beats: [{ vi: "Conflict là hai thay đổi cần quyết định, không phải Git bị hỏng.", en: "A conflict is a decision between changes, not broken Git." }, { vi: "Không rebase commit đã chia sẻ nếu team không thống nhất.", en: "Do not rebase shared commits without team agreement." }, { vi: "Sau resolve: stage kết quả rồi tiếp tục operation.", en: "After resolving: stage the result, then continue the operation." }], warning: { vi: "git reset --hard có thể xóa thay đổi chưa commit; luôn đọc status và target trước.", en: "git reset --hard can destroy uncommitted work; inspect status and the target first." } },
      { marker: { vi: "BÀN 04 · REMOTE", en: "BENCH 04 · REMOTE" }, title: { vi: "fetch cập nhật hiểu biết; pull tích hợp; push công bố", en: "fetch updates knowledge; pull integrates; push publishes" }, narrative: { vi: "Remote là tên cho một repository khác. origin/main là remote-tracking ref local được cập nhật bởi fetch. git pull thực chất fetch rồi merge hoặc rebase theo cấu hình. Push gửi object và yêu cầu remote di chuyển ref; nó có thể bị từ chối nếu lịch sử remote đã tiến lên.", en: "A remote names another repository. origin/main is a local remote-tracking ref updated by fetch. git pull is fetch followed by merge or rebase according to configuration. Push sends objects and asks the remote to move a ref; it can be rejected when remote history has advanced." }, beats: [{ vi: "fetch an toàn để quan sát trước khi tích hợp.", en: "fetch is a safe way to inspect before integrating." }, { vi: "upstream liên kết branch local với branch remote.", en: "An upstream links a local branch to a remote branch." }, { vi: "Push không thay thế backup cho file chưa commit.", en: "Push cannot back up uncommitted files." }], code: { language: "sh", value: "git fetch origin\ngit log --oneline --left-right HEAD...origin/main\ngit rebase origin/main\ngit push -u origin feature/docs" } },
    ],
    sources: [{ label: "Pro Git — What is Git?", href: "https://git-scm.com/book/en/v2/Getting-Started-What-is-Git" }, { label: "Pro Git — Recording changes", href: "https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository" }, { label: "Pro Git — Remotes", href: "https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes" }],
  },
  "commit-messages": {
    mode: "history-ledger",
    eyebrow: { vi: "HISTORY LEDGER · INTENT OVER ACTIVITY", en: "HISTORY LEDGER · INTENT OVER ACTIVITY" },
    thesis: { vi: "Diff cho biết mã đã đổi thế nào; commit message phải giữ lý do và hệ quả mà diff không thể tự kể. Một lịch sử tốt là công cụ debug và review, không phải nhật ký gõ phím.", en: "A diff shows how code changed; the commit message preserves why and what follows from that change. Good history is a debugging and review tool, not a typing diary." },
    mission: { vi: "Tạo commit atomic, viết subject nói rõ ý định và dùng body để lưu bối cảnh mà người đọc sáu tháng sau vẫn cần.", en: "Create an atomic commit, write a subject that states intent, and use the body to retain context a reader still needs six months later." },
    simulation: { label: { vi: "Anatomy của một commit", en: "Anatomy of a commit" }, tracks: [
      { name: { vi: "Subject", en: "Subject" }, detail: { vi: "ý định ngắn, cụ thể", en: "short specific intent" }, tone: "hot" },
      { name: { vi: "Body", en: "Body" }, detail: { vi: "vì sao · đánh đổi · hành vi", en: "why · trade-offs · behaviour" }, tone: "warm" },
      { name: { vi: "Footer", en: "Footer" }, detail: { vi: "issue · breaking change", en: "issue · breaking change" }, tone: "cool" },
    ] },
    stations: [
      { marker: { vi: "MỤC 01 · ATOMIC", en: "ENTRY 01 · ATOMIC" }, title: { vi: "Một commit nên trả lời một câu hỏi review", en: "One commit should answer one review question" }, narrative: { vi: "Atomic không có nghĩa là ít dòng; nó nghĩa là một ý định có thể hiểu, test và revert độc lập. Đừng trộn format toàn repo, refactor và sửa bug vào cùng snapshot. Staging theo patch giúp chọn đúng hunks ngay cả khi working tree chứa nhiều việc.", en: "Atomic does not mean few lines; it means one intention that can be understood, tested, and reverted independently. Do not mix repository-wide formatting, refactoring, and a bug fix in one snapshot. Patch staging selects the right hunks even when the working tree contains several tasks." }, beats: [{ vi: "Commit giữ project ở trạng thái hợp lệ khi khả thi.", en: "Keep the project valid at each commit when practical." }, { vi: "Test đi cùng thay đổi hành vi mà nó bảo vệ.", en: "Tests travel with the behaviour they protect." }, { vi: "Tách mechanical change khỏi semantic change.", en: "Separate mechanical changes from semantic changes." }], code: { language: "sh", value: "git add -p\ngit diff --staged\nnpm test\ngit commit" } },
      { marker: { vi: "MỤC 02 · SUBJECT", en: "ENTRY 02 · SUBJECT" }, title: { vi: "Subject mô tả kết quả, không kể thao tác", en: "The subject states the outcome, not the activity" }, narrative: { vi: "“Update files” không giúp tìm lịch sử. Dùng động từ mệnh lệnh và đối tượng cụ thể: “Prevent duplicate checkout submissions”. Người đọc có thể hoàn thành câu “Nếu áp dụng commit này, nó sẽ…”. Type/scope của Conventional Commits hữu ích cho automation nhưng không thay thế mô tả rõ.", en: "'Update files' does not help history search. Use an imperative verb and a concrete object: 'Prevent duplicate checkout submissions'. A reader should finish the sentence, 'If applied, this commit will…'. Conventional Commit types and scopes help automation but do not replace a clear description." }, beats: [{ vi: "Ngắn để đọc trong log, cụ thể để grep.", en: "Short enough for logs, specific enough to grep." }, { vi: "Không thêm dấu chấm chỉ để trang trí subject.", en: "Do not add punctuation merely to decorate the subject." }, { vi: "Issue ID bổ sung context, không thay nội dung.", en: "An issue ID adds context; it does not replace the subject." }], code: { language: "text", value: "fix(checkout): prevent duplicate payment requests\n\nDisable resubmission while the first request is pending.\nThe server idempotency key remains the final safety boundary.\n\nRefs: PAY-214" } },
      { marker: { vi: "MỤC 03 · BODY", en: "ENTRY 03 · BODY" }, title: { vi: "Body lưu quyết định không thể suy ra từ diff", en: "The body preserves decisions the diff cannot reveal" }, narrative: { vi: "Giải thích vấn đề trước thay đổi, lý do chọn giải pháp này, hành vi mới, đánh đổi và migration nếu có. Không cần chép lại từng file đã sửa. Với breaking change, nói rõ consumer phải làm gì; với security fix, tránh tiết lộ exploit trước khi phát hành an toàn.", en: "Explain the prior problem, why this approach was chosen, new behaviour, trade-offs, and migration where relevant. Do not narrate every edited file. For a breaking change, state what consumers must do; for a security fix, avoid disclosing an exploit before coordinated release." }, beats: [{ vi: "Why quan trọng hơn bản tóm tắt diff.", en: "Why matters more than a diff summary." }, { vi: "Ghi constraint khiến lựa chọn khác bị loại.", en: "Record the constraint that ruled out alternatives." }, { vi: "Link ADR/issue khi bối cảnh dài hơn commit.", en: "Link an ADR or issue when context exceeds the commit." }], warning: { vi: "Conventional Commits chuẩn hóa cấu trúc, không đảm bảo commit có nội dung tốt hoặc atomic.", en: "Conventional Commits standardises structure; it does not guarantee useful or atomic commits." } },
      { marker: { vi: "MỤC 04 · LỊCH SỬ", en: "ENTRY 04 · HISTORY" }, title: { vi: "Viết cho blame, bisect, revert và người review tương lai", en: "Write for blame, bisect, revert, and future reviewers" }, narrative: { vi: "Một lịch sử tuyến tính đẹp không đáng đổi bằng việc rewrite commit người khác đang dùng. Trước khi push, có thể amend subject, reorder hoặc squash WIP local để câu chuyện rõ. Sau khi chia sẻ, ưu tiên commit sửa mới hoặc revert để lịch sử hợp tác không bị thay dưới chân đồng đội.", en: "A tidy linear history is not worth rewriting commits others depend on. Before pushing, amend a subject, reorder, or squash local WIP to clarify the story. After sharing, prefer a follow-up fix or revert so collaborative history does not move beneath teammates." }, beats: [{ vi: "git show kiểm tra snapshot và message cùng nhau.", en: "Use git show to review snapshot and message together." }, { vi: "git log --grep tìm quyết định bằng từ khóa domain.", en: "Use git log --grep to find decisions by domain language." }, { vi: "Revert tốt hơn undo thủ công khi cần lưu dấu quyết định.", en: "Revert beats manual undo when the decision trail matters." }], code: { language: "sh", value: "git show --stat --format=fuller HEAD\ngit commit --amend\ngit log --oneline --grep='checkout'\ngit revert <commit>" } },
    ],
    sources: [{ label: "Git — git commit", href: "https://git-scm.com/docs/git-commit" }, { label: "Pro Git — Recording changes", href: "https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository" }, { label: "Pro Git — Rewriting history", href: "https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History" }, { label: "Conventional Commits — Specification", href: "https://www.conventionalcommits.org/en/v1.0.0/" }],
  },
};
