import type { CreativeGuide } from "./docs-creative-content";

export const qualityCreativeGuides: Record<string, CreativeGuide> = {
  "pull-requests": {
    mode: "review-room",
    eyebrow: { vi: "REVIEW ROOM · DECISION QUEUE", en: "REVIEW ROOM · DECISION QUEUE" },
    thesis: { vi: "Pull Request không phải nơi chứng minh mình đã viết nhiều code; nó là gói bằng chứng đủ nhỏ để người khác hiểu thay đổi, kiểm tra rủi ro và đưa ra quyết định merge.", en: "A pull request is not proof that you wrote a lot of code; it is a small evidence package that lets someone understand the change, assess risk, and make a merge decision." },
    mission: { vi: "Chuẩn bị một PR có một ý định, mô tả được kiểm chứng, diff dễ đọc và cuộc hội thoại phân biệt rõ blocker với gợi ý.", en: "Prepare a PR with one intention, a verifiable description, a readable diff, and a conversation that distinguishes blockers from suggestions." },
    simulation: { label: { vi: "Hàng đợi review", en: "Review decision queue" }, tracks: [
      { name: { vi: "Context", en: "Context" }, detail: { vi: "vấn đề · phạm vi · ảnh hưởng", en: "problem · scope · impact" }, tone: "cool" },
      { name: { vi: "Evidence", en: "Evidence" }, detail: { vi: "diff · test · screenshot", en: "diff · tests · screenshots" }, tone: "warm" },
      { name: { vi: "Decision", en: "Decision" }, detail: { vi: "comment · approve · request changes", en: "comment · approve · request changes" }, tone: "hot" },
    ] },
    stations: [
      { marker: { vi: "PHÒNG 01 · SCOPE", en: "ROOM 01 · SCOPE" }, title: { vi: "Một PR nên chứa một thay đổi tự hoàn chỉnh", en: "One PR should carry one self-contained change" }, narrative: { vi: "Kích thước được đo bằng tải nhận thức, không chỉ số dòng. Tách refactor cơ học khỏi thay đổi hành vi; giữ test liên quan cùng feature. PR nhỏ được review nhanh, kỹ hơn và dễ rollback, nhưng không nên nhỏ đến mức API mới xuất hiện mà chưa có chỗ dùng.", en: "Size is cognitive load, not only line count. Separate mechanical refactors from behaviour changes and keep related tests with the feature. Small PRs are reviewed faster and more thoroughly and are easier to roll back, but should not be so tiny that a new API has no usage." }, beats: [{ vi: "Một title có thể tóm tắt toàn bộ ý định.", en: "One title can summarise the whole intention." }, { vi: "Không trộn format toàn repo với sửa bug.", en: "Do not mix repository-wide formatting with a bug fix." }, { vi: "Nếu review cần sơ đồ lớn, cân nhắc design review trước.", en: "If review needs a large architecture explanation, consider design review first." }], code: { language: "text", value: "Title: Prevent duplicate checkout submissions\n\nWhy: double-clicks can create two payment requests.\nWhat: lock submit while pending; retain server idempotency.\nVerify: unit test + slow-network recording.\nOut of scope: retry policy." } },
      { marker: { vi: "PHÒNG 02 · SELF-REVIEW", en: "ROOM 02 · SELF-REVIEW" }, title: { vi: "Tác giả là reviewer đầu tiên", en: "The author is the first reviewer" }, narrative: { vi: "Đọc diff từ đầu như người không có context. Xóa log, file sinh ra và thay đổi ngoài scope; kiểm tra tên, edge case, security, accessibility và tài liệu. Chạy đúng lệnh CI sẽ chạy, đồng thời mô tả phần chưa test được thay vì để reviewer đoán.", en: "Read the diff from the beginning as someone without context. Remove logs, generated files, and out-of-scope edits; inspect names, edge cases, security, accessibility, and docs. Run the same checks CI will run and state what could not be tested instead of making reviewers guess." }, beats: [{ vi: "Review commit list lẫn Files changed.", en: "Review both the commit list and Files changed." }, { vi: "Giải thích migration và rollback khi có dữ liệu/state.", en: "Explain migration and rollback when data or state changes." }, { vi: "Ảnh/video phải chứng minh trạng thái quan trọng, không chỉ happy path.", en: "Images or video should show important states, not only the happy path." }] },
      { marker: { vi: "PHÒNG 03 · FEEDBACK", en: "ROOM 03 · FEEDBACK" }, title: { vi: "Nhận xét vào code, nêu tác động và mức độ", en: "Comment on the code, explain impact, and label severity" }, narrative: { vi: "Một comment tốt mô tả quan sát, rủi ro và câu hỏi hoặc đề xuất. Dùng blocker/request cho correctness, security hoặc maintainability cần sửa; dùng suggestion/nit cho cải thiện không chặn. Technical facts và chuẩn team quan trọng hơn sở thích cá nhân.", en: "A useful comment states the observation, impact, and a question or proposal. Use blockers or requested changes for correctness, security, or maintainability issues that must change; use suggestions or nits for non-blocking polish. Technical facts and team standards outrank personal taste." }, beats: [{ vi: "Hỏi trước khi kết luận khi thiếu context.", en: "Ask before concluding when context is missing." }, { vi: "Khen cụ thể hành vi tốt để nhân rộng.", en: "Praise specific good practice so it spreads." }, { vi: "Tranh luận dài: đồng bộ trực tiếp rồi ghi kết luận vào PR.", en: "For long disputes, sync directly and record the conclusion in the PR." }], warning: { vi: "Approve không có nghĩa code hoàn hảo; nó nghĩa thay đổi cải thiện codebase và rủi ro đã được xử lý đủ.", en: "Approval does not mean perfect code; it means the change improves the codebase and risks are sufficiently addressed." } },
      { marker: { vi: "PHÒNG 04 · MERGE", en: "ROOM 04 · MERGE" }, title: { vi: "Merge là quyết định vận hành, không chỉ nút màu xanh", en: "Merge is an operational decision, not merely a green button" }, narrative: { vi: "Trước merge, xác nhận checks mới nhất, approvals còn hợp lệ, branch protection và dependency change. Chọn squash, merge commit hoặc rebase theo chính sách lịch sử. Với thay đổi rủi ro, chuẩn bị flag, rollout, metric và rollback owner; sau merge theo dõi production thay vì xem công việc kết thúc.", en: "Before merging, confirm current checks, valid approvals, branch protection, and dependency changes. Choose squash, merge commit, or rebase according to history policy. For risky changes, prepare flags, rollout, metrics, and a rollback owner; observe production after merge rather than treating it as the end." }, beats: [{ vi: "Re-request review khi thay đổi lớn sau approval.", en: "Re-request review after substantial post-approval changes." }, { vi: "Không dùng force push để che feedback chưa xử lý.", en: "Do not use force-push to hide unresolved feedback." }, { vi: "Theo dõi metric liên quan đúng hành vi vừa đổi.", en: "Watch the metric tied to the behaviour that changed." }], code: { language: "text", value: "MERGE GATE\n✓ scope and ownership clear\n✓ required tests/checks current\n✓ security/data migration reviewed\n✓ rollout + rollback defined\n✓ unresolved threads intentionally resolved" } },
    ],
    sources: [{ label: "GitHub Docs — Pull request reviews", href: "https://docs.github.com/en/pull-requests/reference/pull-request-reviews" }, { label: "Google — Small CLs", href: "https://google.github.io/eng-practices/review/developer/small-cls.html" }, { label: "Google — What to look for", href: "https://google.github.io/eng-practices/review/reviewer/looking-for.html" }, { label: "Google — Review comments", href: "https://google.github.io/eng-practices/review/reviewer/comments.html" }],
  },
  "clean-code": {
    mode: "change-budget",
    eyebrow: { vi: "CHANGE BUDGET · COST OF UNDERSTANDING", en: "CHANGE BUDGET · COST OF UNDERSTANDING" },
    thesis: { vi: "Clean code không phải code ngắn hay code theo một cuốn sách; đó là code làm cho thay đổi đúng tiếp theo ít bất ngờ, ít nơi phải sửa và dễ kiểm chứng.", en: "Clean code is not short code or code that obeys one book; it is code that makes the next correct change unsurprising, local, and easy to verify." },
    mission: { vi: "Đọc một thay đổi qua bốn loại chi phí: hiểu ý định, tìm ownership, sửa hành vi và chứng minh không phá phần còn lại.", en: "Read a change through four costs: understanding intent, locating ownership, modifying behaviour, and proving the rest still works." },
    simulation: { label: { vi: "Ngân sách của một thay đổi", en: "A change budget" }, tracks: [
      { name: { vi: "Hiểu", en: "Understand" }, detail: { vi: "tên · flow · invariant", en: "names · flow · invariants" }, tone: "cool" },
      { name: { vi: "Sửa", en: "Change" }, detail: { vi: "cohesion · coupling", en: "cohesion · coupling" }, tone: "warm" },
      { name: { vi: "Kiểm chứng", en: "Verify" }, detail: { vi: "test · types · observation", en: "tests · types · observation" }, tone: "hot" },
    ] },
    stations: [
      { marker: { vi: "CHI PHÍ 01 · TÊN", en: "COST 01 · NAMES" }, title: { vi: "Tên tốt nén đúng domain, không nén thao tác kỹ thuật", en: "Good names compress the domain, not implementation trivia" }, narrative: { vi: "Tên cần trả lời giá trị này đại diện điều gì và đơn vị/trạng thái nào. Tránh data, temp, handle khi có từ domain chính xác. Boolean nên đọc như mệnh đề; function nên nói kết quả hoặc side effect. Nếu cần comment dịch tên, hãy sửa tên trước.", en: "A name should reveal what a value represents and its unit or state. Avoid data, temp, and handle when domain language exists. Booleans should read as propositions; functions should state their result or side effect. If a comment translates a name, improve the name first." }, beats: [{ vi: "Dùng cùng một từ cho cùng một khái niệm.", en: "Use one term for one concept." }, { vi: "Gắn đơn vị vào tên khi type chưa biểu đạt được.", en: "Include units when the type cannot express them." }, { vi: "Tên dài hợp lý tốt hơn viết tắt riêng của tác giả.", en: "A reasonably long name beats a private abbreviation." }], code: { language: "ts", value: "// Before\nconst d = Date.now() - item.t;\n\n// After\nconst ageMilliseconds = Date.now() - cacheEntry.createdAt;\nconst isExpired = ageMilliseconds > cacheTtlMilliseconds;" } },
      { marker: { vi: "CHI PHÍ 02 · COHESION", en: "COST 02 · COHESION" }, title: { vi: "Tách theo lý do thay đổi, không tách chỉ vì hàm dài", en: "Split by reason to change, not only by line count" }, narrative: { vi: "Một function 40 dòng có một flow rõ có thể dễ đổi hơn năm helper nhảy qua lại. Tách khi một khối có tên domain, invariant hoặc dependency riêng. Đặt dữ liệu và hành vi thay đổi cùng nhau gần nhau; tránh utility chung chứa mọi thứ không biết để đâu.", en: "A clear 40-line flow can be easier to change than five helpers that bounce around. Extract when a block owns domain language, an invariant, or a dependency. Keep data and behaviour that change together close; avoid generic utility modules for everything without a home." }, beats: [{ vi: "High cohesion: một module có một câu chuyện nhất quán.", en: "High cohesion: one module tells one coherent story." }, { vi: "Helper chỉ gọi một lần vẫn phải giảm tải nhận thức.", en: "A one-call helper must still reduce cognitive load." }, { vi: "Ẩn invariant sau API nhỏ thay vì lặp guard.", en: "Hide invariants behind a small API instead of repeating guards." }] },
      { marker: { vi: "CHI PHÍ 03 · COUPLING", en: "COST 03 · COUPLING" }, title: { vi: "Dependency rõ ràng rẻ hơn global state tiện lợi", en: "Explicit dependencies are cheaper than convenient global state" }, narrative: { vi: "Code khó test thường đọc clock, network, environment hoặc singleton ẩn. Truyền dependency tại boundary làm ownership và failure mode lộ rõ. Nhưng dependency injection không đồng nghĩa tạo interface cho mọi class; chỉ tạo seam tại nơi cần thay thế policy hoặc I/O.", en: "Hard-to-test code often reads clocks, networks, environment, or singletons invisibly. Passing dependencies at a boundary reveals ownership and failure modes. Dependency injection does not require an interface for every class; create seams where policy or I/O genuinely varies." }, beats: [{ vi: "Pure core, imperative shell là một hướng hữu ích.", en: "A pure core and imperative shell is a useful direction." }, { vi: "Không để domain import framework ở mọi tầng.", en: "Do not make every domain layer import the framework." }, { vi: "Giảm số module phải sửa cho một feature.", en: "Reduce the modules touched by one feature." }], code: { language: "ts", value: "export function quote(order, { now, priceRules }) {\n  const activeRules = priceRules.filter(rule => rule.activeAt(now));\n  return applyRules(order, activeRules);\n}\n// Tests supply a fixed clock and focused rules." } },
      { marker: { vi: "CHI PHÍ 04 · REFACTOR", en: "COST 04 · REFACTOR" }, title: { vi: "Refactor là thay cấu trúc trong khi giữ hành vi quan sát được", en: "Refactoring changes structure while preserving observable behaviour" }, narrative: { vi: "Trước refactor, xác định hành vi đang được bảo vệ bằng test hoặc characterization. Thực hiện bước nhỏ, chạy kiểm tra thường xuyên và tách khỏi feature nếu diff cơ học lớn. Không tối ưu abstraction cho tương lai tưởng tượng; duplication đôi khi rẻ hơn một abstraction sai.", en: "Before refactoring, identify observable behaviour protected by tests or characterization. Take small steps, run checks frequently, and separate large mechanical changes from features. Do not optimise abstractions for an imagined future; duplication can be cheaper than the wrong abstraction." }, beats: [{ vi: "Code smell là tín hiệu điều tra, không phải verdict.", en: "A code smell is an investigation signal, not a verdict." }, { vi: "Đo improvement bằng thay đổi tiếp theo và defect rate.", en: "Measure improvement through the next change and defect rate." }, { vi: "Xóa abstraction không còn trả được chi phí.", en: "Delete abstractions that no longer repay their cost." }], warning: { vi: "Áp dụng máy móc “function phải ngắn” có thể phá flow và tăng số context switch.", en: "Mechanical rules such as 'functions must be short' can destroy flow and increase context switching." } },
    ],
    sources: [{ label: "Google — What to look for in review", href: "https://google.github.io/eng-practices/review/reviewer/looking-for.html" }, { label: "Martin Fowler — Refactoring", href: "https://refactoring.com/" }, { label: "Google TypeScript Style Guide", href: "https://google.github.io/styleguide/tsguide.html" }],
  },
  "debugging-basics": {
    mode: "debug-lab",
    eyebrow: { vi: "DEBUG LAB · EVIDENCE BEFORE EDITS", en: "DEBUG LAB · EVIDENCE BEFORE EDITS" },
    thesis: { vi: "Debugging không phải thử sửa cho tới khi lỗi biến mất; đó là quá trình biến một triệu khả năng thành một nguyên nhân bằng tái hiện, quan sát và thí nghiệm có kiểm soát.", en: "Debugging is not changing code until the symptom disappears; it is reducing a million possibilities to one cause through reproduction, observation, and controlled experiments." },
    mission: { vi: "Đi từ báo cáo mơ hồ tới reproduction tối thiểu, giả thuyết có thể bác bỏ, fix tại nguồn và regression test chứng minh lỗi không quay lại.", en: "Move from a vague report to a minimal reproduction, a falsifiable hypothesis, a source-level fix, and a regression test proving the bug stays gone." },
    simulation: { label: { vi: "Vòng lặp điều tra", en: "Investigation loop" }, tracks: [
      { name: { vi: "Tái hiện", en: "Reproduce" }, detail: { vi: "input · environment · frequency", en: "input · environment · frequency" }, tone: "hot" },
      { name: { vi: "Cô lập", en: "Isolate" }, detail: { vi: "boundary · diff · binary search", en: "boundary · diff · binary search" }, tone: "warm" },
      { name: { vi: "Xác minh", en: "Verify" }, detail: { vi: "regression test · counterexample", en: "regression test · counterexample" }, tone: "cool" },
    ] },
    stations: [
      { marker: { vi: "LAB 01 · REPRODUCTION", en: "LAB 01 · REPRODUCTION" }, title: { vi: "Đóng băng triệu chứng thành một quy trình lặp lại", en: "Freeze the symptom into a repeatable procedure" }, narrative: { vi: "Ghi expected và actual, input nhỏ nhất, phiên bản, thiết bị, account state và tần suất. Nếu lỗi không ổn định, thu thập timestamp, correlation ID và điều kiện cạnh tranh thay vì đoán. Một reproduction tốt giúp phân biệt lỗi code với dữ liệu, config hoặc dependency.", en: "Record expected and actual behaviour, the smallest input, versions, device, account state, and frequency. For intermittent failures, capture timestamps, correlation IDs, and race conditions instead of guessing. A good reproduction separates code defects from data, configuration, and dependency failures." }, beats: [{ vi: "Bắt đầu từ môi trường xảy ra lỗi, rồi giảm dần.", en: "Start where the failure occurs, then reduce." }, { vi: "Không đổi nhiều biến trong lúc tái hiện.", en: "Do not change multiple variables while reproducing." }, { vi: "Lưu sample lỗi thật sau khi đã loại dữ liệu nhạy cảm.", en: "Keep a sanitised real failing sample." }], code: { language: "text", value: "REPRO\nGiven: account has two expired sessions\nWhen: refresh token requests overlap within 50ms\nThen: one request returns 401 and clears the new session\nFrequency: 7/10 with network throttling" } },
      { marker: { vi: "LAB 02 · OBSERVE", en: "LAB 02 · OBSERVE" }, title: { vi: "Dừng tại điểm sai đầu tiên, không tại nơi crash cuối cùng", en: "Pause at the first wrong state, not the final crash" }, narrative: { vi: "Dùng breakpoint điều kiện, logpoint, watch expression và call stack để theo data flow. Network panel trả lời request nào đi, payload/status/timing ra sao. Đặt instrumentation ở boundary để xem dữ liệu vào và ra; log mọi nơi chỉ tạo nhiễu và có thể thay timing.", en: "Use conditional breakpoints, logpoints, watch expressions, and the call stack to follow data flow. The Network panel answers which request ran and its payload, status, and timing. Instrument boundaries to compare inputs and outputs; logging everywhere adds noise and can change timing." }, beats: [{ vi: "Step over flow đã biết; step into nơi giả thuyết tập trung.", en: "Step over known flow; step into the suspected boundary." }, { vi: "Pause on exception để bắt lúc lỗi được tạo.", en: "Pause on exceptions to catch creation time." }, { vi: "Đừng mutate state trong console rồi quên điều kiện gốc.", en: "Do not mutate state in Console and lose the original conditions." }], code: { language: "js", value: "console.debug('token_refresh_boundary', {\n  requestId, sessionVersion, startedAt,\n});\n// Add a conditional breakpoint: sessionVersion !== activeVersion" } },
      { marker: { vi: "LAB 03 · HYPOTHESIS", en: "LAB 03 · HYPOTHESIS" }, title: { vi: "Mỗi thí nghiệm chỉ kiểm tra một giả thuyết có thể sai", en: "Each experiment tests one falsifiable hypothesis" }, narrative: { vi: "Viết rõ: “Tôi nghĩ X gây Y vì bằng chứng Z; nếu đúng, thay đổi Q sẽ làm triệu chứng biến mất còn biến khác giữ nguyên.” So sánh working/broken, bisect theo commit hoặc boundary và thay một biến. Nếu kết quả trái dự đoán, bỏ giả thuyết thay vì thêm patch chồng.", en: "State: 'I think X causes Y because evidence Z; if true, changing Q removes the symptom while other variables stay fixed.' Compare working and broken cases, bisect commits or boundaries, and change one variable. If evidence contradicts the prediction, discard the hypothesis instead of stacking patches." }, beats: [{ vi: "Correlation gợi ý vị trí; không tự chứng minh nguyên nhân.", en: "Correlation suggests a location; it does not prove cause." }, { vi: "Đọc error/stack đầy đủ trước khi search message.", en: "Read the complete error and stack before searching its message." }, { vi: "Kiểm tra recent change nhưng không mặc định commit mới nhất có lỗi.", en: "Inspect recent changes without assuming the newest commit is guilty." }], warning: { vi: "Một fix làm lỗi biến mất nhưng không giải thích được cơ chế vẫn chưa phải bằng chứng đủ.", en: "A change that hides the symptom without explaining the mechanism is not sufficient evidence." } },
      { marker: { vi: "LAB 04 · FIX & VERIFY", en: "LAB 04 · FIX & VERIFY" }, title: { vi: "Sửa tại nguồn dữ liệu sai và giữ reproduction thành test", en: "Fix the source of bad state and preserve the reproduction as a test" }, narrative: { vi: "Trace ngược từ state sai tới nơi đầu tiên tạo ra nó. Viết regression test thất bại trước fix, sửa tối thiểu tại source, rồi chạy test mới, suite liên quan và counterexample. Xóa instrumentation tạm hoặc chuyển metric cần thiết thành observability có chủ đích.", en: "Trace backward from bad state to the first producer. Write a regression test that fails before the fix, make the smallest source-level change, then run the new test, the related suite, and counterexamples. Remove temporary instrumentation or promote useful signals into intentional observability." }, beats: [{ vi: "Verify cả triệu chứng và nguyên nhân dự đoán.", en: "Verify both the symptom and predicted mechanism." }, { vi: "Test failure message phải chứng minh đúng regression.", en: "The failing test message must demonstrate the intended regression." }, { vi: "Ghi lại root cause và lỗ hổng giám sát nếu có.", en: "Record root cause and any observability gap." }], code: { language: "js", value: "test('stale refresh cannot clear a newer session', async () => {\n  const newer = await sessions.rotate(oldSession);\n  await sessions.finishRefresh(oldSession);\n  expect(await sessions.current()).toEqual(newer);\n});" } },
    ],
    sources: [{ label: "Chrome DevTools — Debug JavaScript", href: "https://developer.chrome.com/docs/devtools/javascript/" }, { label: "Chrome DevTools — Breakpoints", href: "https://developer.chrome.com/docs/devtools/javascript/breakpoints" }, { label: "Node.js — Debugger", href: "https://nodejs.org/api/debugger.html" }],
  },
};
