import type { CreativeGuide } from "./docs-creative-content";

export const nextCreativeGuides: Record<string, CreativeGuide> = {
  "javascript-errors": {
    mode: "incident-desk",
    eyebrow: { vi: "INCIDENT DESK · ERROR #JS-042", en: "INCIDENT DESK · ERROR #JS-042" },
    thesis: { vi: "Xử lý lỗi tốt không phải là làm lỗi biến mất; đó là giữ đủ bằng chứng để hiểu nguyên nhân, phục hồi đúng chỗ và không nói dối người dùng.", en: "Good error handling does not make failures disappear; it preserves enough evidence to explain the cause, recover at the right boundary, and tell the user the truth." },
    mission: { vi: "Theo một lỗi từ nơi phát sinh qua call stack đến boundary có thể retry, fallback, báo lỗi hoặc dừng an toàn.", en: "Trace one failure from its origin through the call stack to a boundary that can retry, fall back, report, or stop safely." },
    simulation: { label: { vi: "Đường đi của một lỗi", en: "An error's route" }, tracks: [
      { name: { vi: "Phát sinh", en: "Origin" }, detail: { vi: "throw · reject · lỗi runtime", en: "throw · reject · runtime fault" }, tone: "hot" },
      { name: { vi: "Thêm ngữ cảnh", en: "Add context" }, detail: { vi: "Error cause · mã lỗi · operation", en: "Error cause · code · operation" }, tone: "warm" },
      { name: { vi: "Quyết định", en: "Decision" }, detail: { vi: "retry · fallback · báo người dùng", en: "retry · fallback · user feedback" }, tone: "cool" },
    ] },
    stations: [
      { marker: { vi: "HỒ SƠ 01 · PHÂN LOẠI", en: "CASE 01 · CLASSIFY" }, title: { vi: "Lỗi lập trình và lỗi vận hành cần hai phản ứng khác nhau", en: "Programmer errors and operational failures need different responses" }, narrative: { vi: "SyntaxError, ReferenceError và phần lớn TypeError thường chỉ ra giả định sai trong mã; retry hiếm khi sửa được chúng. Network timeout, 429 hay dữ liệu người dùng không hợp lệ là tình huống vận hành có thể dự đoán. Hãy phân loại theo khả năng phục hồi thay vì chỉ nhìn tên class.", en: "SyntaxError, ReferenceError, and many TypeErrors usually expose a broken coding assumption; retry rarely fixes them. Network timeouts, 429 responses, and invalid user input are expected operational conditions. Classify by recoverability, not only by class name." }, beats: [{ vi: "Bug: fail fast, giữ stack và sửa nguyên nhân.", en: "Bug: fail fast, preserve the stack, fix the cause." }, { vi: "Expected failure: trả trạng thái có cấu trúc.", en: "Expected failure: return a structured state." }, { vi: "Transient failure: retry có giới hạn và backoff.", en: "Transient failure: bounded retry with backoff." }] },
      { marker: { vi: "HỒ SƠ 02 · BẰNG CHỨNG", en: "CASE 02 · EVIDENCE" }, title: { vi: "Bọc lỗi để thêm ngữ cảnh, không xóa dấu vết", en: "Wrap to add context, never to erase evidence" }, narrative: { vi: "Một thông báo như “Request failed” không đủ để điều tra. Khi đổi tầng abstraction, tạo Error mới với thông điệp ở ngôn ngữ của tầng đó và giữ lỗi gốc trong cause. Đừng dựa vào nội dung message để điều khiển logic; mã lỗi hoặc class ổn định hơn.", en: "A message such as 'Request failed' is not enough to investigate. At an abstraction boundary, create a new Error in that layer's language and retain the original in cause. Do not drive logic by parsing human messages; stable codes or classes are safer." }, beats: [{ vi: "message cho người đọc; code cho chương trình.", en: "message is for people; code is for programs." }, { vi: "stack chỉ hữu ích khi không bị thay bằng lỗi rỗng.", en: "A stack helps only when it is not replaced by an empty wrapper." }, { vi: "Không log token, cookie hoặc payload nhạy cảm.", en: "Never log tokens, cookies, or sensitive payloads." }], code: { language: "js", value: "try {\n  return await repository.save(order);\n} catch (cause) {\n  throw new Error(`Could not save order ${order.id}`, { cause });\n}" } },
      { marker: { vi: "HỒ SƠ 03 · RANH GIỚI", en: "CASE 03 · BOUNDARY" }, title: { vi: "Chỉ catch khi bạn có một quyết định thật sự", en: "Catch only where you can make a real decision" }, narrative: { vi: "Catch ở tầng thấp rồi console.error và trả undefined tạo ra lỗi thứ hai ở nơi xa nguyên nhân. Tầng thấp nên thêm context rồi rethrow; boundary của UI, request handler hoặc job worker mới biết cách đổi lỗi thành retry, fallback, HTTP status hay thông báo có hành động.", en: "Catching low down, logging, and returning undefined creates a second failure far from the cause. Lower layers should add context and rethrow; a UI, request handler, or worker boundary can translate failure into retry, fallback, an HTTP status, or actionable feedback." }, beats: [{ vi: "finally chỉ dành cho cleanup luôn phải chạy.", en: "finally is for cleanup that must always run." }, { vi: "Abort/cancel là trạng thái riêng, không nhất thiết là sự cố.", en: "Abort/cancel is its own state, not necessarily a failure." }, { vi: "Không catch toàn cục để tiếp tục trong trạng thái hỏng.", en: "Do not globally catch and continue in corrupted state." }], warning: { vi: "return trong finally có thể nuốt cả giá trị trả về lẫn exception đang bay lên.", en: "A return inside finally can suppress both a return value and an in-flight exception." } },
      { marker: { vi: "HỒ SƠ 04 · QUAN SÁT", en: "CASE 04 · OBSERVE" }, title: { vi: "Log một sự kiện một lần, tại boundary có đủ context", en: "Log an event once, at the boundary with enough context" }, narrative: { vi: "Log có ích cần timestamp, operation, correlation ID, trạng thái đầu vào đã làm sạch và chuỗi cause. Nếu mỗi tầng đều log rồi rethrow, cùng một lỗi tạo nhiều cảnh báo. Hãy log tại ownership boundary, đo tỷ lệ, nhóm fingerprint và gắn release để biết lỗi mới xuất hiện từ đâu.", en: "Useful telemetry includes time, operation, correlation ID, sanitised input state, and the cause chain. Logging and rethrowing at every layer duplicates one incident. Log at the ownership boundary, measure rates, group fingerprints, and attach the release that introduced the change." }, beats: [{ vi: "Người dùng nhận thông báo có bước tiếp theo.", en: "Users receive an actionable next step." }, { vi: "Developer nhận stack, context và correlation ID.", en: "Developers receive stack, context, and a correlation ID." }, { vi: "Alert dựa trên tỷ lệ/tác động, không dựa trên một log đơn lẻ.", en: "Alert on rate and impact, not one isolated log." }], code: { language: "js", value: "catch (error) {\n  logger.error('checkout_failed', {\n    requestId, orderId, error,\n  });\n  return { ok: false, reason: 'temporary_failure' };\n}" } },
    ],
    sources: [{ label: "MDN — Control flow and error handling", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling" }, { label: "MDN — Error cause", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause" }, { label: "ECMAScript — Error objects", href: "https://tc39.es/ecma262/multipage/fundamental-objects.html#error-objects" }],
  },
  "javascript-modules": {
    mode: "module-graph",
    eyebrow: { vi: "MODULE ATLAS · DEPENDENCY GRAPH", en: "MODULE ATLAS · DEPENDENCY GRAPH" },
    thesis: { vi: "Module không chỉ là một file nhỏ; nó là một hợp đồng công khai và một node trong dependency graph được resolve, liên kết rồi mới thực thi.", en: "A module is not merely a small file; it is a public contract and a node in a dependency graph that is resolved, linked, and only then evaluated." },
    mission: { vi: "Thiết kế graph có hướng rõ, API công khai nhỏ và lazy boundary đặt đúng nơi thay vì chia file theo cảm tính.", en: "Design a directional graph, a small public API, and deliberate lazy boundaries instead of splitting files by instinct." },
    simulation: { label: { vi: "Graph của một tính năng checkout", en: "A checkout feature graph" }, tracks: [
      { name: { vi: "entry.js", en: "entry.js" }, detail: { vi: "composition root", en: "composition root" }, tone: "hot" },
      { name: { vi: "checkout/index.js", en: "checkout/index.js" }, detail: { vi: "public contract", en: "public contract" }, tone: "warm" },
      { name: { vi: "price.js · api.js", en: "price.js · api.js" }, detail: { vi: "chi tiết nội bộ", en: "private internals" }, tone: "cool" },
    ] },
    stations: [
      { marker: { vi: "LỚP 01 · HỢP ĐỒNG", en: "LAYER 01 · CONTRACT" }, title: { vi: "Named export làm API dễ tìm và refactor", en: "Named exports make APIs discoverable and refactorable" }, narrative: { vi: "Export chỉ những gì consumer cần. Named export giữ tên nhất quán giữa producer và consumer, hỗ trợ static analysis và refactor tốt. Default export phù hợp khi module có đúng một khái niệm chính, nhưng việc đổi tên tùy ý có thể làm codebase khó tìm kiếm.", en: "Export only what consumers need. Named exports keep producer and consumer vocabulary aligned and support static analysis and refactoring. A default export can suit one dominant concept, but arbitrary import names make a codebase harder to search." }, beats: [{ vi: "Public API nhỏ hơn surface cần duy trì.", en: "A smaller public API means less surface to maintain." }, { vi: "Barrel file là boundary, không phải nơi export mọi thứ.", en: "A barrel is a boundary, not a dump of every symbol." }, { vi: "Module tự chạy side effect khi import cần được ghi rõ.", en: "Import-time side effects must be explicit." }], code: { language: "js", value: "// checkout/index.js — public boundary\nexport { createCheckout } from './create-checkout.js';\nexport { CheckoutError } from './errors.js';\n// price.js remains private." } },
      { marker: { vi: "LỚP 02 · LIÊN KẾT", en: "LAYER 02 · LINKING" }, title: { vi: "Import là live binding chỉ đọc, không phải bản sao", en: "An import is a read-only live binding, not a copy" }, narrative: { vi: "Static import được hoist và liên kết trước khi module chạy. Consumer không thể gán lại binding đã import, nhưng sẽ quan sát giá trị mới khi exporter cập nhật binding. Cơ chế này giải thích vì sao cycle đôi khi chạy, đôi khi gặp temporal dead zone.", en: "Static imports are hoisted and linked before evaluation. A consumer cannot reassign an imported binding, but observes updates when the exporter changes it. This explains why a cycle sometimes works and sometimes reaches a temporal dead zone." }, beats: [{ vi: "Resolve: specifier trỏ tới module nào?", en: "Resolve: which module does the specifier identify?" }, { vi: "Link: nối import với export tương ứng.", en: "Link: connect imports to matching exports." }, { vi: "Evaluate: chạy mỗi module một lần theo graph.", en: "Evaluate: execute each module once according to the graph." }] },
      { marker: { vi: "LỚP 03 · CHU KỲ", en: "LAYER 03 · CYCLES" }, title: { vi: "Circular import là tín hiệu kiến trúc trước khi là lỗi runtime", en: "A circular import is an architectural signal before a runtime error" }, narrative: { vi: "A nhập B và B nhập lại A tạo strongly connected component. Live bindings cho phép một số cycle hợp lệ, nhưng đọc binding trước khi khởi tạo sẽ ném ReferenceError. Thường nên kéo contract dùng chung xuống module thứ ba hoặc đảo dependency bằng callback/interface.", en: "When A imports B and B imports A, they form a strongly connected component. Live bindings make some cycles valid, but reading a binding before initialization throws ReferenceError. Often the fix is extracting a shared contract or inverting the dependency through a callback or interface." }, beats: [{ vi: "Đừng chữa cycle bằng cách chuyển mọi thứ sang default export.", en: "Do not treat default exports as a cycle fix." }, { vi: "Kiểm tra side effect ở top level.", en: "Inspect top-level side effects." }, { vi: "Dependency nên hướng vào domain ổn định hơn.", en: "Dependencies should point toward the more stable domain." }], warning: { vi: "Một barrel file có thể tạo cycle gián tiếp dù hai file không import nhau trực tiếp.", en: "A barrel can create an indirect cycle even when two files do not import each other directly." } },
      { marker: { vi: "LỚP 04 · RANH GIỚI TẢI", en: "LAYER 04 · LOAD BOUNDARY" }, title: { vi: "dynamic import là quyết định tải và thời điểm thực thi", en: "Dynamic import controls loading and evaluation timing" }, narrative: { vi: "import() trả Promise và chỉ tải/evaluate module khi nhánh được dùng. Đây là công cụ tốt cho route, editor nặng hoặc tính năng hiếm gặp. Không nên chia mọi function thành chunk: nhiều request, waterfall và duplicated runtime có thể đắt hơn số byte tiết kiệm.", en: "import() returns a Promise and loads/evaluates a module only when that path is used. It suits routes, heavy editors, and rare features. Do not split every function: request overhead, waterfalls, and duplicated runtime can cost more than the bytes saved." }, beats: [{ vi: "Đặt boundary theo hành vi người dùng.", en: "Place boundaries around user behaviour." }, { vi: "Prefetch khi xác suất dùng cao và mạng cho phép.", en: "Prefetch when intent is likely and network conditions allow." }, { vi: "Đo chunk graph và thời gian tương tác sau thay đổi.", en: "Measure the chunk graph and interaction latency after changes." }], code: { language: "js", value: "button.addEventListener('click', async () => {\n  const { openEditor } = await import('./editor.js');\n  await openEditor();\n});" } },
    ],
    sources: [{ label: "MDN — JavaScript modules", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules" }, { label: "ECMAScript — Modules", href: "https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-modules" }, { label: "Node.js — Packages", href: "https://nodejs.org/api/packages.html" }],
  },
  "npm-basics": {
    mode: "package-console",
    eyebrow: { vi: "PACKAGE CONTROL · RELEASE SAFE", en: "PACKAGE CONTROL · RELEASE SAFE" },
    thesis: { vi: "package.json mô tả ý định; lockfile ghi lại cây dependency đã giải. Một dự án ổn định cần hiểu cả hai thay vì xem npm install như phép thuật.", en: "package.json records intent; the lockfile records the resolved dependency tree. A stable project understands both instead of treating npm install as magic." },
    mission: { vi: "Đọc một manifest như hợp đồng build, dự đoán phiên bản được cài và dựng quy trình cài đặt có thể lặp lại trong CI.", en: "Read a manifest as a build contract, predict installed versions, and create a reproducible CI installation path." },
    simulation: { label: { vi: "Từ manifest đến node_modules", en: "From manifest to node_modules" }, tracks: [
      { name: { vi: "package.json", en: "package.json" }, detail: { vi: "range · scripts · metadata", en: "ranges · scripts · metadata" }, tone: "warm" },
      { name: { vi: "package-lock.json", en: "package-lock.json" }, detail: { vi: "phiên bản và integrity chính xác", en: "exact versions and integrity" }, tone: "hot" },
      { name: { vi: "npm ci", en: "npm ci" }, detail: { vi: "cây sạch, có thể lặp lại", en: "clean reproducible tree" }, tone: "cool" },
    ] },
    stations: [
      { marker: { vi: "PANEL 01 · MANIFEST", en: "PANEL 01 · MANIFEST" }, title: { vi: "package.json là giao diện vận hành của repository", en: "package.json is the repository's operating interface" }, narrative: { vi: "name và version định danh package; scripts tạo lệnh chuẩn cho dev/CI; type quyết định cách Node diễn giải .js; engines công bố runtime được hỗ trợ. Với package phát hành, exports kiểm soát entry point công khai tốt hơn để consumer không phụ thuộc file nội bộ.", en: "name and version identify a package; scripts standardise dev and CI commands; type controls how Node interprets .js; engines declares supported runtimes. For published packages, exports protects public entry points so consumers do not depend on internals." }, beats: [{ vi: "Script nên ghép lệnh nhỏ, có tên theo mục đích.", en: "Scripts should compose small purpose-named commands." }, { vi: "Không lưu secret trong manifest hoặc npm script.", en: "Never store secrets in manifests or npm scripts." }, { vi: "files/exports giúp giới hạn thứ được publish.", en: "files/exports constrain what gets published." }], code: { language: "json", value: "{\n  \"type\": \"module\",\n  \"scripts\": {\n    \"check\": \"npm run lint && npm test\"\n  },\n  \"engines\": { \"node\": \">=20\" }\n}" } },
      { marker: { vi: "PANEL 02 · SEMVER", en: "PANEL 02 · SEMVER" }, title: { vi: "Range là chính sách cập nhật, không phải phiên bản", en: "A range is an update policy, not an installed version" }, narrative: { vi: "Trong SemVer, MAJOR đổi không tương thích, MINOR thêm chức năng tương thích và PATCH sửa lỗi. ^1.4.2 thường cho phép bản dưới 2.0.0; ~1.4.2 thường dừng trước 1.5.0. Với 0.x, caret hẹp hơn vì API chưa ổn định. Phiên bản thực tế phải đọc trong lockfile.", en: "In SemVer, MAJOR is incompatible change, MINOR adds compatible features, and PATCH fixes defects. ^1.4.2 normally stays below 2.0.0; ~1.4.2 stays below 1.5.0. Caret is narrower for 0.x because the API is unstable. The installed version belongs in the lockfile." }, beats: [{ vi: "Exact pin giảm cập nhật tự động nhưng tăng việc bảo trì.", en: "Exact pins reduce automatic movement but increase maintenance." }, { vi: "Range rộng cần CI và lịch cập nhật dependency.", en: "Broad ranges need CI and an update cadence." }, { vi: "Peer dependency mô tả host tương thích, không phải bản sao riêng.", en: "A peer dependency describes a compatible host, not a private copy." }] },
      { marker: { vi: "PANEL 03 · HAI LOẠI DEPENDENCY", en: "PANEL 03 · DEPENDENCY CLASSES" }, title: { vi: "Production cần dependencies; công cụ build/test thuộc devDependencies", en: "Runtime code needs dependencies; build and test tools belong in devDependencies" }, narrative: { vi: "dependencies phải có khi ứng dụng chạy production. devDependencies phục vụ phát triển, kiểm thử và build. optionalDependencies cho phép cài thất bại; peerDependencies yêu cầu consumer cung cấp host tương thích. Phân loại sai có thể làm image production thiếu package hoặc phình không cần thiết.", en: "dependencies are required when the application runs. devDependencies support development, testing, and builds. optionalDependencies may fail to install; peerDependencies ask the consumer for a compatible host. Misclassification can break or bloat a production image." }, beats: [{ vi: "Ứng dụng build trước deploy vẫn cần devDependencies ở build stage.", en: "Apps built before deploy still need devDependencies in the build stage." }, { vi: "Không dùng NODE_ENV để che lỗi phân loại package.", en: "Do not use NODE_ENV to hide package classification mistakes." }, { vi: "Xóa dependency không dùng để giảm attack surface.", en: "Remove unused dependencies to reduce attack surface." }] },
      { marker: { vi: "PANEL 04 · CÀI ĐẶT TIN CẬY", en: "PANEL 04 · REPRODUCIBLE INSTALL" }, title: { vi: "Commit lockfile và dùng npm ci trong automation", en: "Commit the lockfile and use npm ci in automation" }, narrative: { vi: "package-lock.json lưu cây đã resolve cùng integrity để đồng đội và CI tái tạo cùng kết quả. npm ci yêu cầu manifest và lockfile khớp, xóa cây hiện có rồi cài sạch mà không sửa lockfile. Review diff lockfile, chạy audit có đánh giá ngữ cảnh và tránh chạy script từ package không tin cậy.", en: "package-lock.json records the resolved tree and integrity so teammates and CI can reproduce it. npm ci requires manifest and lockfile agreement, removes the existing tree, and installs without rewriting the lockfile. Review lockfile diffs, triage audits in context, and avoid scripts from untrusted packages." }, beats: [{ vi: "npm install để phát triển; npm ci cho CI/deploy sạch.", en: "Use npm install while developing; npm ci for clean CI/deploys." }, { vi: "Audit warning cần đánh giá reachability và bản vá.", en: "Audit findings need reachability and remediation analysis." }, { vi: "Cập nhật theo batch nhỏ để rollback dễ.", en: "Update in small batches for easy rollback." }], code: { language: "sh", value: "npm ci\nnpm run check\nnpm audit --omit=dev\n# Review package.json and package-lock.json together." }, warning: { vi: "Xóa lockfile để “sửa” conflict có thể âm thầm đổi toàn bộ cây dependency.", en: "Deleting a lockfile to 'fix' a conflict can silently replace the entire dependency tree." } },
    ],
    sources: [{ label: "npm Docs — package.json", href: "https://docs.npmjs.com/cli/configuring-npm/package-json" }, { label: "npm Docs — package-lock.json", href: "https://docs.npmjs.com/cli/configuring-npm/package-lock-json" }, { label: "npm Docs — npm ci", href: "https://docs.npmjs.com/cli/commands/npm-ci" }, { label: "SemVer — Specification", href: "https://semver.org/" }],
  },
};
