import type { CreativeGuide } from "./docs-creative-content";

export const platformCreativeGuides: Record<string, CreativeGuide> = {
  "testing-basics": {
    mode: "test-pyramid-lab",
    eyebrow: { vi: "TEST PYRAMID LAB · TỐC ĐỘ ĐỔI LẤY ĐỘ TIN CẬY", en: "TEST PYRAMID LAB · SPEED FOR CONFIDENCE" },
    thesis: { vi: "Một test tốt không chứng minh code đã được chạy; nó tạo ra tín hiệu đủ nhanh, ổn định và sát rủi ro để đội ngũ dám thay đổi phần mềm.", en: "A good test does not prove that code ran; it creates a signal fast, stable, and risk-focused enough for a team to change software confidently." },
    mission: { vi: "Chọn ranh giới test nhỏ nhất vẫn quan sát được hành vi có giá trị, rồi phân bổ unit, integration và end-to-end theo chi phí thất bại thực tế.", en: "Choose the smallest test boundary that still observes valuable behaviour, then allocate unit, integration, and end-to-end coverage according to real failure cost." },
    simulation: { label: { vi: "Danh mục tín hiệu kiểm thử", en: "Test signal portfolio" }, tracks: [
      { name: { vi: "Unit", en: "Unit" }, detail: { vi: "nhanh · cô lập · nhiều trường hợp", en: "fast · isolated · many cases" }, tone: "cool" },
      { name: { vi: "Integration", en: "Integration" }, detail: { vi: "boundary thật · hợp đồng thật", en: "real boundary · real contract" }, tone: "warm" },
      { name: { vi: "E2E", en: "E2E" }, detail: { vi: "luồng sống còn · ít nhưng sâu", en: "critical journeys · few but deep" }, tone: "hot" },
    ] },
    stations: [
      { marker: { vi: "TẦNG 01 · TÍN HIỆU", en: "LAYER 01 · SIGNAL" }, title: { vi: "Test hành vi quan sát được, không đóng băng cách cài đặt", en: "Test observable behaviour without freezing implementation" }, narrative: { vi: "Bắt đầu từ câu hỏi: nếu phần mềm đúng, người gọi nhìn thấy điều gì? Assert đầu ra, state bền vững hoặc side effect tại boundary công khai. Đừng test private method, thứ tự gọi nội bộ hay snapshot lớn chỉ vì chúng dễ đo; chúng khiến refactor vô hại cũng phá test. Một test chỉ đáng giữ khi thất bại của nó chỉ ra một hợp đồng quan trọng đã đổi.", en: "Start with: if the software is correct, what can its caller observe? Assert output, durable state, or a side effect at a public boundary. Avoid private methods, internal call order, and broad snapshots merely because they are easy to measure; they make harmless refactors fail. Keep a test when its failure reveals that an important contract changed." }, beats: [{ vi: "Tên test mô tả tình huống và kết quả, không lặp tên hàm.", en: "Name the scenario and outcome, not the function." }, { vi: "Arrange chỉ dựng dữ liệu cần thiết; Act thường là một hành động.", en: "Arrange only necessary data; Act is usually one action." }, { vi: "Một failure nên dẫn người đọc tới đúng hành vi hỏng.", en: "One failure should point to the broken behaviour." }], code: { language: "js", value: "test('rejects a coupon after its expiry instant', () => {\n  const clock = () => new Date('2026-07-22T10:00:00Z');\n  const result = price(order, expiredCoupon, { clock });\n  assert.equal(result.discount, 0);\n  assert.equal(result.reason, 'coupon_expired');\n});" } },
      { marker: { vi: "TẦNG 02 · RANH GIỚI", en: "LAYER 02 · BOUNDARY" }, title: { vi: "Chọn loại test theo thứ có thể sai", en: "Choose test type by what can fail" }, narrative: { vi: "Unit test phù hợp cho rule, chuyển đổi và state machine có nhiều nhánh. Integration test dùng khi rủi ro nằm ở SQL, serialization, filesystem, queue hoặc HTTP adapter—hãy chạy boundary thật và chỉ giả phần nằm ngoài quyền sở hữu. E2E đi qua UI hoặc API như người dùng cho vài hành trình tạo giá trị hoặc gây thiệt hại lớn. Tên gọi ít quan trọng hơn việc team ghi rõ ranh giới nào là thật.", en: "Use unit tests for rules, transformations, and state machines with many branches. Use integration tests when risk lives in SQL, serialization, filesystems, queues, or HTTP adapters—run the real boundary and replace only systems outside your ownership. E2E tests traverse UI or API like a user for a few high-value or high-loss journeys. Labels matter less than documenting which boundaries are real." }, beats: [{ vi: "Logic sai → unit; wiring sai → integration; hành trình vỡ → E2E.", en: "Wrong logic → unit; wrong wiring → integration; broken journey → E2E." }, { vi: "Không mock database rồi gọi đó là test tích hợp database.", en: "Do not mock the database and call it a database integration test." }, { vi: "Một behavior không cần được lặp nguyên xi ở mọi tầng.", en: "The same behaviour need not be duplicated at every layer." }] },
      { marker: { vi: "TẦNG 03 · ĐỘ ỔN ĐỊNH", en: "LAYER 03 · RELIABILITY" }, title: { vi: "Loại ngẫu nhiên khỏi test, không che lỗi bằng retry", en: "Remove nondeterminism instead of masking it with retries" }, narrative: { vi: "Flaky test phá niềm tin vì cùng một commit cho hai kết quả. Kiểm soát clock, random seed, locale và dữ liệu; chờ điều kiện quan sát được thay vì sleep; cô lập account và namespace khi chạy song song. Retry chỉ thích hợp để thu thập bằng chứng tạm thời, không phải định nghĩa pass. Khi test flake, quarantine có owner và deadline, rồi sửa nguyên nhân race hoặc môi trường.", en: "A flaky test destroys trust because the same commit produces two outcomes. Control clocks, random seeds, locale, and data; wait for observable conditions rather than sleeping; isolate accounts and namespaces in parallel runs. Retries may gather temporary evidence but must not define passing. Quarantine a flaky test with an owner and deadline, then fix the race or environment cause." }, beats: [{ vi: "Dùng locator hướng người dùng thay cho selector DOM dễ vỡ.", en: "Prefer user-facing locators over brittle DOM selectors." }, { vi: "Mỗi test tự tạo và dọn dữ liệu của nó.", en: "Each test owns setup and cleanup." }, { vi: "Theo dõi thời gian, tỉ lệ flake và lỗi bị lọt—not chỉ coverage.", en: "Track duration, flake rate, and escaped defects—not coverage alone." }], warning: { vi: "Coverage cao có thể chỉ nói nhiều dòng đã chạy; nó không chứng minh assertion có giá trị hay rủi ro quan trọng đã được bảo vệ.", en: "High coverage may only show that many lines ran; it does not prove valuable assertions or protected risks." } },
      { marker: { vi: "TẦNG 04 · PIPELINE", en: "LAYER 04 · PIPELINE" }, title: { vi: "Đặt tín hiệu nhanh trước, tín hiệu đắt sau", en: "Put fast signals first and expensive signals later" }, narrative: { vi: "Trên mỗi commit, chạy lint, type check và unit tests song song để phản hồi trong vài phút. Sau đó chạy integration theo phần bị ảnh hưởng; E2E smoke chặn deploy cho luồng đăng nhập, thanh toán hoặc lưu dữ liệu. Suite rộng hơn có thể chạy theo lịch nhưng phải có người xử lý. Khi test fail, log cần giữ input, expected/actual và artifact đủ tái hiện mà không lộ bí mật.", en: "On every commit, run lint, type checks, and unit tests in parallel for feedback within minutes. Then run affected integration tests; E2E smoke tests gate deployment for login, payment, or data persistence journeys. Broader suites may run on a schedule but need an owner. Failure logs should retain inputs, expected versus actual, and reproducible artifacts without exposing secrets." }, beats: [{ vi: "Fail fast cho lỗi rẻ; giữ artifact cho lỗi đắt.", en: "Fail fast on cheap checks; preserve artifacts for expensive failures." }, { vi: "Một test chậm phải mua được confidence mà test rẻ không có.", en: "A slow test must buy confidence that cheaper tests cannot." }, { vi: "Đo thời gian từ commit tới tín hiệu đầu tiên hữu ích.", en: "Measure commit-to-first-useful-signal time." }], code: { language: "text", value: "COMMIT\n  ├─ lint + types + unit       < 2 min\n  ├─ integration by boundary  < 6 min\n  └─ critical E2E smoke       < 10 min\nDEPLOY\n  └─ observe error rate + business outcome" } },
    ],
    sources: [{ label: "Martin Fowler — Practical Test Pyramid", href: "https://martinfowler.com/articles/practical-test-pyramid.html" }, { label: "Playwright — Best practices", href: "https://playwright.dev/docs/best-practices" }, { label: "Node.js — Test runner", href: "https://nodejs.org/api/test.html" }],
  },
  "rest-api-basics": {
    mode: "api-contract-workshop",
    eyebrow: { vi: "API CONTRACT WORKSHOP · LỜI HỨA QUA HTTP", en: "API CONTRACT WORKSHOP · PROMISES OVER HTTP" },
    thesis: { vi: "REST API dễ dùng khi URI gọi tên tài nguyên, HTTP diễn đạt ý định và mọi response cho client đủ dữ kiện để quyết định bước tiếp theo.", en: "A REST API is easy to use when URIs name resources, HTTP expresses intent, and every response gives clients enough information for the next decision." },
    mission: { vi: "Thiết kế một hợp đồng có resource rõ, method đúng ngữ nghĩa, lỗi có cấu trúc và khả năng tiến hóa mà không buộc client đoán.", en: "Design a contract with clear resources, semantically correct methods, structured errors, and room to evolve without making clients guess." },
    simulation: { label: { vi: "Bàn mổ một request", en: "Request dissection table" }, tracks: [
      { name: { vi: "Ý định", en: "Intent" }, detail: { vi: "method + target", en: "method + target" }, tone: "cool" },
      { name: { vi: "Hợp đồng", en: "Contract" }, detail: { vi: "headers + representation", en: "headers + representation" }, tone: "warm" },
      { name: { vi: "Kết quả", en: "Outcome" }, detail: { vi: "status + next action", en: "status + next action" }, tone: "hot" },
    ] },
    stations: [
      { marker: { vi: "BẢN VẼ 01 · RESOURCE", en: "BLUEPRINT 01 · RESOURCE" }, title: { vi: "URI gọi tên danh từ; method mang động từ", en: "URIs name nouns; methods carry verbs" }, narrative: { vi: "Thiết kế từ domain: /orders/{id}, /users/{id}/sessions, không phải /createOrder. Collection và member cần hành vi nhất quán. GET đọc và phải an toàn; PUT thay thế trạng thái tại URI đã biết và có tính idempotent; PATCH cập nhật một phần theo media type đã định; POST tạo subordinate resource hoặc kích hoạt xử lý không khớp method khác; DELETE yêu cầu trạng thái mục tiêu không còn tồn tại dù gọi lặp.", en: "Design from the domain: /orders/{id}, /users/{id}/sessions, not /createOrder. Collections and members need consistent behaviour. GET reads and is safe; PUT replaces state at a known URI and is idempotent; PATCH performs a partial update under a defined media type; POST creates a subordinate resource or starts processing that fits no other method; repeated DELETE targets the same absent end state." }, beats: [{ vi: "Filter, sort và pagination là query; identity nằm trong path.", en: "Filtering, sorting, and pagination belong in queries; identity belongs in paths." }, { vi: "Không nhầm idempotent với response luôn giống nhau.", en: "Do not confuse idempotency with identical responses." }, { vi: "Tên resource phải dùng ngôn ngữ domain ổn định.", en: "Resource names should use stable domain language." }] },
      { marker: { vi: "BẢN VẼ 02 · RESPONSE", en: "BLUEPRINT 02 · RESPONSE" }, title: { vi: "Status code là quyết định máy đọc được", en: "A status code is a machine-readable decision" }, narrative: { vi: "Dùng 200 khi trả representation thành công, 201 khi resource được tạo kèm Location, 202 khi mới nhận xử lý và cung cấp nơi theo dõi, 204 khi thật sự không có body. Phân biệt 400 malformed, 401 thiếu credentials hợp lệ, 403 đã biết danh tính nhưng không được phép, 404 không có hoặc chủ động che resource, 409 xung đột state và 422 representation đúng cú pháp nhưng không xử lý được. 500 dành cho lỗi bất ngờ của server, không bọc mọi lỗi business.", en: "Use 200 for a successful representation, 201 when creating a resource with Location, 202 when work is only accepted and a monitor is provided, and 204 when there is truly no body. Distinguish malformed 400, invalid or missing credentials 401, known-but-forbidden 403, absent or intentionally hidden 404, state conflict 409, and syntactically valid but unprocessable 422. Reserve 500 for unexpected server failure rather than every business rejection." }, beats: [{ vi: "Client phải quyết định retry, sửa input hay dừng chỉ từ contract.", en: "The contract should let clients retry, fix input, or stop." }, { vi: "204 và 304 không mang response content.", en: "204 and 304 do not carry response content." }, { vi: "Trả header Allow cho 405 Method Not Allowed.", en: "Return Allow with 405 Method Not Allowed." }], code: { language: "http", value: "HTTP/1.1 201 Created\nLocation: /orders/ord_8421\nContent-Type: application/json\n\n{\n  \"id\": \"ord_8421\",\n  \"status\": \"pending\",\n  \"links\": { \"self\": \"/orders/ord_8421\" }\n}" } },
      { marker: { vi: "BẢN VẼ 03 · FAILURE", en: "BLUEPRINT 03 · FAILURE" }, title: { vi: "Lỗi cũng là một phần của hợp đồng", en: "Errors are part of the contract" }, narrative: { vi: "Một body lỗi ổn định cần type hoặc code cho máy, title ngắn, detail an toàn cho người, instance/correlation id để điều tra và danh sách field errors khi validation. Không trả stack trace, SQL hay quy tắc nội bộ nhạy cảm. Giữ cùng schema cho các status để client chỉ cần một parser; document khả năng retry và dùng Retry-After khi phù hợp.", en: "A stable error body needs a machine-readable type or code, a short title, safe human detail, an instance or correlation id for investigation, and field errors for validation. Never expose stack traces, SQL, or sensitive internal rules. Keep one schema across statuses so clients need one parser; document retryability and use Retry-After where appropriate." }, beats: [{ vi: "Thông điệp người dùng có thể dịch; code lỗi phải ổn định.", en: "Human messages may be localized; error codes must stay stable." }, { vi: "Correlation id nối client failure với server trace.", en: "A correlation id connects client failure to server traces." }, { vi: "Không tiết lộ account có tồn tại trong lỗi đăng nhập.", en: "Do not reveal account existence in login errors." }], code: { language: "json", value: "{\n  \"type\": \"https://api.example.dev/problems/invalid-order\",\n  \"title\": \"Order cannot be submitted\",\n  \"status\": 422,\n  \"code\": \"ORDER_TOTAL_INVALID\",\n  \"instance\": \"req_7f12\",\n  \"errors\": [{ \"field\": \"items\", \"code\": \"EMPTY\" }]\n}" } },
      { marker: { vi: "BẢN VẼ 04 · EVOLUTION", en: "BLUEPRINT 04 · EVOLUTION" }, title: { vi: "Tiến hóa bằng tương thích, điều kiện và quan sát", en: "Evolve through compatibility, conditions, and observation" }, narrative: { vi: "Ưu tiên thay đổi cộng thêm: field mới là optional, client bỏ qua field chưa biết và server chấp nhận version cũ trong cửa sổ chuyển đổi. Chỉ version khi ngữ nghĩa không thể tương thích. Dùng cursor pagination cho tập biến động, ETag/If-Match để tránh lost update và idempotency key cho POST có nguy cơ gửi lặp. Contract tests kiểm tra schema lẫn semantic; metrics theo endpoint, status, latency và retry để phát hiện client đang đau ở đâu.", en: "Prefer additive change: new fields are optional, clients ignore unknown fields, and servers accept older forms during migration. Version only when semantics cannot remain compatible. Use cursor pagination for changing sets, ETag with If-Match to prevent lost updates, and idempotency keys for retry-prone POSTs. Contract tests verify schema and semantics; metrics by endpoint, status, latency, and retry reveal client pain." }, beats: [{ vi: "Deprecation cần deadline, usage telemetry và đường thay thế.", en: "Deprecation needs a deadline, usage telemetry, and replacement path." }, { vi: "OpenAPI mô tả contract nhưng không tự tạo ra thiết kế tốt.", en: "OpenAPI describes a contract but does not create a good design." }, { vi: "Rate-limit response phải nói khi nào thử lại.", en: "Rate-limit responses should say when to retry." }], warning: { vi: "REST không đồng nghĩa CRUD máy móc. Hãy giữ ngữ nghĩa HTTP rõ ràng nhưng mô hình resource theo hành vi thật của domain.", en: "REST does not mean mechanical CRUD. Preserve HTTP semantics while modelling resources around real domain behaviour." } },
    ],
    sources: [{ label: "IETF — RFC 9110 HTTP Semantics", href: "https://www.rfc-editor.org/rfc/rfc9110" }, { label: "Roy Fielding — REST", href: "https://roy.gbiv.com/pubs/dissertation/rest_arch_style.htm" }, { label: "IETF — RFC 9457 Problem Details", href: "https://www.rfc-editor.org/rfc/rfc9457" }],
  },
  "authentication-basics": {
    mode: "access-control-matrix",
    eyebrow: { vi: "ACCESS CONTROL MATRIX · SUBJECT × ACTION × RESOURCE", en: "ACCESS CONTROL MATRIX · SUBJECT × ACTION × RESOURCE" },
    thesis: { vi: "Authentication trả lời bạn là ai; session giữ bằng chứng đó; authorization phải quyết định lại trên server rằng danh tính ấy được làm gì với đúng tài nguyên này.", en: "Authentication answers who you are; a session carries that evidence; authorization must decide again on the server what that identity may do to this exact resource." },
    mission: { vi: "Thiết kế luồng đăng nhập, session và phân quyền theo deny-by-default, least privilege và kiểm tra quyền trên mọi request nhạy cảm.", en: "Design login, session, and authorization around deny by default, least privilege, and permission checks on every sensitive request." },
    simulation: { label: { vi: "Ma trận quyết định truy cập", en: "Access decision matrix" }, tracks: [
      { name: { vi: "Subject", en: "Subject" }, detail: { vi: "user · service · device", en: "user · service · device" }, tone: "cool" },
      { name: { vi: "Action", en: "Action" }, detail: { vi: "read · edit · approve", en: "read · edit · approve" }, tone: "warm" },
      { name: { vi: "Resource + context", en: "Resource + context" }, detail: { vi: "owner · tenant · state", en: "owner · tenant · state" }, tone: "hot" },
    ] },
    stations: [
      { marker: { vi: "Ô 01 · DANH TÍNH", en: "CELL 01 · IDENTITY" }, title: { vi: "Đăng nhập xác minh bằng chứng, không cấp toàn bộ quyền", en: "Login verifies evidence; it does not grant every permission" }, narrative: { vi: "Identifier và authenticator là hai thứ khác nhau. Mật khẩu cần hash bằng thuật toán thích ứng với cost phù hợp; MFA giảm rủi ro khi một yếu tố bị lộ; OAuth/OIDC dùng cho ủy quyền và liên kết danh tính, không phải tự chế token exchange. Thông báo lỗi đăng nhập nên thống nhất để tránh dò account, đồng thời rate limit và quan sát credential stuffing. Re-authenticate trước thao tác rủi ro hoặc sau sự kiện đáng ngờ.", en: "Identifiers and authenticators are different. Passwords need adaptive hashing with an appropriate cost; MFA reduces risk when one factor leaks; OAuth and OIDC support delegated access and identity rather than home-grown token exchange. Login failures should be generic to resist account enumeration, while rate limits and monitoring address credential stuffing. Re-authenticate before risky actions or after suspicious events." }, beats: [{ vi: "Không lưu mật khẩu bằng mã hóa có thể giải ngược.", en: "Never store passwords with reversible encryption." }, { vi: "Recovery là một luồng authentication và phải mạnh tương xứng.", en: "Recovery is an authentication flow and must be comparably strong." }, { vi: "MFA ưu tiên yếu tố chống phishing khi threat model yêu cầu.", en: "Prefer phishing-resistant MFA when the threat model requires it." }] },
      { marker: { vi: "Ô 02 · SESSION", en: "CELL 02 · SESSION" }, title: { vi: "Session id là bí mật đại diện cho người dùng", en: "A session id is a bearer secret representing the user" }, narrative: { vi: "Sau đăng nhập, server phát session id ngẫu nhiên đủ mạnh và chỉ lưu ý nghĩa ở server; rotate id khi privilege thay đổi để chống fixation. Với cookie, dùng Secure, HttpOnly và SameSite phù hợp, scope Domain/Path hẹp, timeout idle lẫn absolute và hủy session phía server khi logout. Token tự chứa giảm lookup nhưng làm revoke, thay đổi quyền và phát hiện replay khó hơn—đừng chọn chỉ vì 'stateless'.", en: "After login, issue a strong random session id and keep its meaning server-side; rotate it when privilege changes to prevent fixation. For cookies, use Secure, HttpOnly, an appropriate SameSite setting, narrow Domain and Path scopes, idle and absolute timeouts, and server-side invalidation on logout. Self-contained tokens reduce lookups but complicate revocation, permission changes, and replay detection—do not choose them merely for being stateless." }, beats: [{ vi: "Không đặt access token trong localStorage nếu cookie an toàn đáp ứng mô hình.", en: "Avoid localStorage access tokens when secure cookies fit the model." }, { vi: "Logout mọi thiết bị cần inventory hoặc version session phía server.", en: "Global logout needs server-side session inventory or versioning." }, { vi: "CSRF và XSS là rủi ro khác nhau; SameSite không sửa XSS.", en: "CSRF and XSS are different risks; SameSite does not fix XSS." }], code: { language: "http", value: "Set-Cookie: __Host-session=<opaque>; Path=/; Secure; HttpOnly; SameSite=Lax\nCache-Control: no-store\n\n# Rotate after login, MFA, password change, or role elevation.\n# Revoke server-side on logout and suspicious activity." } },
      { marker: { vi: "Ô 03 · QUYẾT ĐỊNH", en: "CELL 03 · DECISION" }, title: { vi: "Kiểm tra quyền trên object thật, trong mọi request", en: "Authorize against the real object on every request" }, narrative: { vi: "Deny by default, rồi cấp quyền tối thiểu theo subject, action, resource và context. RBAC phù hợp vai trò ổn định; ABAC thêm thuộc tính như tenant, ownership, trạng thái và thời gian; relationship-based rules diễn đạt thành viên hoặc người sở hữu. Dù UI đã ẩn nút, API vẫn phải load resource và kiểm tra policy—đừng tin userId, tenantId hay role do client gửi. Đặt policy tập trung nhưng quyết định gần boundary truy cập dữ liệu.", en: "Deny by default, then grant least privilege based on subject, action, resource, and context. RBAC fits stable roles; ABAC adds tenant, ownership, state, and time; relationship-based rules express membership or ownership. Even when UI hides a button, the API must load the resource and evaluate policy—never trust a client-supplied userId, tenantId, or role. Centralize policy while enforcing it near the data-access boundary." }, beats: [{ vi: "Kiểm tra object-level permission để chặn IDOR/BOLA.", en: "Check object-level permission to prevent IDOR/BOLA." }, { vi: "Admin cũng chỉ có quyền trong đúng scope được giao.", en: "Admins still operate within an assigned scope." }, { vi: "Cache quyết định quyền phải invalidation khi policy đổi.", en: "Cached decisions need invalidation when policy changes." }], code: { language: "ts", value: "const invoice = await invoices.findById(params.id);\nif (!invoice) return notFound();\n\nconst allowed = policy.can(actor, 'invoice:approve', {\n  ownerId: invoice.ownerId,\n  tenantId: invoice.tenantId,\n  status: invoice.status,\n});\nif (!allowed) return forbidden();\nreturn invoices.approve(invoice.id, actor.id);" } },
      { marker: { vi: "Ô 04 · VÒNG ĐỜI", en: "CELL 04 · LIFECYCLE" }, title: { vi: "Quyền thay đổi theo thời gian; audit phải kể lại được quyết định", en: "Privileges change over time; audit must reconstruct decisions" }, narrative: { vi: "Provision quyền theo yêu cầu đã duyệt, tự hết hạn cho quyền tạm và thu hồi ngay khi người dùng rời nhóm hoặc tenant. Với thao tác nhạy cảm, log actor, action, resource, decision, policy version và correlation id—không log secret/token. Test ma trận cả allow lẫn deny, cross-tenant, object khác owner và state không hợp lệ. Theo dõi spike 401/403, session bất thường và thay đổi role để phát hiện lạm dụng.", en: "Provision access through approved requests, expire temporary grants, and revoke promptly when users leave a group or tenant. For sensitive operations, log actor, action, resource, decision, policy version, and correlation id—never secrets or tokens. Test both allow and deny cells, cross-tenant access, non-owner objects, and invalid states. Monitor 401/403 spikes, unusual sessions, and role changes for abuse." }, beats: [{ vi: "Authorization test cần bắt đầu từ deny cases.", en: "Authorization tests should begin with deny cases." }, { vi: "Audit log cần chống sửa và có chính sách lưu giữ.", en: "Audit logs need tamper resistance and retention policy." }, { vi: "Review định kỳ quyền tích lũy và service accounts.", en: "Periodically review accumulated privileges and service accounts." }], warning: { vi: "JWT hợp lệ chỉ chứng minh chữ ký và claims chưa hết hạn; nó không tự chứng minh quyền vẫn còn đúng ở thời điểm request.", en: "A valid JWT proves its signature and current claims; it does not by itself prove that access is still appropriate at request time." } },
    ],
    sources: [{ label: "OWASP — Authentication Cheat Sheet", href: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html" }, { label: "OWASP — Authorization Cheat Sheet", href: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html" }, { label: "OWASP — Session Management Cheat Sheet", href: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" }],
  },
};
