import { nextCreativeGuides } from "./docs-next-creative-content.ts";
import { workflowCreativeGuides } from "./docs-workflow-creative-content.ts";
import { qualityCreativeGuides } from "./docs-quality-creative-content.ts";
import { platformCreativeGuides } from "./docs-platform-creative-content.ts";

export type CreativeLanguage = "vi" | "en";
type L = Record<CreativeLanguage, string>;
type Source = { label: string; href: string };
type Station = { marker: L; title: L; narrative: L; beats: L[]; code?: { language: string; value: string }; warning?: L };
export type CreativeGuide = {
  mode: "frame-lab" | "event-scene" | "async-control-room" | "incident-desk" | "module-graph" | "package-console" | "config-vault" | "git-workbench" | "history-ledger" | "review-room" | "change-budget" | "debug-lab" | "test-pyramid-lab" | "api-contract-workshop" | "access-control-matrix";
  eyebrow: L;
  thesis: L;
  mission: L;
  simulation: { label: L; tracks: Array<{ name: L; detail: L; tone: "cool" | "warm" | "hot" }> };
  stations: Station[];
  sources: Source[];
};

export const creativeGuides: Record<string, CreativeGuide> = {
  "browser-rendering": {
    mode: "frame-lab",
    eyebrow: { vi: "FRAME LAB · 16,7 MILLI-GIÂY", en: "FRAME LAB · 16.7 MILLISECONDS" },
    thesis: { vi: "Browser không 'vẽ lại trang'. Nó cố hoàn thành đúng phần việc cần thiết trước nhịp màn hình kế tiếp.", en: "The browser does not simply 'redraw the page'. It tries to finish only the necessary work before the next display refresh." },
    mission: { vi: "Nhiệm vụ: theo dấu một thay đổi UI từ JavaScript đến pixel và tìm bước nào làm rơi frame.", en: "Mission: follow one UI mutation from JavaScript to pixels and find the stage that drops the frame." },
    simulation: { label: { vi: "Bản ghi của một frame", en: "One frame recording" }, tracks: [
      { name: { vi: "JavaScript", en: "JavaScript" }, detail: { vi: "4,2ms · cập nhật DOM", en: "4.2ms · DOM mutation" }, tone: "cool" },
      { name: { vi: "Style", en: "Style" }, detail: { vi: "1,8ms · selector → computed style", en: "1.8ms · selectors → computed styles" }, tone: "cool" },
      { name: { vi: "Layout", en: "Layout" }, detail: { vi: "7,4ms · tính lại hình học", en: "7.4ms · geometry recalculation" }, tone: "hot" },
      { name: { vi: "Paint", en: "Paint" }, detail: { vi: "2,1ms · tạo display list", en: "2.1ms · build display list" }, tone: "warm" },
      { name: { vi: "Composite", en: "Composite" }, detail: { vi: "1,2ms · ghép layer", en: "1.2ms · combine layers" }, tone: "cool" },
    ] },
    stations: [
      { marker: { vi: "01 · NHẬP XƯỞNG", en: "01 · INTAKE" }, title: { vi: "DOM và CSSOM chưa phải là pixel", en: "DOM and CSSOM are not pixels" }, narrative: { vi: "HTML tạo DOM, CSS tạo CSSOM. Browser kết hợp node nhìn thấy với computed style để hình thành cấu trúc phục vụ render. display:none bị loại khỏi render tree; visibility:hidden vẫn chiếm hình học. JavaScript có thể chặn parser hoặc thay đổi hai cây trước lần paint đầu.", en: "HTML creates the DOM and CSS creates the CSSOM. The browser combines visible nodes with computed styles into render data. display:none leaves the render tree; visibility:hidden still occupies geometry. JavaScript can block parsing or mutate both trees before first paint." }, beats: [{ vi: "DOM trả lời: có nội dung gì?", en: "DOM: what content exists?" }, { vi: "CSSOM trả lời: rule nào áp dụng?", en: "CSSOM: which rules apply?" }, { vi: "Render data trả lời: thứ gì thật sự cần vẽ?", en: "Render data: what must be drawn?" }] },
      { marker: { vi: "02 · BA LÀN CHI PHÍ", en: "02 · THREE COST LANES" }, title: { vi: "Không phải CSS property nào cũng trả cùng một hóa đơn", en: "CSS properties do not send the same bill" }, narrative: { vi: "Đổi width có thể kéo theo style → layout → paint → composite. Đổi color thường bỏ qua layout. transform và opacity thường có thể đi thẳng tới composite nếu layer phù hợp. 'Nhanh' không có nghĩa tạo layer cho mọi thứ: layer cũng tốn bộ nhớ và thời gian quản lý.", en: "Changing width may trigger style → layout → paint → composite. Color often skips layout. Transform and opacity can often reach compositing directly when layering permits. Fast does not mean promoting everything: layers also cost memory and management." }, beats: [{ vi: "Geometry: width, height, top — dễ kích layout.", en: "Geometry: width, height, top — likely layout." }, { vi: "Visual: color, shadow — thường paint.", en: "Visual: color, shadow — often paint." }, { vi: "Composition: transform, opacity — có thể composite-only.", en: "Composition: transform, opacity — may be composite-only." }], code: { language: "css", value: ".card { transition: transform 180ms, opacity 180ms; }\n.card:hover { transform: translateY(-4px); }\n/* Measure first: compositor-only is an opportunity, not a guarantee. */" } },
      { marker: { vi: "03 · HIỆN TRƯỜNG", en: "03 · INCIDENT" }, title: { vi: "Layout thrashing: đọc và ghi xen kẽ", en: "Layout thrashing: interleaved reads and writes" }, narrative: { vi: "Sau khi ghi style, việc đọc offsetHeight có thể ép browser hoàn tất style/layout ngay để trả số chính xác. Lặp read → write trong loop biến một lần layout thành nhiều lần. Gom tất cả phép đọc trước, tính toán trong bộ nhớ, rồi ghi DOM trong một lượt requestAnimationFrame.", en: "After a style write, reading offsetHeight may force style and layout immediately to return an accurate number. Repeating read → write turns one layout into many. Batch reads first, compute in memory, then write once in requestAnimationFrame." }, beats: [{ vi: "Đo bằng Performance, không đoán bằng mắt.", en: "Measure in Performance; do not guess visually." }, { vi: "Tìm Forced reflow và Long task.", en: "Look for Forced reflow and Long task." }, { vi: "Giảm phạm vi DOM bị ảnh hưởng trước khi micro-optimize.", en: "Reduce affected DOM scope before micro-optimising." }], code: { language: "js", value: "const widths = cards.map(card => card.getBoundingClientRect().width);\nrequestAnimationFrame(() => {\n  cards.forEach((card, i) => { card.style.setProperty('--w', `${widths[i]}px`); });\n});" }, warning: { vi: "requestAnimationFrame không làm code rẻ hơn; nó chỉ đặt phần ghi đúng gần nhịp render.", en: "requestAnimationFrame does not make work cheaper; it schedules writes near rendering." } },
      { marker: { vi: "04 · BÀN GIAO", en: "04 · HANDOFF" }, title: { vi: "Quy trình điều tra một frame rơi", en: "A dropped-frame investigation" }, narrative: { vi: "Ghi lại thao tác thật, tìm frame vượt budget, mở Main thread và xác định chi phí thuộc script, layout hay paint. Tạo một giả thuyết, thay đúng một yếu tố rồi đo lại. Chỉ tối ưu nơi trace cho thấy người dùng đang chờ.", en: "Record a real interaction, find frames over budget, inspect the Main thread, and classify cost as script, layout, or paint. Form one hypothesis, change one variable, and measure again. Optimise only where the trace shows user-visible waiting." }, beats: [{ vi: "Record → isolate → classify", en: "Record → isolate → classify" }, { vi: "Hypothesis → one change → remeasure", en: "Hypothesis → one change → remeasure" }, { vi: "So sánh thiết bị yếu, không chỉ máy dev", en: "Compare on slower hardware, not only a dev machine" }] },
    ],
    sources: [{ label: "web.dev — Rendering performance", href: "https://web.dev/articles/rendering-performance" }, { label: "web.dev — Critical rendering path", href: "https://web.dev/learn/performance/understanding-the-critical-path" }, { label: "MDN — How browsers work", href: "https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/How_browsers_work" }],
  },
  "dom-events": {
    mode: "event-scene",
    eyebrow: { vi: "EVENT CRIME SCENE · CLICK #A17", en: "EVENT CRIME SCENE · CLICK #A17" },
    thesis: { vi: "Một event không thuộc riêng phần tử được click; nó mang theo một đường đi, nhiều listener và có thể cả hành vi mặc định của browser.", en: "An event does not belong only to the clicked element; it carries a path, multiple listeners, and possibly a browser default action." },
    mission: { vi: "Nhiệm vụ: dựng lại đường đi của click và quyết định chính xác nơi nên nghe, chặn hay ủy quyền.", en: "Mission: reconstruct a click path and decide exactly where to listen, cancel, or delegate." },
    simulation: { label: { vi: "Dấu vết propagation", en: "Propagation evidence" }, tracks: [
      { name: { vi: "Capture", en: "Capture" }, detail: { vi: "window → document → list", en: "window → document → list" }, tone: "cool" },
      { name: { vi: "Target", en: "Target" }, detail: { vi: "button[data-action=remove]", en: "button[data-action=remove]" }, tone: "hot" },
      { name: { vi: "Bubble", en: "Bubble" }, detail: { vi: "list → document → window", en: "list → document → window" }, tone: "warm" },
    ] },
    stations: [
      { marker: { vi: "HỒ SƠ A · ĐƯỜNG ĐI", en: "FILE A · PATH" }, title: { vi: "target đứng yên, currentTarget di chuyển", en: "target stays; currentTarget moves" }, narrative: { vi: "target là node gốc nhận event; currentTarget là node có listener đang chạy. Event đi capture từ ngoài vào, chạy ở target rồi bubble ra nếu bubbles=true. composedPath() cho thấy đường gọi listener và đặc biệt hữu ích khi Shadow DOM retarget event.", en: "target is the original receiving node; currentTarget is the node whose listener is running. The event captures inward, runs at target, then bubbles when bubbles=true. composedPath() reveals the listener path and matters when Shadow DOM retargets events." }, beats: [{ vi: "eventPhase cho biết capture, target hay bubble.", en: "eventPhase identifies capture, target, or bubble." }, { vi: "Không phải event nào cũng bubble.", en: "Not every event bubbles." }, { vi: "Shadow boundary có thể đổi target quan sát được.", en: "A shadow boundary can retarget what observers see." }] },
      { marker: { vi: "HỒ SƠ B · BA NÚT KHẨN CẤP", en: "FILE B · THREE EMERGENCY BUTTONS" }, title: { vi: "Ba API, ba hậu quả khác nhau", en: "Three APIs, three different consequences" }, narrative: { vi: "preventDefault hủy hành vi mặc định khi event cancelable; stopPropagation dừng đường đi tiếp nhưng không dừng listener khác trên cùng node; stopImmediatePropagation dừng cả listener còn lại trên node. Dùng chúng như công cụ cuối cùng vì chặn propagation rộng làm analytics, shortcut và component cha khó quan sát.", en: "preventDefault cancels a cancelable default action; stopPropagation stops further traversal but not sibling listeners on the same node; stopImmediatePropagation stops both. Treat them as last-resort tools because broad propagation stops break analytics, shortcuts, and parent components." }, beats: [{ vi: "Link vẫn điều hướng sau stopPropagation.", en: "A link still navigates after stopPropagation." }, { vi: "preventDefault không dừng bubble.", en: "preventDefault does not stop bubbling." }, { vi: "Kiểm tra event.cancelable trước khi kỳ vọng hủy.", en: "Check event.cancelable before expecting cancellation." }] },
      { marker: { vi: "HỒ SƠ C · ỦY QUYỀN", en: "FILE C · DELEGATION" }, title: { vi: "Một listener quản lý danh sách động", en: "One listener manages a dynamic list" }, narrative: { vi: "Đặt listener trên container, tìm ancestor hợp lệ bằng closest rồi xác nhận nó nằm trong container. Cách này dùng bubbling để xử lý cả item thêm sau này và giảm listener. Nhưng delegation không phù hợp khi event không bubble hoặc boundary component cần cô lập rõ.", en: "Listen on a container, find the intended ancestor with closest, then confirm it belongs to the container. This uses bubbling to handle future items and reduce listeners. Delegation is less suitable for non-bubbling events or strongly isolated component boundaries." }, beats: [{ vi: "Phân loại action bằng data-* thay vì đọc text.", en: "Classify actions with data-* rather than text." }, { vi: "Dùng AbortSignal để tháo listener theo lifecycle.", en: "Use AbortSignal to remove listeners by lifecycle." }, { vi: "Tránh listener document nếu container đủ scope.", en: "Avoid document listeners when a container is sufficient." }], code: { language: "js", value: "list.addEventListener('click', event => {\n  const button = event.target.closest('button[data-action]');\n  if (!button || !list.contains(button)) return;\n  actions[button.dataset.action]?.(button.dataset.id);\n}, { signal: controller.signal });" } },
      { marker: { vi: "HỒ SƠ D · TÁI HIỆN", en: "FILE D · RECONSTRUCTION" }, title: { vi: "Debug event bằng bằng chứng, không thêm stopPropagation", en: "Debug events with evidence, not more stopPropagation" }, narrative: { vi: "Log type, phase, target, currentTarget, defaultPrevented và composedPath. Kiểm tra listener trong DevTools, đặt breakpoint Event Listener rồi tái hiện đúng input. Nếu handler chạy hai lần, tìm việc đăng ký lặp hoặc lifecycle cleanup thiếu trước khi chặn đường truyền.", en: "Log type, phase, target, currentTarget, defaultPrevented, and composedPath. Inspect listeners, set an Event Listener breakpoint, and reproduce the exact input. If a handler runs twice, find duplicate registration or missing cleanup before blocking propagation." }, beats: [{ vi: "Đường đi sai? kiểm tra DOM/Shadow DOM.", en: "Wrong path? inspect DOM/Shadow DOM." }, { vi: "Handler lặp? kiểm tra registration/cleanup.", en: "Repeated handler? inspect registration/cleanup." }, { vi: "Browser vẫn hành động? kiểm tra default action.", en: "Browser still acts? inspect the default action." }] },
    ],
    sources: [{ label: "WHATWG — DOM event dispatch", href: "https://dom.spec.whatwg.org/#concept-event-dispatch" }, { label: "MDN — Event bubbling", href: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Event_bubbling" }, { label: "MDN — Event API", href: "https://developer.mozilla.org/en-US/docs/Web/API/Event" }],
  },
  "promises-async": {
    mode: "async-control-room",
    eyebrow: { vi: "ASYNC CONTROL ROOM · LUỒNG ĐANG CHẠY", en: "ASYNC CONTROL ROOM · LIVE WORKFLOW" },
    thesis: { vi: "Promise không phải dữ liệu tương lai; nó là giao diện quan sát một công việc đã settle hoặc sẽ settle đúng một lần.", en: "A Promise is not future data; it is an interface to work that has settled or will settle exactly once." },
    mission: { vi: "Nhiệm vụ: vẽ dependency graph trước, rồi chọn await, Promise.all, allSettled, any và cancellation theo ý nghĩa sản phẩm.", en: "Mission: draw the dependency graph first, then choose await, Promise.all, allSettled, any, and cancellation by product semantics." },
    simulation: { label: { vi: "Dependency graph của màn hình", en: "Screen dependency graph" }, tracks: [
      { name: { vi: "profile", en: "profile" }, detail: { vi: "bắt đầu ngay · bắt buộc", en: "start now · required" }, tone: "hot" },
      { name: { vi: "permissions", en: "permissions" }, detail: { vi: "phụ thuộc profile.id", en: "depends on profile.id" }, tone: "warm" },
      { name: { vi: "recommendations", en: "recommendations" }, detail: { vi: "độc lập · có thể thất bại", en: "independent · optional failure" }, tone: "cool" },
    ] },
    stations: [
      { marker: { vi: "CONSOLE 01 · SETTLEMENT", en: "CONSOLE 01 · SETTLEMENT" }, title: { vi: "Promise có trạng thái; await chỉ tạm dừng một nhánh", en: "Promises have state; await pauses one branch" }, narrative: { vi: "Promise pending chuyển một lần sang fulfilled hoặc rejected. then/catch luôn tạo Promise mới và reaction chạy qua microtask. async function luôn trả Promise; await unwrap giá trị hoặc throw rejection vào async function, nhưng không khóa thread hay dừng công việc độc lập khác.", en: "A pending Promise moves once to fulfilled or rejected. then/catch creates a new Promise and reactions run as microtasks. An async function always returns a Promise; await unwraps a value or throws a rejection into that function, but it does not block the thread or independent work." }, beats: [{ vi: "return trong then trở thành fulfillment kế tiếp.", en: "return in then becomes the next fulfillment." }, { vi: "throw trở thành rejection kế tiếp.", en: "throw becomes the next rejection." }, { vi: "Quên return/await làm đứt chuỗi quan sát.", en: "Missing return/await breaks the observed chain." }] },
      { marker: { vi: "CONSOLE 02 · LẬP LỊCH", en: "CONSOLE 02 · SCHEDULING" }, title: { vi: "Tuần tự hay song song là câu hỏi về dependency", en: "Sequential or concurrent is a dependency question" }, narrative: { vi: "Nếu B cần kết quả A, await tuần tự là đúng. Nếu A và B độc lập, hãy khởi động cùng lúc rồi await Promise.all. allSettled phù hợp khi cần báo cáo từng kết quả; any lấy thành công đầu tiên; race lấy settle đầu tiên và không tự hủy phần còn lại.", en: "If B needs A, sequential await is correct. If A and B are independent, start both and await Promise.all. allSettled reports every outcome; any takes the first fulfillment; race takes the first settlement and does not cancel the rest." }, beats: [{ vi: "all: tất cả bắt buộc, fail-fast.", en: "all: every result required, fail-fast." }, { vi: "allSettled: kết quả riêng lẻ vẫn có giá trị.", en: "allSettled: individual outcomes still matter." }, { vi: "any: cần một nguồn thành công.", en: "any: one successful source is enough." }], code: { language: "js", value: "const profileTask = getProfile();\nconst recommendationsTask = getRecommendations();\nconst profile = await profileTask;\nconst [permissions, recommendations] = await Promise.all([\n  getPermissions(profile.id),\n  recommendationsTask,\n]);" } },
      { marker: { vi: "CONSOLE 03 · FAILURE ROUTING", en: "CONSOLE 03 · FAILURE ROUTING" }, title: { vi: "Catch ở nơi có quyết định phục hồi", en: "Catch where recovery is possible" }, narrative: { vi: "Đừng catch chỉ để console.log rồi trả undefined. Hãy catch tại boundary biết retry, fallback, đổi status hoặc hiển thị lỗi. finally dành cho cleanup không phụ thuộc kết quả. Error cần giữ cause/context nhưng không làm lộ token hay payload nhạy cảm.", en: "Do not catch merely to console.log and return undefined. Catch at a boundary that can retry, fall back, map status, or show an error. finally is for outcome-independent cleanup. Preserve cause and context without leaking tokens or sensitive payloads." }, beats: [{ vi: "Low level: thêm context rồi rethrow.", en: "Low level: add context and rethrow." }, { vi: "Boundary: chuyển lỗi thành quyết định UX/API.", en: "Boundary: map failure to a UX/API decision." }, { vi: "Global handler: telemetry cuối cùng, không phải recovery chính.", en: "Global handler: last-resort telemetry, not primary recovery." }], code: { language: "js", value: "try {\n  return await saveDraft(data, { signal });\n} catch (error) {\n  if (error.name === 'AbortError') return { status: 'cancelled' };\n  throw new Error('Could not save draft', { cause: error });\n} finally {\n  releasePendingState();\n}" } },
      { marker: { vi: "CONSOLE 04 · LIFECYCLE", en: "CONSOLE 04 · LIFECYCLE" }, title: { vi: "Promise không có cancel; operation mới có", en: "Promises do not cancel; operations do" }, narrative: { vi: "Promise chỉ báo kết quả. Muốn hủy fetch hoặc API hỗ trợ signal, truyền AbortSignal tới operation và xử lý AbortError như trạng thái riêng. Với UI, hủy request cũ khi query đổi hoặc component rời đi; đồng thời chống stale result vì không phải operation nào cũng hủy được.", en: "A Promise only reports an outcome. To cancel fetch or signal-aware APIs, pass an AbortSignal to the operation and handle AbortError as its own state. In UI, abort stale requests as queries change or components leave, while also guarding stale results because not every operation is cancellable." }, beats: [{ vi: "Timeout nên abort operation, không chỉ race Promise.", en: "A timeout should abort the operation, not only race its Promise." }, { vi: "Giới hạn concurrency khi xử lý danh sách lớn.", en: "Limit concurrency for large batches." }, { vi: "Test fulfilled, rejected, aborted và partial failure.", en: "Test fulfillment, rejection, abort, and partial failure." }], warning: { vi: "Promise.race với timer không dừng fetch thua cuộc; request vẫn tiêu tài nguyên nếu không abort.", en: "Racing a timer does not stop the losing fetch; it still consumes resources unless aborted." } },
    ],
    sources: [{ label: "ECMAScript — Promise and async semantics", href: "https://tc39.es/ecma262/multipage/control-abstraction-objects.html" }, { label: "MDN — Using promises", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises" }, { label: "MDN — Promise concurrency", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise" }],
  },
  ...nextCreativeGuides,
  ...workflowCreativeGuides,
  ...qualityCreativeGuides,
  ...platformCreativeGuides,
};