export type Language = "vi" | "en";
export type Item = { id: string; title: string; description: string; category: string; tags: string[]; status: "live" | "coming-soon"; href: string };
export type Project = Item & { role: string; outcome: string };
export type Content = { profile: { name: string; role: string; summary: string; location: string; values: string[]; skills: { title: string; items: string[] }[] }; projects: Project[]; tools: Item[]; playground: Item[]; posts: Item[] };

export const siteNav = [
  { href: "/about", label: { vi: "Giới thiệu", en: "About" } }, { href: "/projects", label: { vi: "Dự án", en: "Projects" } }, { href: "/tools", label: { vi: "Công cụ", en: "Tools" } }, { href: "/playground", label: { vi: "Góc thử nghiệm", en: "Playground" } }, { href: "/blog", label: { vi: "Bài viết", en: "Blog" } },
] as const;

const baseSkills = [{ title: "Frontend", items: ["React", "Next.js", "TypeScript", "Tailwind CSS"] }, { title: "Backend & Data", items: ["Node.js", "NestJS", "PostgreSQL", "MongoDB"] }, { title: "Product delivery", items: ["UI/UX", "REST API", "Testing", "Deployment"] }, { title: "Interactive", items: ["React Native", "Unity", "PixiJS", "Game design"] }];

export const portfolio: Record<Language, Content> = {
  vi: { profile: { name: "Trần Đình Khánh", role: "Full-stack Developer", location: "Đà Nẵng, Việt Nam", summary: "Tôi xây dựng những sản phẩm số hữu ích, kết hợp kỹ thuật, trải nghiệm người dùng và tư duy sản phẩm.", values: ["Làm rõ vấn đề trước khi viết code", "Ưu tiên trải nghiệm đơn giản và bền vững", "Luôn học qua sản phẩm thật"], skills: baseSkills }, projects: [
    { id: "heritage", title: "Heritage Ginseng", description: "Nền tảng thương mại điện tử đa vai trò với CMS, quản lý sản phẩm và dashboard vận hành.", category: "Web product", tags: ["Next.js", "NestJS", "PostgreSQL"], status: "coming-soon", href: "/projects", role: "Full-stack development", outcome: "Kiến trúc có thể mở rộng cho vận hành nội dung và bán hàng." },
    { id: "commerce", title: "Electronics Commerce", description: "Marketplace cho khách hàng, người bán và quản trị viên, tích hợp thanh toán và OAuth.", category: "Marketplace", tags: ["React", "Express", "MongoDB"], status: "coming-soon", href: "/projects", role: "Frontend & API", outcome: "Làm rõ luồng nghiệp vụ cho ba nhóm người dùng." },
    { id: "booking", title: "Booking Platform", description: "Sản phẩm đặt lịch đa nền tảng cho khách hàng, đối tác và đội ngũ vận hành.", category: "Mobile & dashboard", tags: ["React Native", "Next.js", "Prisma"], status: "coming-soon", href: "/projects", role: "Product engineering", outcome: "Kết nối trải nghiệm đặt lịch và vận hành trong một hệ thống." },
  ], tools: [{ id: "tool-shelf", title: "Tool Shelf", description: "Bộ sưu tập các tiện ích nhỏ giúp công việc số gọn gàng hơn.", category: "Utility", tags: ["Web", "Productivity"], status: "coming-soon", href: "/tools" }], playground: [{ id: "ocean", title: "Ocean Quest", description: "Thử nghiệm puzzle casual về nhịp độ, phản hồi và cảm giác tương tác.", category: "Game experiment", tags: ["Unity", "Game design"], status: "coming-soon", href: "/playground" }], posts: [{ id: "notes", title: "Ghi chú khi xây sản phẩm", description: "Các quyết định kỹ thuật, bài học và tài liệu tôi muốn lưu lại.", category: "Engineering notes", tags: ["Notes", "Docs"], status: "coming-soon", href: "/blog" }] },
  en: { profile: { name: "Tran Dinh Khanh", role: "Full-stack Developer", location: "Da Nang, Vietnam", summary: "I build useful digital products by combining engineering, user experience and product thinking.", values: ["Clarify the problem before writing code", "Prefer simple, durable experiences", "Learn through real products"], skills: baseSkills }, projects: [
    { id: "heritage", title: "Heritage Ginseng", description: "A multi-role commerce platform with CMS, product management and an operations dashboard.", category: "Web product", tags: ["Next.js", "NestJS", "PostgreSQL"], status: "coming-soon", href: "/projects", role: "Full-stack development", outcome: "Architecture designed to grow with content and commerce operations." },
    { id: "commerce", title: "Electronics Commerce", description: "A marketplace for customers, sellers and administrators with payment and OAuth integrations.", category: "Marketplace", tags: ["React", "Express", "MongoDB"], status: "coming-soon", href: "/projects", role: "Frontend & API", outcome: "Clarified workflows across three user groups." },
    { id: "booking", title: "Booking Platform", description: "A multi-platform booking product for customers, partners and operations teams.", category: "Mobile & dashboard", tags: ["React Native", "Next.js", "Prisma"], status: "coming-soon", href: "/projects", role: "Product engineering", outcome: "Connected booking and operations in one system." },
  ], tools: [{ id: "tool-shelf", title: "Tool Shelf", description: "A collection of small utilities that make digital work calmer and clearer.", category: "Utility", tags: ["Web", "Productivity"], status: "coming-soon", href: "/tools" }], playground: [{ id: "ocean", title: "Ocean Quest", description: "A casual puzzle experiment about pace, feedback and interaction.", category: "Game experiment", tags: ["Unity", "Game design"], status: "coming-soon", href: "/playground" }], posts: [{ id: "notes", title: "Notes from building products", description: "Technical choices, lessons and documentation worth keeping.", category: "Engineering notes", tags: ["Notes", "Docs"], status: "coming-soon", href: "/blog" }] },
};
