export type Language = "vi" | "en";
export type Item = { id: string; title: string; description: string; category: string; tags: string[]; status: "live" | "coming-soon"; href: string };
export type Project = Item & { role: string; outcome: string };
export type Content = { profile: { name: string; role: string; summary: string; location: string; values: string[]; skills: { title: string; items: string[] }[] }; projects: Project[]; tools: Item[]; playground: Item[]; posts: Item[] };

export const siteNav = [
  { href: "/", label: { vi: "Trang chủ", en: "Home" } },
  { href: "/projects", label: { vi: "Dự án", en: "Projects" } },
  { href: "/tools", label: { vi: "Công cụ", en: "Tools" } },
  { href: "/playground", label: { vi: "Trò chơi", en: "Games" } },
  { href: "/blog", label: { vi: "Bài viết", en: "Blog" } },
  { href: "/contact", label: { vi: "Liên hệ", en: "Contact" } },
] as const;

const baseSkills = [{ title: "Frontend", items: ["React", "Next.js", "TypeScript", "Tailwind CSS"] }, { title: "Backend & Data", items: ["Node.js", "NestJS", "PostgreSQL", "MongoDB"] }, { title: "Product delivery", items: ["UI/UX", "REST API", "Testing", "Deployment"] }, { title: "Interactive", items: ["React Native", "Unity", "PixiJS", "Game design"] }];


const projectBlueprints = [
  { id: "heritage", title: "Heritage Ginseng", category: "Web", tags: ["Next.js", "NestJS", "PostgreSQL"], status: "live", vi: ["Nền tảng thương mại điện tử đa vai trò với CMS và dashboard vận hành.", "Full-stack development", "Kiến trúc có thể mở rộng cho nội dung và bán hàng."], en: ["A multi-role commerce platform with CMS and an operations dashboard.", "Full-stack development", "Scalable architecture for content and commerce operations."] },
  { id: "commerce", title: "Electronics Commerce", category: "Web", tags: ["React", "Express", "MongoDB"], status: "coming-soon", vi: ["Marketplace điện tử dành cho khách hàng, người bán và quản trị viên.", "Frontend & API", "Hoàn thiện luồng mua hàng cho ba nhóm người dùng."], en: ["An electronics marketplace for customers, sellers and administrators.", "Frontend & API", "Completed commerce flows across three user groups."] },
  { id: "portfolio", title: "DK Coder Portfolio", category: "Web", tags: ["Next.js", "TypeScript", "UI/UX"], status: "live", vi: ["Portfolio cá nhân song ngữ, tích hợp dự án, công cụ, game và bài viết.", "Product engineering", "Xây dựng nền tảng nội dung có thể phát triển lâu dài."], en: ["A bilingual personal portfolio for projects, tools, games and writing.", "Product engineering", "Built a long-lived platform for personal work and content."] },
  { id: "booking", title: "Booking Platform", category: "App", tags: ["React Native", "Next.js", "Prisma"], status: "coming-soon", vi: ["Ứng dụng đặt lịch đa nền tảng cho khách hàng và đối tác vận hành.", "Full-stack mobile", "Kết nối đặt lịch và vận hành trong một hệ thống."], en: ["A cross-platform booking app for customers and operating partners.", "Full-stack mobile", "Connected booking and operations in one system."] },
  { id: "habit-flow", title: "Habit Flow", category: "App", tags: ["React Native", "Expo", "SQLite"], status: "coming-soon", vi: ["Ứng dụng xây dựng thói quen với nhắc lịch và thống kê tiến độ trực quan.", "Mobile development", "Thiết kế trải nghiệm duy trì thói quen đơn giản mỗi ngày."], en: ["A habit-building app with reminders and visual progress tracking.", "Mobile development", "Designed a simple daily habit-retention experience."] },
  { id: "field-service", title: "Field Service Mobile", category: "App", tags: ["Flutter", "Firebase", "Maps"], status: "coming-soon", vi: ["Ứng dụng điều phối công việc hiện trường và cập nhật trạng thái theo thời gian thực.", "App architecture", "Rút ngắn luồng giao việc và báo cáo tại hiện trường."], en: ["A field operations app with assignments and real-time status updates.", "App architecture", "Shortened assignment and field-reporting workflows."] },
  { id: "ocean-quest", title: "Ocean Quest", category: "Game", tags: ["Unity", "C#", "Game Design"], status: "live", vi: ["Game puzzle casual tập trung vào nhịp độ và cảm giác tương tác.", "Gameplay programming", "Xây dựng vòng lặp chơi dễ tiếp cận và có chiều sâu."], en: ["A casual puzzle game focused on pacing and tactile feedback.", "Gameplay programming", "Built an approachable game loop with growing depth."] },
  { id: "pixel-defense", title: "Pixel Defense", category: "Game", tags: ["Unity", "C#", "Aseprite"], status: "coming-soon", vi: ["Tower defense phong cách pixel với hệ thống nâng cấp và nhiều loại kẻ địch.", "Game development", "Thiết kế hệ thống chiến đấu có thể mở rộng nội dung."], en: ["A pixel tower-defense game with upgrades and varied enemy types.", "Game development", "Designed a combat system ready for content expansion."] },
  { id: "word-sprint", title: "Word Sprint", category: "Game", tags: ["PixiJS", "TypeScript", "Web Audio"], status: "coming-soon", vi: ["Game từ vựng chạy trên web với thử thách ngắn và bảng điểm.", "Interactive development", "Tối ưu trải nghiệm chơi nhanh trên cả desktop và mobile."], en: ["A browser word game with short challenges and scoreboards.", "Interactive development", "Optimized quick play across desktop and mobile."] },
  { id: "tool-shelf", title: "Tool Shelf", category: "Tool", tags: ["Next.js", "Web APIs", "PWA"], status: "live", vi: ["Bộ sưu tập tiện ích nhỏ phục vụ công việc số hằng ngày.", "Full-stack development", "Gom nhiều thao tác lặp lại vào một không gian thống nhất."], en: ["A collection of focused utilities for everyday digital work.", "Full-stack development", "Unified recurring tasks in one focused workspace."] },
  { id: "api-playground", title: "API Playground", category: "Tool", tags: ["React", "OpenAPI", "Node.js"], status: "coming-soon", vi: ["Công cụ thử API, lưu request và chia sẻ bộ cấu hình cho đội nhóm.", "Developer tooling", "Giảm thời gian kiểm thử và trao đổi API."], en: ["An API client for testing, saving and sharing request collections.", "Developer tooling", "Reduced API testing and handoff time."] },
  { id: "image-optimizer", title: "Image Optimizer", category: "Tool", tags: ["WebAssembly", "Canvas", "Workers"], status: "coming-soon", vi: ["Công cụ nén, đổi kích thước và chuyển định dạng ảnh ngay trên trình duyệt.", "Frontend engineering", "Xử lý ảnh cục bộ nhanh mà không tải dữ liệu lên máy chủ."], en: ["An in-browser tool for compressing, resizing and converting images.", "Frontend engineering", "Enabled fast local processing without server uploads."] },
  { id: "design-system", title: "Design System Kit", category: "Design", tags: ["Figma", "Tokens", "Storybook"], status: "coming-soon", vi: ["Hệ thống component và token giúp sản phẩm giữ trải nghiệm nhất quán.", "UI/UX & frontend", "Tăng tốc thiết kế và triển khai giao diện giữa các màn hình."], en: ["A component and token system for consistent product experiences.", "UI/UX & frontend", "Accelerated design and implementation across screens."] },
  { id: "analytics", title: "Analytics Dashboard", category: "Design", tags: ["Figma", "React", "Data Viz"], status: "coming-soon", vi: ["Dashboard phân tích dữ liệu vận hành với hệ thống biểu đồ dễ đọc.", "Product design", "Biến dữ liệu phức tạp thành quyết định rõ ràng."], en: ["An operations analytics dashboard with a readable chart system.", "Product design", "Turned complex data into clearer decisions."] },
  { id: "event-brand", title: "Event Brand Studio", category: "Design", tags: ["Figma", "Illustrator", "Motion"], status: "coming-soon", vi: ["Bộ nhận diện và landing page linh hoạt dành cho sự kiện công nghệ.", "Visual & web design", "Tạo ngôn ngữ hình ảnh đồng nhất trên nhiều điểm chạm."], en: ["A flexible identity and landing page system for technology events.", "Visual & web design", "Created a consistent visual language across touchpoints."] },
] as const;

const buildProjects = (language: Language): Project[] => projectBlueprints.map((project) => ({
  id: project.id,
  title: project.title,
  category: project.category,
  tags: [...project.tags],
  status: project.status,
  href: `/projects/${project.id}`,
  description: project[language][0],
  role: project[language][1],
  outcome: project[language][2],
}));
export const portfolio: Record<Language, Content> = {
  vi: { profile: { name: "Trần Đình Khánh", role: "Full-stack Developer", location: "Đà Nẵng, Việt Nam", summary: "Tôi xây dựng những sản phẩm số hữu ích, kết hợp kỹ thuật, trải nghiệm người dùng và tư duy sản phẩm.", values: ["Làm rõ vấn đề trước khi viết code", "Ưu tiên trải nghiệm đơn giản và bền vững", "Luôn học qua sản phẩm thật"], skills: baseSkills }, projects: buildProjects("vi"), tools: [{ id: "tool-shelf", title: "Tool Shelf", description: "Bộ sưu tập các tiện ích nhỏ giúp công việc số gọn gàng hơn.", category: "Utility", tags: ["Web", "Productivity"], status: "coming-soon", href: "/tools" }], playground: [{ id: "ocean", title: "Ocean Quest", description: "Thử nghiệm puzzle casual về nhịp độ, phản hồi và cảm giác tương tác.", category: "Game experiment", tags: ["Unity", "Game design"], status: "coming-soon", href: "/playground" }], posts: [{ id: "notes", title: "Ghi chú khi xây sản phẩm", description: "Các quyết định kỹ thuật, bài học và tài liệu tôi muốn lưu lại.", category: "Engineering notes", tags: ["Notes", "Docs"], status: "coming-soon", href: "/blog" }] },
  en: { profile: { name: "Tran Dinh Khanh", role: "Full-stack Developer", location: "Da Nang, Vietnam", summary: "I build useful digital products by combining engineering, user experience and product thinking.", values: ["Clarify the problem before writing code", "Prefer simple, durable experiences", "Learn through real products"], skills: baseSkills }, projects: buildProjects("en"), tools: [{ id: "tool-shelf", title: "Tool Shelf", description: "A collection of small utilities that make digital work calmer and clearer.", category: "Utility", tags: ["Web", "Productivity"], status: "coming-soon", href: "/tools" }], playground: [{ id: "ocean", title: "Ocean Quest", description: "A casual puzzle experiment about pace, feedback and interaction.", category: "Game experiment", tags: ["Unity", "Game design"], status: "coming-soon", href: "/playground" }], posts: [{ id: "notes", title: "Notes from building products", description: "Technical choices, lessons and documentation worth keeping.", category: "Engineering notes", tags: ["Notes", "Docs"], status: "coming-soon", href: "/blog" }] },
};
