"use client";

import { Check, Clipboard, Download, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { availableGitignoreTemplates, buildCsp, buildGitignore, buildNginx, buildRobots, chmodFromOctal, octalFromPermissions, type BotRule, type PermissionMatrix, type RobotRule } from "./config-file-engine";

type Mode = "csp" | "robots" | "gitignore" | "nginx" | "chmod";
const tabs: { id: Mode; label: string; description: string }[] = [
  { id: "csp", label: "CSP Generator", description: "Build a Content-Security-Policy header with practical presets, source lists, reporting, and a copy-ready response header." },
  { id: "robots", label: "Robots.txt Generator", description: "Control global paths and common crawlers, then export a safe robots.txt with a sitemap reference." },
  { id: "gitignore", label: ".gitignore Generator", description: "Compose a deduplicated .gitignore from language, framework, editor, operating-system, and infrastructure templates." },
  { id: "nginx", label: "Nginx Config Generator", description: "Generate an Nginx server block for static sites, SPAs, HTTPS, reverse proxies, compression, caching, and security headers." },
  { id: "chmod", label: "chmod Calculator", description: "Convert file permissions between octal and symbolic forms, including setuid, setgid, sticky bit, and copy-ready commands." },
];
const cspDirectives = ["default-src", "script-src", "style-src", "img-src", "connect-src", "font-src", "frame-src", "object-src", "base-uri", "form-action"];
const sourceChoices = ["'self'", "'none'", "'unsafe-inline'", "'unsafe-eval'", "data:", "blob:", "https:"];
const copy = async (value: string, setCopied: (value: boolean) => void) => { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1200); };
const download = (value: string, name: string) => { const url = URL.createObjectURL(new Blob([value], { type: "text/plain;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); };
function CopyButton({ value }: { value: string }) { const [copied, setCopied] = useState(false); return <button className="config-copy" onClick={() => void copy(value, setCopied)}>{copied ? <Check size={14} /> : <Clipboard size={14} />}{copied ? "Copied" : "Copy"}</button>; }

export default function ConfigFileWorkbench() {
  const [mode, setMode] = useState<Mode>("csp"); const active = tabs.find((tab) => tab.id === mode)!;
  return <section className="config-workbench"><div className="data-format-tabs config-tabs" role="tablist">{tabs.map((tab) => <button role="tab" aria-selected={mode === tab.id} className={mode === tab.id ? "is-active" : ""} onClick={() => setMode(tab.id)} key={tab.id}>{tab.label}</button>)}</div><div className="config-intro"><h2>{active.label}</h2><p>{active.description}</p></div>{mode === "csp" ? <CspPanel /> : mode === "robots" ? <RobotsPanel /> : mode === "gitignore" ? <GitignorePanel /> : mode === "nginx" ? <NginxPanel /> : <ChmodPanel />}</section>;
}

function CspPanel() {
  const [reportOnly, setReportOnly] = useState(false); const [reportUri, setReportUri] = useState(""); const [custom, setCustom] = useState<Record<string, string>>({});
  const [directives, setDirectives] = useState<Record<string, string[]>>({ "default-src": ["'self'"], "script-src": ["'self'"], "style-src": ["'self'"], "img-src": ["'self'", "data:"], "object-src": ["'none'"], "base-uri": ["'self'"] });
  const result = buildCsp({ reportOnly, reportUri, directives });
  const preset = (kind: "strict" | "moderate" | "open") => setDirectives(kind === "strict" ? { "default-src": ["'self'"], "script-src": ["'self'"], "style-src": ["'self'"], "img-src": ["'self'", "data:"], "object-src": ["'none'"], "base-uri": ["'self'"] } : kind === "moderate" ? { "default-src": ["'self'", "https:"], "script-src": ["'self'", "'unsafe-inline'", "https:"], "style-src": ["'self'", "'unsafe-inline'", "https:"], "img-src": ["'self'", "data:", "https:"], "connect-src": ["'self'", "https:"] } : { "default-src": ["*", "data:", "blob:", "https:"], "script-src": ["*", "'unsafe-inline'", "'unsafe-eval'"], "img-src": ["*", "data:", "blob:"] });
  return <div className="config-split"><div className="config-controls"><div className="config-row"><span>Presets</span><button onClick={() => preset("strict")}>Strict</button><button onClick={() => preset("moderate")}>Moderate</button><button onClick={() => preset("open")}>Open</button></div><label className="config-check"><input type="checkbox" checked={reportOnly} onChange={(event) => setReportOnly(event.target.checked)} />Report-only mode</label><label>Report URI (optional)<input value={reportUri} onChange={(event) => setReportUri(event.target.value)} placeholder="https://report.example.com/csp" /></label>{cspDirectives.map((directive) => <article className="config-directive" key={directive}><header><label className="config-check"><input type="checkbox" checked={Boolean(directives[directive]?.length)} onChange={(event) => setDirectives((current) => ({ ...current, [directive]: event.target.checked ? ["'self'"] : [] }))} />{directive}</label></header>{directives[directive]?.length ? <><div className="config-chips">{directives[directive].map((source) => <button onClick={() => setDirectives((current) => ({ ...current, [directive]: current[directive]!.filter((item) => item !== source) }))} key={source}>{source} ×</button>)}</div><div className="config-chips is-add">{sourceChoices.filter((source) => !directives[directive]!.includes(source)).map((source) => <button onClick={() => setDirectives((current) => ({ ...current, [directive]: [...current[directive]!, source] }))} key={source}>+ {source}</button>)}</div><div className="config-add"><input value={custom[directive] ?? ""} onChange={(event) => setCustom((current) => ({ ...current, [directive]: event.target.value }))} placeholder="custom-source.example.com" /><button onClick={() => { const value = custom[directive]?.trim(); if (value) { setDirectives((current) => ({ ...current, [directive]: [...current[directive]!, value] })); setCustom((current) => ({ ...current, [directive]: "" })); } }}><Plus size={14} />Add</button></div></> : <small>Disabled — no source will be emitted.</small>}</article>)}</div><Output title={result.name} value={`${result.name}: ${result.value}`} file="csp-header.txt" /></div>;
}

function RobotsPanel() {
  const [rules, setRules] = useState<RobotRule[]>([]); const [path, setPath] = useState(""); const [ruleMode, setRuleMode] = useState<RobotRule["mode"]>("Disallow"); const [sitemap, setSitemap] = useState(""); const [bots, setBots] = useState<BotRule[]>([{ name: "Googlebot", mode: "Allow All" }, { name: "Bingbot", mode: "Allow All" }, { name: "GPTBot", mode: "Block All" }, { name: "ClaudeBot", mode: "Block All" }]);
  const output = buildRobots({ globalRules: rules, sitemap, bots });
  return <div className="config-split"><div className="config-controls"><article className="config-card"><h3>Global path rules <small>(User-agent: *)</small></h3><div className="config-chips is-add">{["/admin", "/api", "/private", "/login", "/wp-admin", "/*.json$"].map((value) => <button onClick={() => setRules((current) => current.some((rule) => rule.path === value) ? current : [...current, { mode: "Disallow", path: value }])} key={value}>+ {value}</button>)}</div><div className="config-add"><select value={ruleMode} onChange={(event) => setRuleMode(event.target.value as RobotRule["mode"])}><option>Disallow</option><option>Allow</option></select><input value={path} onChange={(event) => setPath(event.target.value)} placeholder="/path or /*.ext$" /><button onClick={() => { if (path.trim()) { setRules((current) => [...current, { mode: ruleMode, path: path.trim() }]); setPath(""); } }}><Plus size={14} /></button></div>{rules.map((rule, index) => <p className="config-list-row" key={`${rule.path}-${index}`}>{rule.mode}: {rule.path}<button onClick={() => setRules((current) => current.filter((_, item) => item !== index))}><Trash2 size={13} /></button></p>)}</article><label>Sitemap URL<input value={sitemap} onChange={(event) => setSitemap(event.target.value)} placeholder="https://example.com/sitemap.xml" /></label><article className="config-card"><h3>Bot access rules</h3>{bots.map((bot, index) => <div className="config-bot" key={bot.name}><strong>{bot.name}</strong><div>{(["Allow All", "Block All"] as const).map((value) => <button className={bot.mode === value ? "is-active" : ""} onClick={() => setBots((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, mode: value } : item))} key={value}>{value}</button>)}<button onClick={() => setBots((current) => current.filter((_, item) => item !== index))}><Trash2 size={13} /></button></div></div>)}<button className="config-add-bot" onClick={() => setBots((current) => [...current, { name: "CustomBot", mode: "Allow All" }])}><Plus size={14} />Add bot</button></article></div><Output title="robots.txt" value={output} file="robots.txt" /></div>;
}

function GitignorePanel() { const [selected, setSelected] = useState(["Node.js", "Next.js", "VS Code"]); const [custom, setCustom] = useState(""); const output = buildGitignore(selected, custom); return <div className="config-split"><div className="config-controls"><label>Search templates<input placeholder="Filter templates…" /></label><article className="config-card"><h3>Templates</h3><div className="config-template-grid">{availableGitignoreTemplates().map((template) => <button aria-pressed={selected.includes(template)} className={selected.includes(template) ? "is-active" : ""} style={selected.includes(template) ? { backgroundColor: "var(--teal)", color: "var(--control-on-accent)", borderColor: "transparent" } : undefined} onClick={() => setSelected((current) => current.includes(template) ? current.filter((item) => item !== template) : [...current, template])} key={template}>{selected.includes(template) ? "✓ " : ""}{template}</button>)}</div></article><label>Custom rules<textarea value={custom} onChange={(event) => setCustom(event.target.value)} placeholder="# Add your own patterns\n*.local\n.env.secret" /></label></div><Output title=".gitignore" value={output} file=".gitignore" /></div>; }

function NginxPanel() { const [config, setConfig] = useState({ serverName: "example.com", port: 80, root: "/var/www/html", index: "index.html index.htm", ssl: false, sslCertificate: "", sslKey: "", gzip: true, spa: false, proxyPass: "", cacheStatic: true, securityHeaders: true }); const output = buildNginx(config); const set = <K extends keyof typeof config>(key: K, value: (typeof config)[K]) => setConfig((current) => ({ ...current, [key]: value })); return <div className="config-split"><div className="config-controls"><div className="config-row"><span>Preset</span><button onClick={() => setConfig((current) => ({ ...current, spa: false, proxyPass: "" }))}>Static site</button><button onClick={() => setConfig((current) => ({ ...current, proxyPass: "http://127.0.0.1:3000", spa: false }))}>Reverse proxy</button><button onClick={() => setConfig((current) => ({ ...current, spa: true, proxyPass: "" }))}>SPA</button></div><label>Server name<input value={config.serverName} onChange={(event) => set("serverName", event.target.value)} /></label><div className="config-two"><label>Listen port<input type="number" value={config.port} onChange={(event) => set("port", Number(event.target.value))} /></label><label>Root directory<input value={config.root} onChange={(event) => set("root", event.target.value)} /></label></div><label>Index files<input value={config.index} onChange={(event) => set("index", event.target.value)} /></label><label>Reverse proxy target (optional)<input value={config.proxyPass} onChange={(event) => set("proxyPass", event.target.value)} placeholder="http://127.0.0.1:3000" /></label><div className="config-checkbox-grid">{(["ssl", "gzip", "spa", "cacheStatic", "securityHeaders"] as const).map((key) => <label className="config-check" key={key}><input type="checkbox" checked={config[key]} onChange={(event) => set(key, event.target.checked)} />{key.replace(/([A-Z])/g, " $1")}</label>)}</div>{config.ssl && <div className="config-two"><label>SSL certificate<input value={config.sslCertificate} onChange={(event) => set("sslCertificate", event.target.value)} placeholder="/etc/ssl/cert.pem" /></label><label>SSL key<input value={config.sslKey} onChange={(event) => set("sslKey", event.target.value)} placeholder="/etc/ssl/key.pem" /></label></div>}</div><Output title="nginx.conf" value={output} file="nginx.conf" /></div>; }

function ChmodPanel() { const [matrix, setMatrix] = useState<PermissionMatrix>({ owner: [true, true, true], group: [true, false, true], others: [true, false, true], special: { setuid: false, setgid: false, sticky: false } }); const [filename, setFilename] = useState("file.sh"); const octal = octalFromPermissions(matrix); const parsed = chmodFromOctal(octal); const toggle = (group: "owner" | "group" | "others", index: number) => setMatrix((current) => ({ ...current, [group]: current[group].map((value, item) => item === index ? !value : value) })); return <div className="config-chmod"><div className="config-controls"><div className="config-row"><span>Common presets</span>{["644", "755", "777", "600", "400", "700", "664", "750"].map((value) => <button onClick={() => { const data = chmodFromOctal(value); const digits = data.octal.padStart(3, "0").split("").map(Number); const flags = (digit: number) => [Boolean(digit & 4), Boolean(digit & 2), Boolean(digit & 1)]; setMatrix((current) => ({ ...current, owner: flags(digits[0]!), group: flags(digits[1]!), others: flags(digits[2]!) })); }} key={value}>{value}</button>)}</div><table className="config-permission-table"><thead><tr><th>Permission</th><th>Owner</th><th>Group</th><th>Others</th></tr></thead><tbody>{["Read (4)", "Write (2)", "Execute (1)"].map((label, index) => <tr key={label}><td>{label}</td>{(["owner", "group", "others"] as const).map((group) => <td key={group}><input type="checkbox" checked={matrix[group][index]} onChange={() => toggle(group, index)} /></td>)}</tr>)}</tbody></table><div className="config-checkbox-grid">{(["setuid", "setgid", "sticky"] as const).map((key) => <label className="config-check" key={key}><input type="checkbox" checked={matrix.special[key]} onChange={(event) => setMatrix((current) => ({ ...current, special: { ...current.special, [key]: event.target.checked } }))} />{key}</label>)}</div><label>Filename (optional)<input value={filename} onChange={(event) => setFilename(event.target.value)} /></label></div><div className="config-chmod-result"><strong>Octal value <b>{octal}</b></strong><strong>Symbolic <code>{parsed.symbolic}</code></strong><Output title="Command" value={`chmod ${octal} ${filename || "file"}`} file="chmod-command.txt" /><Output title="Symbolic command" value={`chmod u=${parsed.symbolic.slice(0, 3)},g=${parsed.symbolic.slice(3, 6)},o=${parsed.symbolic.slice(6)} ${filename || "file"}`} file="chmod-command.txt" /></div></div>; }

function Output({ title, value, file }: { title: string; value: string; file: string }) { return <section className="config-output"><header><strong>{title}</strong><div><CopyButton value={value} /><button onClick={() => download(value, file)}><Download size={14} />Download</button></div></header><pre>{value || "Select a preset or add values to generate output."}</pre><small>{value.split("\n").length} lines · {new TextEncoder().encode(value).length} bytes</small></section>; }
